// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Subscription.Subscriptions;

public partial class SubscriptionsRequestBuilder
{
    public async Task<SubscriptionSubscription_Response?> GetAllAsync(Action<RequestConfiguration<SubscriptionsRequestBuilder.SubscriptionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SubscriptionSubscriptionResults is null)
        {
            return response;
        }

        var allItems = new List<SubscriptionSubscription>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SubscriptionSubscriptionResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SubscriptionSubscriptionResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new SubscriptionsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SubscriptionSubscription_Response
        {
            D = new SubscriptionSubscription_Response.SubscriptionSubscription_Response_d
            {
                SubscriptionSubscription = allItems
            }
        };

        return finalResponse;
    }
}
