// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Salesorder.GoodsDeliveries;

public partial class GoodsDeliveriesRequestBuilder
{
    public async Task<SalesOrderGoodsDeliveries_Response?> GetAllAsync(Action<RequestConfiguration<GoodsDeliveriesRequestBuilder.GoodsDeliveriesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SalesOrderGoodsDeliveriesResults is null)
        {
            return response;
        }

        var allItems = new List<SalesOrderGoodsDeliveries>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SalesOrderGoodsDeliveriesResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SalesOrderGoodsDeliveriesResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new GoodsDeliveriesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SalesOrderGoodsDeliveries_Response
        {
            D = new SalesOrderGoodsDeliveries_Response.SalesOrderGoodsDeliveries_Response_d
            {
                SalesOrderGoodsDeliveries = allItems
            }
        };

        return finalResponse;
    }
}
