// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Crm.Addresses;

public partial class AddressesRequestBuilder
{
    public async Task<CRMAddresses_Response?> GetAllAsync(Action<RequestConfiguration<AddressesRequestBuilder.AddressesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.CRMAddressesResults is null)
        {
            return response;
        }

        var allItems = new List<CRMAddresses>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.CRMAddressesResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.CRMAddressesResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new AddressesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new CRMAddresses_Response
        {
            D = new CRMAddresses_Response.CRMAddresses_Response_d
            {
                CRMAddresses = allItems
            }
        };

        return finalResponse;
    }
}
