// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Project.TimeAndBillingAccountDetails;

public partial class TimeAndBillingAccountDetailsRequestBuilder
{
    public async Task<ReadProjectTimeAndBillingAccountDetail_Response?> GetAllAsync(Action<RequestConfiguration<TimeAndBillingAccountDetailsRequestBuilder.TimeAndBillingAccountDetailsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadProjectTimeAndBillingAccountDetailResults is null)
        {
            return response;
        }

        var allItems = new List<ReadProjectTimeAndBillingAccountDetail>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadProjectTimeAndBillingAccountDetailResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadProjectTimeAndBillingAccountDetailResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new TimeAndBillingAccountDetailsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadProjectTimeAndBillingAccountDetail_Response
        {
            D = new ReadProjectTimeAndBillingAccountDetail_Response.ReadProjectTimeAndBillingAccountDetail_Response_d
            {
                ReadProjectTimeAndBillingAccountDetail = allItems
            }
        };

        return finalResponse;
    }
}
