// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Accountancy.SolutionLinks;

public partial class SolutionLinksRequestBuilder
{
    public async Task<AccountancySolutionLink_Response?> GetAllAsync(Action<RequestConfiguration<SolutionLinksRequestBuilder.SolutionLinksRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.AccountancySolutionLinkResults is null)
        {
            return response;
        }

        var allItems = new List<AccountancySolutionLink>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.AccountancySolutionLinkResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.AccountancySolutionLinkResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new SolutionLinksRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new AccountancySolutionLink_Response
        {
            D = new AccountancySolutionLink_Response.AccountancySolutionLink_Response_d
            {
                AccountancySolutionLink = allItems
            }
        };

        return finalResponse;
    }
}
