// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sync.CRM.QuotationHeaders;

public partial class QuotationHeadersRequestBuilder
{
    public async Task<SyncCRMQuotationHeader_Response?> GetAllAsync(Action<RequestConfiguration<QuotationHeadersRequestBuilder.QuotationHeadersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SyncCRMQuotationHeaderResults is null)
        {
            return response;
        }

        var allItems = new List<SyncCRMQuotationHeader>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SyncCRMQuotationHeaderResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SyncCRMQuotationHeaderResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new QuotationHeadersRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SyncCRMQuotationHeader_Response
        {
            D = new SyncCRMQuotationHeader_Response.SyncCRMQuotationHeader_Response_d
            {
                SyncCRMQuotationHeader = allItems
            }
        };

        return finalResponse;
    }
}
