// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.General.Layouts;

public partial class LayoutsRequestBuilder
{
    public async Task<GeneralLayout_Response?> GetAllAsync(Action<RequestConfiguration<LayoutsRequestBuilder.LayoutsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.GeneralLayoutResults is null)
        {
            return response;
        }

        var allItems = new List<GeneralLayout>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.GeneralLayoutResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.GeneralLayoutResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new LayoutsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new GeneralLayout_Response
        {
            D = new GeneralLayout_Response.GeneralLayout_Response_d
            {
                GeneralLayout = allItems
            }
        };

        return finalResponse;
    }
}
