<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Exact Online Kiota AuthenticationProvider for IExactOnlineServiceClient</Description>
    <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
    <PackageTags>Exact;ExactOnline;C#;APIs;Client;Interface;Authentication;Tokens;RefreshToken;AccessToken;Kiota;IAuthenticationProvider;AuthenticationProvider</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExactOnline.Api.Client.Authentication.Kiota\ExactOnline.Api.Client.Authentication.Kiota.csproj" />
    <ProjectReference Include="..\ExactOnline.Api.Client.Interfaces\ExactOnline.Api.Client.Interfaces.csproj" />
  </ItemGroup>

</Project>