// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sales.OrderCharges;

public partial class OrderChargesRequestBuilder
{
    public async Task<SalesOrderCharge_Response?> GetAllAsync(Action<RequestConfiguration<OrderChargesRequestBuilder.OrderChargesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SalesOrderChargeResults is null)
        {
            return response;
        }

        var allItems = new List<SalesOrderCharge>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SalesOrderChargeResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SalesOrderChargeResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new OrderChargesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SalesOrderCharge_Response
        {
            D = new SalesOrderCharge_Response.SalesOrderCharge_Response_d
            {
                SalesOrderCharge = allItems
            }
        };

        return finalResponse;
    }
}
