// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sync.Inventory.ItemWarehouses;

public partial class ItemWarehousesRequestBuilder
{
    public async Task<SyncInventoryItemWarehouses_Response?> GetAllAsync(Action<RequestConfiguration<ItemWarehousesRequestBuilder.ItemWarehousesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SyncInventoryItemWarehousesResults is null)
        {
            return response;
        }

        var allItems = new List<SyncInventoryItemWarehouses>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SyncInventoryItemWarehousesResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SyncInventoryItemWarehousesResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ItemWarehousesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SyncInventoryItemWarehouses_Response
        {
            D = new SyncInventoryItemWarehouses_Response.SyncInventoryItemWarehouses_Response_d
            {
                SyncInventoryItemWarehouses = allItems
            }
        };

        return finalResponse;
    }
}
