// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Documents.Documents;

public partial class DocumentsRequestBuilder
{
    public async Task<DocumentsDocument_Response?> GetAllAsync(Action<RequestConfiguration<DocumentsRequestBuilder.DocumentsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.DocumentsDocumentResults is null)
        {
            return response;
        }

        var allItems = new List<DocumentsDocument>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.DocumentsDocumentResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.DocumentsDocumentResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new DocumentsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new DocumentsDocument_Response
        {
            D = new DocumentsDocument_Response.DocumentsDocument_Response_d
            {
                DocumentsDocument = allItems
            }
        };

        return finalResponse;
    }
}
