// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Hrm.JobTitles;

public partial class JobTitlesRequestBuilder
{
    public async Task<HRMJobTitle_Response?> GetAllAsync(Action<RequestConfiguration<JobTitlesRequestBuilder.JobTitlesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.HRMJobTitleResults is null)
        {
            return response;
        }

        var allItems = new List<HRMJobTitle>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.HRMJobTitleResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.HRMJobTitleResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new JobTitlesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new HRMJobTitle_Response
        {
            D = new HRMJobTitle_Response.HRMJobTitle_Response_d
            {
                HRMJobTitle = allItems
            }
        };

        return finalResponse;
    }
}
