// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Documents.DocumentTypes;

public partial class DocumentTypesRequestBuilder
{
    public async Task<DocumentsDocumentType_Response?> GetAllAsync(Action<RequestConfiguration<DocumentTypesRequestBuilder.DocumentTypesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.DocumentsDocumentTypeResults is null)
        {
            return response;
        }

        var allItems = new List<DocumentsDocumentType>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.DocumentsDocumentTypeResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.DocumentsDocumentTypeResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new DocumentTypesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new DocumentsDocumentType_Response
        {
            D = new DocumentsDocumentType_Response.DocumentsDocumentType_Response_d
            {
                DocumentsDocumentType = allItems
            }
        };

        return finalResponse;
    }
}
