// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Crm.ReasonCodes;

public partial class ReasonCodesRequestBuilder
{
    public async Task<CRMReasonCode_Response?> GetAllAsync(Action<RequestConfiguration<ReasonCodesRequestBuilder.ReasonCodesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.CRMReasonCodeResults is null)
        {
            return response;
        }

        var allItems = new List<CRMReasonCode>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.CRMReasonCodeResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.CRMReasonCodeResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ReasonCodesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new CRMReasonCode_Response
        {
            D = new CRMReasonCode_Response.CRMReasonCode_Response_d
            {
                CRMReasonCode = allItems
            }
        };

        return finalResponse;
    }
}
