// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Bulk.CRM.Accounts;

public partial class AccountsRequestBuilder
{
    public async Task<BulkCRMAccount_Response?> GetAllAsync(Action<RequestConfiguration<AccountsRequestBuilder.AccountsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.BulkCRMAccountResults is null)
        {
            return response;
        }

        var allItems = new List<BulkCRMAccount>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.BulkCRMAccountResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.BulkCRMAccountResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new AccountsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new BulkCRMAccount_Response
        {
            D = new BulkCRMAccount_Response.BulkCRMAccount_Response_d
            {
                BulkCRMAccount = allItems
            }
        };

        return finalResponse;
    }
}
