// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sync.CRM.Contacts;

public partial class ContactsRequestBuilder
{
    public async Task<SyncCRMContacts_Response?> GetAllAsync(Action<RequestConfiguration<ContactsRequestBuilder.ContactsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SyncCRMContactsResults is null)
        {
            return response;
        }

        var allItems = new List<SyncCRMContacts>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SyncCRMContactsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SyncCRMContactsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ContactsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SyncCRMContacts_Response
        {
            D = new SyncCRMContacts_Response.SyncCRMContacts_Response_d
            {
                SyncCRMContacts = allItems
            }
        };

        return finalResponse;
    }
}
