// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Manufacturing.ShopOrders;

public partial class ShopOrdersRequestBuilder
{
    public async Task<ManufacturingShopOrders_Response?> GetAllAsync(Action<RequestConfiguration<ShopOrdersRequestBuilder.ShopOrdersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ManufacturingShopOrdersResults is null)
        {
            return response;
        }

        var allItems = new List<ManufacturingShopOrders>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ManufacturingShopOrdersResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ManufacturingShopOrdersResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ShopOrdersRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ManufacturingShopOrders_Response
        {
            D = new ManufacturingShopOrders_Response.ManufacturingShopOrders_Response_d
            {
                ManufacturingShopOrders = allItems
            }
        };

        return finalResponse;
    }
}
