// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sync.Manufacturing.BillOfMaterialVersions;

public partial class BillOfMaterialVersionsRequestBuilder
{
    public async Task<SyncManufacturingBillOfMaterialVersions_Response?> GetAllAsync(Action<RequestConfiguration<BillOfMaterialVersionsRequestBuilder.BillOfMaterialVersionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SyncManufacturingBillOfMaterialVersionsResults is null)
        {
            return response;
        }

        var allItems = new List<SyncManufacturingBillOfMaterialVersions>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SyncManufacturingBillOfMaterialVersionsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SyncManufacturingBillOfMaterialVersionsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new BillOfMaterialVersionsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SyncManufacturingBillOfMaterialVersions_Response
        {
            D = new SyncManufacturingBillOfMaterialVersions_Response.SyncManufacturingBillOfMaterialVersions_Response_d
            {
                SyncManufacturingBillOfMaterialVersions = allItems
            }
        };

        return finalResponse;
    }
}
