// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sync.CRM.Accounts;

public partial class AccountsRequestBuilder
{
    public async Task<SyncCRMAccount_Response?> GetAllAsync(Action<RequestConfiguration<AccountsRequestBuilder.AccountsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SyncCRMAccountResults is null)
        {
            return response;
        }

        var allItems = new List<SyncCRMAccount>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SyncCRMAccountResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SyncCRMAccountResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new AccountsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SyncCRMAccount_Response
        {
            D = new SyncCRMAccount_Response.SyncCRMAccount_Response_d
            {
                SyncCRMAccount = allItems
            }
        };

        return finalResponse;
    }
}
