// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Logistics.ItemExtraField;

public partial class ItemExtraFieldRequestBuilder
{
    public async Task<ReadLogisticsItemExtraField_Response?> GetAllAsync(Action<RequestConfiguration<ItemExtraFieldRequestBuilder.ItemExtraFieldRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadLogisticsItemExtraFieldResults is null)
        {
            return response;
        }

        var allItems = new List<ReadLogisticsItemExtraField>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadLogisticsItemExtraFieldResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadLogisticsItemExtraFieldResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ItemExtraFieldRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadLogisticsItemExtraField_Response
        {
            D = new ReadLogisticsItemExtraField_Response.ReadLogisticsItemExtraField_Response_d
            {
                ReadLogisticsItemExtraField = allItems
            }
        };

        return finalResponse;
    }
}
