// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Assets.CommercialBuildingValues;

public partial class CommercialBuildingValuesRequestBuilder
{
    public async Task<AssetsCommercialBuildingValue_Response?> GetAllAsync(Action<RequestConfiguration<CommercialBuildingValuesRequestBuilder.CommercialBuildingValuesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.AssetsCommercialBuildingValueResults is null)
        {
            return response;
        }

        var allItems = new List<AssetsCommercialBuildingValue>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.AssetsCommercialBuildingValueResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.AssetsCommercialBuildingValueResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new CommercialBuildingValuesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new AssetsCommercialBuildingValue_Response
        {
            D = new AssetsCommercialBuildingValue_Response.AssetsCommercialBuildingValue_Response_d
            {
                AssetsCommercialBuildingValue = allItems
            }
        };

        return finalResponse;
    }
}
