// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Purchaseorder.GoodsReceiptLines;

public partial class GoodsReceiptLinesRequestBuilder
{
    public async Task<PurchaseOrderGoodsReceiptLine_Response?> GetAllAsync(Action<RequestConfiguration<GoodsReceiptLinesRequestBuilder.GoodsReceiptLinesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.PurchaseOrderGoodsReceiptLineResults is null)
        {
            return response;
        }

        var allItems = new List<PurchaseOrderGoodsReceiptLine>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.PurchaseOrderGoodsReceiptLineResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.PurchaseOrderGoodsReceiptLineResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new GoodsReceiptLinesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new PurchaseOrderGoodsReceiptLine_Response
        {
            D = new PurchaseOrderGoodsReceiptLine_Response.PurchaseOrderGoodsReceiptLine_Response_d
            {
                PurchaseOrderGoodsReceiptLine = allItems
            }
        };

        return finalResponse;
    }
}
