// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Cashflow.Receivables;

public partial class ReceivablesRequestBuilder
{
    public async Task<CashflowReceivable_Response?> GetAllAsync(Action<RequestConfiguration<ReceivablesRequestBuilder.ReceivablesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.CashflowReceivableResults is null)
        {
            return response;
        }

        var allItems = new List<CashflowReceivable>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.CashflowReceivableResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.CashflowReceivableResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ReceivablesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new CashflowReceivable_Response
        {
            D = new CashflowReceivable_Response.CashflowReceivable_Response_d
            {
                CashflowReceivable = allItems
            }
        };

        return finalResponse;
    }
}
