// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Users.UserRoles;

public partial class UserRolesRequestBuilder
{
    public async Task<UsersUserRole_Response?> GetAllAsync(Action<RequestConfiguration<UserRolesRequestBuilder.UserRolesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.UsersUserRoleResults is null)
        {
            return response;
        }

        var allItems = new List<UsersUserRole>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.UsersUserRoleResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.UsersUserRoleResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new UserRolesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new UsersUserRole_Response
        {
            D = new UsersUserRole_Response.UsersUserRole_Response_d
            {
                UsersUserRole = allItems
            }
        };

        return finalResponse;
    }
}
