// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Project.RecentHours;

public partial class RecentHoursRequestBuilder
{
    public async Task<ReadProjectRecentHour_Response?> GetAllAsync(Action<RequestConfiguration<RecentHoursRequestBuilder.RecentHoursRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadProjectRecentHourResults is null)
        {
            return response;
        }

        var allItems = new List<ReadProjectRecentHour>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadProjectRecentHourResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadProjectRecentHourResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new RecentHoursRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadProjectRecentHour_Response
        {
            D = new ReadProjectRecentHour_Response.ReadProjectRecentHour_Response_d
            {
                ReadProjectRecentHour = allItems
            }
        };

        return finalResponse;
    }
}
