// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Project.CostTransactions;

public partial class CostTransactionsRequestBuilder
{
    public async Task<ProjectCostTransaction_Response?> GetAllAsync(Action<RequestConfiguration<CostTransactionsRequestBuilder.CostTransactionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ProjectCostTransactionResults is null)
        {
            return response;
        }

        var allItems = new List<ProjectCostTransaction>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ProjectCostTransactionResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ProjectCostTransactionResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new CostTransactionsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ProjectCostTransaction_Response
        {
            D = new ProjectCostTransaction_Response.ProjectCostTransaction_Response_d
            {
                ProjectCostTransaction = allItems
            }
        };

        return finalResponse;
    }
}
