// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Purchaseentry.PurchaseEntryLines;

public partial class PurchaseEntryLinesRequestBuilder
{
    public async Task<PurchaseEntryPurchaseEntryLines_Response?> GetAllAsync(Action<RequestConfiguration<PurchaseEntryLinesRequestBuilder.PurchaseEntryLinesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.PurchaseEntryPurchaseEntryLinesResults is null)
        {
            return response;
        }

        var allItems = new List<PurchaseEntryPurchaseEntryLines>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.PurchaseEntryPurchaseEntryLinesResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.PurchaseEntryPurchaseEntryLinesResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new PurchaseEntryLinesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new PurchaseEntryPurchaseEntryLines_Response
        {
            D = new PurchaseEntryPurchaseEntryLines_Response.PurchaseEntryPurchaseEntryLines_Response_d
            {
                PurchaseEntryPurchaseEntryLines = allItems
            }
        };

        return finalResponse;
    }
}
