// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Financial.ReceivablesList;

public partial class ReceivablesListRequestBuilder
{
    public async Task<ReadFinancialReceivablesList_Response?> GetAllAsync(Action<RequestConfiguration<ReceivablesListRequestBuilder.ReceivablesListRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadFinancialReceivablesListResults is null)
        {
            return response;
        }

        var allItems = new List<ReadFinancialReceivablesList>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadFinancialReceivablesListResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadFinancialReceivablesListResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ReceivablesListRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadFinancialReceivablesList_Response
        {
            D = new ReadFinancialReceivablesList_Response.ReadFinancialReceivablesList_Response_d
            {
                ReadFinancialReceivablesList = allItems
            }
        };

        return finalResponse;
    }
}
