// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Vat.VatPercentages;

public partial class VatPercentagesRequestBuilder
{
    public async Task<VATVatPercentages_Response?> GetAllAsync(Action<RequestConfiguration<VatPercentagesRequestBuilder.VatPercentagesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.VATVatPercentagesResults is null)
        {
            return response;
        }

        var allItems = new List<VATVatPercentages>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.VATVatPercentagesResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.VATVatPercentagesResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new VatPercentagesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new VATVatPercentages_Response
        {
            D = new VATVatPercentages_Response.VATVatPercentages_Response_d
            {
                VATVatPercentages = allItems
            }
        };

        return finalResponse;
    }
}
