// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Inventory.ItemWarehousePlanningDetails;

public partial class ItemWarehousePlanningDetailsRequestBuilder
{
    public async Task<InventoryItemWarehousePlanningDetail_Response?> GetAllAsync(Action<RequestConfiguration<ItemWarehousePlanningDetailsRequestBuilder.ItemWarehousePlanningDetailsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.InventoryItemWarehousePlanningDetailResults is null)
        {
            return response;
        }

        var allItems = new List<InventoryItemWarehousePlanningDetail>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.InventoryItemWarehousePlanningDetailResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.InventoryItemWarehousePlanningDetailResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ItemWarehousePlanningDetailsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new InventoryItemWarehousePlanningDetail_Response
        {
            D = new InventoryItemWarehousePlanningDetail_Response.InventoryItemWarehousePlanningDetail_Response_d
            {
                InventoryItemWarehousePlanningDetail = allItems
            }
        };

        return finalResponse;
    }
}
