// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sync.SalesOrder.SalesOrderLines;

public partial class SalesOrderLinesRequestBuilder
{
    public async Task<SyncSalesOrderSalesOrderLine_Response?> GetAllAsync(Action<RequestConfiguration<SalesOrderLinesRequestBuilder.SalesOrderLinesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SyncSalesOrderSalesOrderLineResults is null)
        {
            return response;
        }

        var allItems = new List<SyncSalesOrderSalesOrderLine>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SyncSalesOrderSalesOrderLineResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SyncSalesOrderSalesOrderLineResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new SalesOrderLinesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SyncSalesOrderSalesOrderLine_Response
        {
            D = new SyncSalesOrderSalesOrderLine_Response.SyncSalesOrderSalesOrderLine_Response_d
            {
                SyncSalesOrderSalesOrderLine = allItems
            }
        };

        return finalResponse;
    }
}
