// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Accountancy.InvolvedUserRoles;

public partial class InvolvedUserRolesRequestBuilder
{
    public async Task<AccountancyInvolvedUserRole_Response?> GetAllAsync(Action<RequestConfiguration<InvolvedUserRolesRequestBuilder.InvolvedUserRolesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.AccountancyInvolvedUserRoleResults is null)
        {
            return response;
        }

        var allItems = new List<AccountancyInvolvedUserRole>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.AccountancyInvolvedUserRoleResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.AccountancyInvolvedUserRoleResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new InvolvedUserRolesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new AccountancyInvolvedUserRole_Response
        {
            D = new AccountancyInvolvedUserRole_Response.AccountancyInvolvedUserRole_Response_d
            {
                AccountancyInvolvedUserRole = allItems
            }
        };

        return finalResponse;
    }
}
