// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sync.Inventory.StockSerialBatchNumbers;

public partial class StockSerialBatchNumbersRequestBuilder
{
    public async Task<SyncInventoryStockSerialBatchNumber_Response?> GetAllAsync(Action<RequestConfiguration<StockSerialBatchNumbersRequestBuilder.StockSerialBatchNumbersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SyncInventoryStockSerialBatchNumberResults is null)
        {
            return response;
        }

        var allItems = new List<SyncInventoryStockSerialBatchNumber>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SyncInventoryStockSerialBatchNumberResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SyncInventoryStockSerialBatchNumberResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new StockSerialBatchNumbersRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SyncInventoryStockSerialBatchNumber_Response
        {
            D = new SyncInventoryStockSerialBatchNumber_Response.SyncInventoryStockSerialBatchNumber_Response_d
            {
                SyncInventoryStockSerialBatchNumber = allItems
            }
        };

        return finalResponse;
    }
}
