// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Financialtransaction.BankEntries;

public partial class BankEntriesRequestBuilder
{
    public async Task<FinancialTransactionBankEntry_Response?> GetAllAsync(Action<RequestConfiguration<BankEntriesRequestBuilder.BankEntriesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.FinancialTransactionBankEntryResults is null)
        {
            return response;
        }

        var allItems = new List<FinancialTransactionBankEntry>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.FinancialTransactionBankEntryResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.FinancialTransactionBankEntryResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new BankEntriesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new FinancialTransactionBankEntry_Response
        {
            D = new FinancialTransactionBankEntry_Response.FinancialTransactionBankEntry_Response_d
            {
                FinancialTransactionBankEntry = allItems
            }
        };

        return finalResponse;
    }
}
