// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sync.HRM.AbsenceRegistrations;

public partial class AbsenceRegistrationsRequestBuilder
{
    public async Task<SyncHRMAbsenceRegistrations_Response?> GetAllAsync(Action<RequestConfiguration<AbsenceRegistrationsRequestBuilder.AbsenceRegistrationsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SyncHRMAbsenceRegistrationsResults is null)
        {
            return response;
        }

        var allItems = new List<SyncHRMAbsenceRegistrations>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SyncHRMAbsenceRegistrationsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SyncHRMAbsenceRegistrationsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new AbsenceRegistrationsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SyncHRMAbsenceRegistrations_Response
        {
            D = new SyncHRMAbsenceRegistrations_Response.SyncHRMAbsenceRegistrations_Response_d
            {
                SyncHRMAbsenceRegistrations = allItems
            }
        };

        return finalResponse;
    }
}
