// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sales.SalesPriceLists;

public partial class SalesPriceListsRequestBuilder
{
    public async Task<SalesSalesPriceLists_Response?> GetAllAsync(Action<RequestConfiguration<SalesPriceListsRequestBuilder.SalesPriceListsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SalesSalesPriceListsResults is null)
        {
            return response;
        }

        var allItems = new List<SalesSalesPriceLists>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SalesSalesPriceListsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SalesSalesPriceListsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new SalesPriceListsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SalesSalesPriceLists_Response
        {
            D = new SalesSalesPriceLists_Response.SalesSalesPriceLists_Response_d
            {
                SalesSalesPriceLists = allItems
            }
        };

        return finalResponse;
    }
}
