// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Logistics.SalesItemPrices;

public partial class SalesItemPricesRequestBuilder
{
    public async Task<LogisticsSalesItemPrice_Response?> GetAllAsync(Action<RequestConfiguration<SalesItemPricesRequestBuilder.SalesItemPricesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.LogisticsSalesItemPriceResults is null)
        {
            return response;
        }

        var allItems = new List<LogisticsSalesItemPrice>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.LogisticsSalesItemPriceResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.LogisticsSalesItemPriceResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new SalesItemPricesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new LogisticsSalesItemPrice_Response
        {
            D = new LogisticsSalesItemPrice_Response.LogisticsSalesItemPrice_Response_d
            {
                LogisticsSalesItemPrice = allItems
            }
        };

        return finalResponse;
    }
}
