// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Subscription.SubscriptionLines;

public partial class SubscriptionLinesRequestBuilder
{
    public async Task<SubscriptionSubscriptionLine_Response?> GetAllAsync(Action<RequestConfiguration<SubscriptionLinesRequestBuilder.SubscriptionLinesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SubscriptionSubscriptionLineResults is null)
        {
            return response;
        }

        var allItems = new List<SubscriptionSubscriptionLine>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SubscriptionSubscriptionLineResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SubscriptionSubscriptionLineResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new SubscriptionLinesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SubscriptionSubscriptionLine_Response
        {
            D = new SubscriptionSubscriptionLine_Response.SubscriptionSubscriptionLine_Response_d
            {
                SubscriptionSubscriptionLine = allItems
            }
        };

        return finalResponse;
    }
}
