// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Project.HourEntryRecentAccountsByProject;

public partial class HourEntryRecentAccountsByProjectRequestBuilder
{
    public async Task<ReadProjectHourEntryRecentAccountsByProject_Response?> GetAllAsync(Action<RequestConfiguration<HourEntryRecentAccountsByProjectRequestBuilder.HourEntryRecentAccountsByProjectRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadProjectHourEntryRecentAccountsByProjectResults is null)
        {
            return response;
        }

        var allItems = new List<ReadProjectHourEntryRecentAccountsByProject>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadProjectHourEntryRecentAccountsByProjectResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadProjectHourEntryRecentAccountsByProjectResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new HourEntryRecentAccountsByProjectRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadProjectHourEntryRecentAccountsByProject_Response
        {
            D = new ReadProjectHourEntryRecentAccountsByProject_Response.ReadProjectHourEntryRecentAccountsByProject_Response_d
            {
                ReadProjectHourEntryRecentAccountsByProject = allItems
            }
        };

        return finalResponse;
    }
}
