// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Cashflow.PaymentConditions;

public partial class PaymentConditionsRequestBuilder
{
    public async Task<CashflowPaymentCondition_Response?> GetAllAsync(Action<RequestConfiguration<PaymentConditionsRequestBuilder.PaymentConditionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.CashflowPaymentConditionResults is null)
        {
            return response;
        }

        var allItems = new List<CashflowPaymentCondition>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.CashflowPaymentConditionResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.CashflowPaymentConditionResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new PaymentConditionsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new CashflowPaymentCondition_Response
        {
            D = new CashflowPaymentCondition_Response.CashflowPaymentCondition_Response_d
            {
                CashflowPaymentCondition = allItems
            }
        };

        return finalResponse;
    }
}
