// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Financial.RevenueListByYearAndStatus;

public partial class RevenueListByYearAndStatusRequestBuilder
{
    public async Task<ReadFinancialRevenueListByYearAndStatu_Response?> GetAllAsync(Action<RequestConfiguration<RevenueListByYearAndStatusRequestBuilder.RevenueListByYearAndStatusRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadFinancialRevenueListByYearAndStatuResults is null)
        {
            return response;
        }

        var allItems = new List<ReadFinancialRevenueListByYearAndStatu>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadFinancialRevenueListByYearAndStatuResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadFinancialRevenueListByYearAndStatuResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new RevenueListByYearAndStatusRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadFinancialRevenueListByYearAndStatu_Response
        {
            D = new ReadFinancialRevenueListByYearAndStatu_Response.ReadFinancialRevenueListByYearAndStatu_Response_d
            {
                ReadFinancialRevenueListByYearAndStatu = allItems
            }
        };

        return finalResponse;
    }
}
