// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Manufacturing.MaterialReversals;

public partial class MaterialReversalsRequestBuilder
{
    public async Task<ManufacturingMaterialReversal_Response?> GetAllAsync(Action<RequestConfiguration<MaterialReversalsRequestBuilder.MaterialReversalsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ManufacturingMaterialReversalResults is null)
        {
            return response;
        }

        var allItems = new List<ManufacturingMaterialReversal>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ManufacturingMaterialReversalResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ManufacturingMaterialReversalResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new MaterialReversalsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ManufacturingMaterialReversal_Response
        {
            D = new ManufacturingMaterialReversal_Response.ManufacturingMaterialReversal_Response_d
            {
                ManufacturingMaterialReversal = allItems
            }
        };

        return finalResponse;
    }
}
