// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Financial.FinancialPeriods;

public partial class FinancialPeriodsRequestBuilder
{
    public async Task<FinancialFinancialPeriod_Response?> GetAllAsync(Action<RequestConfiguration<FinancialPeriodsRequestBuilder.FinancialPeriodsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.FinancialFinancialPeriodResults is null)
        {
            return response;
        }

        var allItems = new List<FinancialFinancialPeriod>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.FinancialFinancialPeriodResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.FinancialFinancialPeriodResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new FinancialPeriodsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new FinancialFinancialPeriod_Response
        {
            D = new FinancialFinancialPeriod_Response.FinancialFinancialPeriod_Response_d
            {
                FinancialFinancialPeriod = allItems
            }
        };

        return finalResponse;
    }
}
