// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Financial.FinancialPeriods;

public partial class FinancialPeriodsRequestBuilder
{
    public async Task<FinancialFinancialPeriods_Response?> GetAllAsync(Action<RequestConfiguration<FinancialPeriodsRequestBuilder.FinancialPeriodsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.FinancialFinancialPeriodsResults is null)
        {
            return response;
        }

        var allItems = new List<FinancialFinancialPeriods>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.FinancialFinancialPeriodsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.FinancialFinancialPeriodsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new FinancialPeriodsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new FinancialFinancialPeriods_Response
        {
            D = new FinancialFinancialPeriods_Response.FinancialFinancialPeriods_Response_d
            {
                FinancialFinancialPeriods = allItems
            }
        };

        return finalResponse;
    }
}
