// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Salesinvoice.SalesInvoices;

public partial class SalesInvoicesRequestBuilder
{
    public async Task<SalesInvoiceSalesInvoices_Response?> GetAllAsync(Action<RequestConfiguration<SalesInvoicesRequestBuilder.SalesInvoicesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SalesInvoiceSalesInvoicesResults is null)
        {
            return response;
        }

        var allItems = new List<SalesInvoiceSalesInvoices>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SalesInvoiceSalesInvoicesResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SalesInvoiceSalesInvoicesResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new SalesInvoicesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SalesInvoiceSalesInvoices_Response
        {
            D = new SalesInvoiceSalesInvoices_Response.SalesInvoiceSalesInvoices_Response_d
            {
                SalesInvoiceSalesInvoices = allItems
            }
        };

        return finalResponse;
    }
}
