// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Project.RecentHoursByNumberOfWeeks;

public partial class RecentHoursByNumberOfWeeksRequestBuilder
{
    public async Task<ReadProjectRecentHoursByNumberOfWeek_Response?> GetAllAsync(Action<RequestConfiguration<RecentHoursByNumberOfWeeksRequestBuilder.RecentHoursByNumberOfWeeksRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadProjectRecentHoursByNumberOfWeekResults is null)
        {
            return response;
        }

        var allItems = new List<ReadProjectRecentHoursByNumberOfWeek>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadProjectRecentHoursByNumberOfWeekResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadProjectRecentHoursByNumberOfWeekResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new RecentHoursByNumberOfWeeksRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadProjectRecentHoursByNumberOfWeek_Response
        {
            D = new ReadProjectRecentHoursByNumberOfWeek_Response.ReadProjectRecentHoursByNumberOfWeek_Response_d
            {
                ReadProjectRecentHoursByNumberOfWeek = allItems
            }
        };

        return finalResponse;
    }
}
