// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Logistics.Incoterms;

public partial class IncotermsRequestBuilder
{
    public async Task<LogisticsIncoterms_Response?> GetAllAsync(Action<RequestConfiguration<IncotermsRequestBuilder.IncotermsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.LogisticsIncotermsResults is null)
        {
            return response;
        }

        var allItems = new List<LogisticsIncoterms>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.LogisticsIncotermsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.LogisticsIncotermsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new IncotermsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new LogisticsIncoterms_Response
        {
            D = new LogisticsIncoterms_Response.LogisticsIncoterms_Response_d
            {
                LogisticsIncoterms = allItems
            }
        };

        return finalResponse;
    }
}
