// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Logistics.ItemGroups;

public partial class ItemGroupsRequestBuilder
{
    public async Task<LogisticsItemGroup_Response?> GetAllAsync(Action<RequestConfiguration<ItemGroupsRequestBuilder.ItemGroupsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.LogisticsItemGroupResults is null)
        {
            return response;
        }

        var allItems = new List<LogisticsItemGroup>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.LogisticsItemGroupResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.LogisticsItemGroupResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ItemGroupsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new LogisticsItemGroup_Response
        {
            D = new LogisticsItemGroup_Response.LogisticsItemGroup_Response_d
            {
                LogisticsItemGroup = allItems
            }
        };

        return finalResponse;
    }
}
