// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Crm.Contacts;

public partial class ContactsRequestBuilder
{
    public async Task<CRMContact_Response?> GetAllAsync(Action<RequestConfiguration<ContactsRequestBuilder.ContactsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.CRMContactResults is null)
        {
            return response;
        }

        var allItems = new List<CRMContact>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.CRMContactResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.CRMContactResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ContactsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new CRMContact_Response
        {
            D = new CRMContact_Response.CRMContact_Response_d
            {
                CRMContact = allItems
            }
        };

        return finalResponse;
    }
}
