<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>ExactOnline Authentication Token Storage using SqlServer</Description>
    <TargetFramework>net8.0</TargetFramework>
    <PackageTags>Exact;ExactOnline;C#;APIs;Client;Authentication;Tokens;RefreshToken;Storage;SQL;SqlServer</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\ExactOnline.Api.Client.Authentication.Storage.SqlServer\Data\ExactOnlineToken.cs" Link="Data\ExactOnlineToken.cs" />
    <Compile Include="..\ExactOnline.Api.Client.Authentication.Storage.SqlServer\Data\ExactOnlineTokenDbContext.cs" Link="Data\ExactOnlineTokenDbContext.cs" />
    <Compile Include="..\ExactOnline.Api.Client.Authentication.Storage.SqlServer\Data\ExactOnlineTokenDbContext.Extensions.cs" Link="Data\ExactOnlineTokenDbContext.Extensions.cs" />
    <Compile Include="..\ExactOnline.Api.Client.Authentication.Storage.SqlServer\ExactTokenStorageEntityFrameworkCoreService.cs" Link="ExactTokenStorageEntityFrameworkCoreService.cs" />
    <Compile Include="..\ExactOnline.Api.Client.Authentication.Storage.SqlServer\Options\ExactOnlineEntityFrameworkCoreStorageOptions.cs" Link="Options\ExactOnlineEntityFrameworkCoreStorageOptions.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.TimeProvider" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExactOnline.Api.Client.Authentication.Abstractions\ExactOnline.Api.Client.Authentication.Abstractions.csproj" />
  </ItemGroup>

</Project>