// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Accountancy.TaskTypes;

public partial class TaskTypesRequestBuilder
{
    public async Task<AccountancyTaskType_Response?> GetAllAsync(Action<RequestConfiguration<TaskTypesRequestBuilder.TaskTypesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.AccountancyTaskTypeResults is null)
        {
            return response;
        }

        var allItems = new List<AccountancyTaskType>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.AccountancyTaskTypeResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.AccountancyTaskTypeResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new TaskTypesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new AccountancyTaskType_Response
        {
            D = new AccountancyTaskType_Response.AccountancyTaskType_Response_d
            {
                AccountancyTaskType = allItems
            }
        };

        return finalResponse;
    }
}
