// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Crm.Opportunities;

public partial class OpportunitiesRequestBuilder
{
    public async Task<CRMOpportunity_Response?> GetAllAsync(Action<RequestConfiguration<OpportunitiesRequestBuilder.OpportunitiesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.CRMOpportunityResults is null)
        {
            return response;
        }

        var allItems = new List<CRMOpportunity>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.CRMOpportunityResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.CRMOpportunityResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new OpportunitiesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new CRMOpportunity_Response
        {
            D = new CRMOpportunity_Response.CRMOpportunity_Response_d
            {
                CRMOpportunity = allItems
            }
        };

        return finalResponse;
    }
}
