// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Cashflow.DirectDebitMandates;

public partial class DirectDebitMandatesRequestBuilder
{
    public async Task<CashflowDirectDebitMandate_Response?> GetAllAsync(Action<RequestConfiguration<DirectDebitMandatesRequestBuilder.DirectDebitMandatesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.CashflowDirectDebitMandateResults is null)
        {
            return response;
        }

        var allItems = new List<CashflowDirectDebitMandate>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.CashflowDirectDebitMandateResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.CashflowDirectDebitMandateResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new DirectDebitMandatesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new CashflowDirectDebitMandate_Response
        {
            D = new CashflowDirectDebitMandate_Response.CashflowDirectDebitMandate_Response_d
            {
                CashflowDirectDebitMandate = allItems
            }
        };

        return finalResponse;
    }
}
