// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Crm.AccountDocuments;

public partial class AccountDocumentsRequestBuilder
{
    public async Task<ReadCRMAccountDocuments_Response?> GetAllAsync(Action<RequestConfiguration<AccountDocumentsRequestBuilder.AccountDocumentsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadCRMAccountDocumentsResults is null)
        {
            return response;
        }

        var allItems = new List<ReadCRMAccountDocuments>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadCRMAccountDocumentsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadCRMAccountDocumentsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new AccountDocumentsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadCRMAccountDocuments_Response
        {
            D = new ReadCRMAccountDocuments_Response.ReadCRMAccountDocuments_Response_d
            {
                ReadCRMAccountDocuments = allItems
            }
        };

        return finalResponse;
    }
}
