// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Openingbalance.PreviousYear.AfterEntry;

public partial class AfterEntryRequestBuilder
{
    public async Task<OpeningBalancePreviousYearAfterEntry_Response?> GetAllAsync(Action<RequestConfiguration<AfterEntryRequestBuilder.AfterEntryRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.OpeningBalancePreviousYearAfterEntryResults is null)
        {
            return response;
        }

        var allItems = new List<OpeningBalancePreviousYearAfterEntry>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.OpeningBalancePreviousYearAfterEntryResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.OpeningBalancePreviousYearAfterEntryResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new AfterEntryRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new OpeningBalancePreviousYearAfterEntry_Response
        {
            D = new OpeningBalancePreviousYearAfterEntry_Response.OpeningBalancePreviousYearAfterEntry_Response_d
            {
                OpeningBalancePreviousYearAfterEntry = allItems
            }
        };

        return finalResponse;
    }
}
