// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Financial.AgingPayablesList;

public partial class AgingPayablesListRequestBuilder
{
    public async Task<ReadFinancialAgingPayablesList_Response?> GetAllAsync(Action<RequestConfiguration<AgingPayablesListRequestBuilder.AgingPayablesListRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadFinancialAgingPayablesListResults is null)
        {
            return response;
        }

        var allItems = new List<ReadFinancialAgingPayablesList>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadFinancialAgingPayablesListResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadFinancialAgingPayablesListResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new AgingPayablesListRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadFinancialAgingPayablesList_Response
        {
            D = new ReadFinancialAgingPayablesList_Response.ReadFinancialAgingPayablesList_Response_d
            {
                ReadFinancialAgingPayablesList = allItems
            }
        };

        return finalResponse;
    }
}
