// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Inventory.AssemblyBillOfMaterialMaterials;

public partial class AssemblyBillOfMaterialMaterialsRequestBuilder
{
    public async Task<InventoryAssemblyBillOfMaterialMaterials_Response?> GetAllAsync(Action<RequestConfiguration<AssemblyBillOfMaterialMaterialsRequestBuilder.AssemblyBillOfMaterialMaterialsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.InventoryAssemblyBillOfMaterialMaterialsResults is null)
        {
            return response;
        }

        var allItems = new List<InventoryAssemblyBillOfMaterialMaterials>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.InventoryAssemblyBillOfMaterialMaterialsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.InventoryAssemblyBillOfMaterialMaterialsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new AssemblyBillOfMaterialMaterialsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new InventoryAssemblyBillOfMaterialMaterials_Response
        {
            D = new InventoryAssemblyBillOfMaterialMaterials_Response.InventoryAssemblyBillOfMaterialMaterials_Response_d
            {
                InventoryAssemblyBillOfMaterialMaterials = allItems
            }
        };

        return finalResponse;
    }
}
