// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Financialtransaction.BankEntryLines;

public partial class BankEntryLinesRequestBuilder
{
    public async Task<FinancialTransactionBankEntryLines_Response?> GetAllAsync(Action<RequestConfiguration<BankEntryLinesRequestBuilder.BankEntryLinesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.FinancialTransactionBankEntryLinesResults is null)
        {
            return response;
        }

        var allItems = new List<FinancialTransactionBankEntryLines>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.FinancialTransactionBankEntryLinesResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.FinancialTransactionBankEntryLinesResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new BankEntryLinesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new FinancialTransactionBankEntryLines_Response
        {
            D = new FinancialTransactionBankEntryLines_Response.FinancialTransactionBankEntryLines_Response_d
            {
                FinancialTransactionBankEntryLines = allItems
            }
        };

        return finalResponse;
    }
}
