// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Project.CostsById;

public partial class CostsByIdRequestBuilder
{
    public async Task<ReadProjectCostsById_Response?> GetAllAsync(Action<RequestConfiguration<CostsByIdRequestBuilder.CostsByIdRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadProjectCostsByIdResults is null)
        {
            return response;
        }

        var allItems = new List<ReadProjectCostsById>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadProjectCostsByIdResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadProjectCostsByIdResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new CostsByIdRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadProjectCostsById_Response
        {
            D = new ReadProjectCostsById_Response.ReadProjectCostsById_Response_d
            {
                ReadProjectCostsById = allItems
            }
        };

        return finalResponse;
    }
}
