// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Hrm.Costunits;

public partial class CostunitsRequestBuilder
{
    public async Task<HRMCostunits_Response?> GetAllAsync(Action<RequestConfiguration<CostunitsRequestBuilder.CostunitsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.HRMCostunitsResults is null)
        {
            return response;
        }

        var allItems = new List<HRMCostunits>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.HRMCostunitsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.HRMCostunitsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new CostunitsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new HRMCostunits_Response
        {
            D = new HRMCostunits_Response.HRMCostunits_Response_d
            {
                HRMCostunits = allItems
            }
        };

        return finalResponse;
    }
}
