// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Documents.DocumentTypes;

public partial class DocumentTypesRequestBuilder
{
    public async Task<DocumentsDocumentTypes_Response?> GetAllAsync(Action<RequestConfiguration<DocumentTypesRequestBuilder.DocumentTypesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.DocumentsDocumentTypesResults is null)
        {
            return response;
        }

        var allItems = new List<DocumentsDocumentTypes>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.DocumentsDocumentTypesResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.DocumentsDocumentTypesResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new DocumentTypesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new DocumentsDocumentTypes_Response
        {
            D = new DocumentsDocumentTypes_Response.DocumentsDocumentTypes_Response_d
            {
                DocumentsDocumentTypes = allItems
            }
        };

        return finalResponse;
    }
}
