// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Financial.GLAccountClassificationMappings;

public partial class GLAccountClassificationMappingsRequestBuilder
{
    public async Task<FinancialGLAccountClassificationMappings_Response?> GetAllAsync(Action<RequestConfiguration<GLAccountClassificationMappingsRequestBuilder.GLAccountClassificationMappingsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.FinancialGLAccountClassificationMappingsResults is null)
        {
            return response;
        }

        var allItems = new List<FinancialGLAccountClassificationMappings>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.FinancialGLAccountClassificationMappingsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.FinancialGLAccountClassificationMappingsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new GLAccountClassificationMappingsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new FinancialGLAccountClassificationMappings_Response
        {
            D = new FinancialGLAccountClassificationMappings_Response.FinancialGLAccountClassificationMappings_Response_d
            {
                FinancialGLAccountClassificationMappings = allItems
            }
        };

        return finalResponse;
    }
}
