// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Project.HourEntryRecentProjects;

public partial class HourEntryRecentProjectsRequestBuilder
{
    public async Task<ReadProjectHourEntryRecentProjects_Response?> GetAllAsync(Action<RequestConfiguration<HourEntryRecentProjectsRequestBuilder.HourEntryRecentProjectsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadProjectHourEntryRecentProjectsResults is null)
        {
            return response;
        }

        var allItems = new List<ReadProjectHourEntryRecentProjects>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadProjectHourEntryRecentProjectsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadProjectHourEntryRecentProjectsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new HourEntryRecentProjectsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadProjectHourEntryRecentProjects_Response
        {
            D = new ReadProjectHourEntryRecentProjects_Response.ReadProjectHourEntryRecentProjects_Response_d
            {
                ReadProjectHourEntryRecentProjects = allItems
            }
        };

        return finalResponse;
    }
}
