// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Crm.LeadSources;

public partial class LeadSourcesRequestBuilder
{
    public async Task<CRMLeadSources_Response?> GetAllAsync(Action<RequestConfiguration<LeadSourcesRequestBuilder.LeadSourcesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.CRMLeadSourcesResults is null)
        {
            return response;
        }

        var allItems = new List<CRMLeadSources>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.CRMLeadSourcesResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.CRMLeadSourcesResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new LeadSourcesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new CRMLeadSources_Response
        {
            D = new CRMLeadSources_Response.CRMLeadSources_Response_d
            {
                CRMLeadSources = allItems
            }
        };

        return finalResponse;
    }
}
