// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sync.Manufacturing.MaterialIssues;

public partial class MaterialIssuesRequestBuilder
{
    public async Task<SyncManufacturingMaterialIssues_Response?> GetAllAsync(Action<RequestConfiguration<MaterialIssuesRequestBuilder.MaterialIssuesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SyncManufacturingMaterialIssuesResults is null)
        {
            return response;
        }

        var allItems = new List<SyncManufacturingMaterialIssues>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SyncManufacturingMaterialIssuesResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SyncManufacturingMaterialIssuesResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new MaterialIssuesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SyncManufacturingMaterialIssues_Response
        {
            D = new SyncManufacturingMaterialIssues_Response.SyncManufacturingMaterialIssues_Response_d
            {
                SyncManufacturingMaterialIssues = allItems
            }
        };

        return finalResponse;
    }
}
