// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Financial.OfficialReturns;

public partial class OfficialReturnsRequestBuilder
{
    public async Task<FinancialOfficialReturns_Response?> GetAllAsync(Action<RequestConfiguration<OfficialReturnsRequestBuilder.OfficialReturnsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.FinancialOfficialReturnsResults is null)
        {
            return response;
        }

        var allItems = new List<FinancialOfficialReturns>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.FinancialOfficialReturnsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.FinancialOfficialReturnsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new OfficialReturnsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new FinancialOfficialReturns_Response
        {
            D = new FinancialOfficialReturns_Response.FinancialOfficialReturns_Response_d
            {
                FinancialOfficialReturns = allItems
            }
        };

        return finalResponse;
    }
}
