// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Cashflow.Payments;

public partial class PaymentsRequestBuilder
{
    public async Task<CashflowPayments_Response?> GetAllAsync(Action<RequestConfiguration<PaymentsRequestBuilder.PaymentsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.CashflowPaymentsResults is null)
        {
            return response;
        }

        var allItems = new List<CashflowPayments>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.CashflowPaymentsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.CashflowPaymentsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new PaymentsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new CashflowPayments_Response
        {
            D = new CashflowPayments_Response.CashflowPayments_Response_d
            {
                CashflowPayments = allItems
            }
        };

        return finalResponse;
    }
}
