// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Salesorder.PlannedSalesReturnLines;

public partial class PlannedSalesReturnLinesRequestBuilder
{
    public async Task<SalesOrderPlannedSalesReturnLines_Response?> GetAllAsync(Action<RequestConfiguration<PlannedSalesReturnLinesRequestBuilder.PlannedSalesReturnLinesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SalesOrderPlannedSalesReturnLinesResults is null)
        {
            return response;
        }

        var allItems = new List<SalesOrderPlannedSalesReturnLines>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SalesOrderPlannedSalesReturnLinesResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SalesOrderPlannedSalesReturnLinesResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new PlannedSalesReturnLinesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SalesOrderPlannedSalesReturnLines_Response
        {
            D = new SalesOrderPlannedSalesReturnLines_Response.SalesOrderPlannedSalesReturnLines_Response_d
            {
                SalesOrderPlannedSalesReturnLines = allItems
            }
        };

        return finalResponse;
    }
}
