// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Salesinvoice.PrintedSalesInvoices;

public partial class PrintedSalesInvoicesRequestBuilder
{
    public async Task<SalesInvoicePrintedSalesInvoices_Response?> GetAllAsync(Action<RequestConfiguration<PrintedSalesInvoicesRequestBuilder.PrintedSalesInvoicesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SalesInvoicePrintedSalesInvoicesResults is null)
        {
            return response;
        }

        var allItems = new List<SalesInvoicePrintedSalesInvoices>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SalesInvoicePrintedSalesInvoicesResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SalesInvoicePrintedSalesInvoicesResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new PrintedSalesInvoicesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SalesInvoicePrintedSalesInvoices_Response
        {
            D = new SalesInvoicePrintedSalesInvoices_Response.SalesInvoicePrintedSalesInvoices_Response_d
            {
                SalesInvoicePrintedSalesInvoices = allItems
            }
        };

        return finalResponse;
    }
}
