// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Cashflow.ProcessPayments;

public partial class ProcessPaymentsRequestBuilder
{
    public async Task<CashflowProcessPayments_Response?> GetAllAsync(Action<RequestConfiguration<ProcessPaymentsRequestBuilder.ProcessPaymentsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.CashflowProcessPaymentsResults is null)
        {
            return response;
        }

        var allItems = new List<CashflowProcessPayments>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.CashflowProcessPaymentsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.CashflowProcessPaymentsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ProcessPaymentsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new CashflowProcessPayments_Response
        {
            D = new CashflowProcessPayments_Response.CashflowProcessPayments_Response_d
            {
                CashflowProcessPayments = allItems
            }
        };

        return finalResponse;
    }
}
