// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Crm.Quotations;

public partial class QuotationsRequestBuilder
{
    public async Task<CRMQuotations_Response?> GetAllAsync(Action<RequestConfiguration<QuotationsRequestBuilder.QuotationsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.CRMQuotationsResults is null)
        {
            return response;
        }

        var allItems = new List<CRMQuotations>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.CRMQuotationsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.CRMQuotationsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new QuotationsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new CRMQuotations_Response
        {
            D = new CRMQuotations_Response.CRMQuotations_Response_d
            {
                CRMQuotations = allItems
            }
        };

        return finalResponse;
    }
}
