// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Logistics.ReasonCodes;

public partial class ReasonCodesRequestBuilder
{
    public async Task<LogisticsReasonCodes_Response?> GetAllAsync(Action<RequestConfiguration<ReasonCodesRequestBuilder.ReasonCodesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.LogisticsReasonCodesResults is null)
        {
            return response;
        }

        var allItems = new List<LogisticsReasonCodes>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.LogisticsReasonCodesResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.LogisticsReasonCodesResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ReasonCodesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new LogisticsReasonCodes_Response
        {
            D = new LogisticsReasonCodes_Response.LogisticsReasonCodes_Response_d
            {
                LogisticsReasonCodes = allItems
            }
        };

        return finalResponse;
    }
}
