// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sales.SalesChannels;

public partial class SalesChannelsRequestBuilder
{
    public async Task<SalesSalesChannels_Response?> GetAllAsync(Action<RequestConfiguration<SalesChannelsRequestBuilder.SalesChannelsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SalesSalesChannelsResults is null)
        {
            return response;
        }

        var allItems = new List<SalesSalesChannels>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SalesSalesChannelsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SalesSalesChannelsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new SalesChannelsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SalesSalesChannels_Response
        {
            D = new SalesSalesChannels_Response.SalesSalesChannels_Response_d
            {
                SalesSalesChannels = allItems
            }
        };

        return finalResponse;
    }
}
