// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Logistics.SelectionCodes;

public partial class SelectionCodesRequestBuilder
{
    public async Task<LogisticsSelectionCodes_Response?> GetAllAsync(Action<RequestConfiguration<SelectionCodesRequestBuilder.SelectionCodesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.LogisticsSelectionCodesResults is null)
        {
            return response;
        }

        var allItems = new List<LogisticsSelectionCodes>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.LogisticsSelectionCodesResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.LogisticsSelectionCodesResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new SelectionCodesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new LogisticsSelectionCodes_Response
        {
            D = new LogisticsSelectionCodes_Response.LogisticsSelectionCodes_Response_d
            {
                LogisticsSelectionCodes = allItems
            }
        };

        return finalResponse;
    }
}
