// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Inventory.SerialNumbers;

public partial class SerialNumbersRequestBuilder
{
    public async Task<InventorySerialNumbers_Response?> GetAllAsync(Action<RequestConfiguration<SerialNumbersRequestBuilder.SerialNumbersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.InventorySerialNumbersResults is null)
        {
            return response;
        }

        var allItems = new List<InventorySerialNumbers>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.InventorySerialNumbersResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.InventorySerialNumbersResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new SerialNumbersRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new InventorySerialNumbers_Response
        {
            D = new InventorySerialNumbers_Response.InventorySerialNumbers_Response_d
            {
                InventorySerialNumbers = allItems
            }
        };

        return finalResponse;
    }
}
