// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sync.Manufacturing.ShopOrderRoutingStepPlans;

public partial class ShopOrderRoutingStepPlansRequestBuilder
{
    public async Task<SyncManufacturingShopOrderRoutingStepPlans_Response?> GetAllAsync(Action<RequestConfiguration<ShopOrderRoutingStepPlansRequestBuilder.ShopOrderRoutingStepPlansRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SyncManufacturingShopOrderRoutingStepPlansResults is null)
        {
            return response;
        }

        var allItems = new List<SyncManufacturingShopOrderRoutingStepPlans>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SyncManufacturingShopOrderRoutingStepPlansResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SyncManufacturingShopOrderRoutingStepPlansResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ShopOrderRoutingStepPlansRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SyncManufacturingShopOrderRoutingStepPlans_Response
        {
            D = new SyncManufacturingShopOrderRoutingStepPlans_Response.SyncManufacturingShopOrderRoutingStepPlans_Response_d
            {
                SyncManufacturingShopOrderRoutingStepPlans = allItems
            }
        };

        return finalResponse;
    }
}
