// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Manufacturing.ShopOrderPriorities;

public partial class ShopOrderPrioritiesRequestBuilder
{
    public async Task<ManufacturingShopOrderPriorities_Response?> GetAllAsync(Action<RequestConfiguration<ShopOrderPrioritiesRequestBuilder.ShopOrderPrioritiesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ManufacturingShopOrderPrioritiesResults is null)
        {
            return response;
        }

        var allItems = new List<ManufacturingShopOrderPriorities>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ManufacturingShopOrderPrioritiesResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ManufacturingShopOrderPrioritiesResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ShopOrderPrioritiesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ManufacturingShopOrderPriorities_Response
        {
            D = new ManufacturingShopOrderPriorities_Response.ManufacturingShopOrderPriorities_Response_d
            {
                ManufacturingShopOrderPriorities = allItems
            }
        };

        return finalResponse;
    }
}
