// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Manufacturing.StageForDeliveryReversals;

public partial class StageForDeliveryReversalsRequestBuilder
{
    public async Task<ManufacturingStageForDeliveryReversals_Response?> GetAllAsync(Action<RequestConfiguration<StageForDeliveryReversalsRequestBuilder.StageForDeliveryReversalsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ManufacturingStageForDeliveryReversalsResults is null)
        {
            return response;
        }

        var allItems = new List<ManufacturingStageForDeliveryReversals>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ManufacturingStageForDeliveryReversalsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ManufacturingStageForDeliveryReversalsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new StageForDeliveryReversalsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ManufacturingStageForDeliveryReversals_Response
        {
            D = new ManufacturingStageForDeliveryReversals_Response.ManufacturingStageForDeliveryReversals_Response_d
            {
                ManufacturingStageForDeliveryReversals = allItems
            }
        };

        return finalResponse;
    }
}
