// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Subscription.SubscriptionRestrictionItems;

public partial class SubscriptionRestrictionItemsRequestBuilder
{
    public async Task<SubscriptionSubscriptionRestrictionItems_Response?> GetAllAsync(Action<RequestConfiguration<SubscriptionRestrictionItemsRequestBuilder.SubscriptionRestrictionItemsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SubscriptionSubscriptionRestrictionItemsResults is null)
        {
            return response;
        }

        var allItems = new List<SubscriptionSubscriptionRestrictionItems>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SubscriptionSubscriptionRestrictionItemsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SubscriptionSubscriptionRestrictionItemsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new SubscriptionRestrictionItemsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SubscriptionSubscriptionRestrictionItems_Response
        {
            D = new SubscriptionSubscriptionRestrictionItems_Response.SubscriptionSubscriptionRestrictionItems_Response_d
            {
                SubscriptionSubscriptionRestrictionItems = allItems
            }
        };

        return finalResponse;
    }
}
