// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Project.TimeTransactions;

public partial class TimeTransactionsRequestBuilder
{
    public async Task<ProjectTimeTransactions_Response?> GetAllAsync(Action<RequestConfiguration<TimeTransactionsRequestBuilder.TimeTransactionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ProjectTimeTransactionsResults is null)
        {
            return response;
        }

        var allItems = new List<ProjectTimeTransactions>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ProjectTimeTransactionsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ProjectTimeTransactionsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new TimeTransactionsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ProjectTimeTransactions_Response
        {
            D = new ProjectTimeTransactions_Response.ProjectTimeTransactions_Response_d
            {
                ProjectTimeTransactions = allItems
            }
        };

        return finalResponse;
    }
}
