// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Project.TimeAndBillingEntryRecentHourCostTypes;

public partial class TimeAndBillingEntryRecentHourCostTypesRequestBuilder
{
    public async Task<ReadProjectTimeAndBillingEntryRecentHourCostTypes_Response?> GetAllAsync(Action<RequestConfiguration<TimeAndBillingEntryRecentHourCostTypesRequestBuilder.TimeAndBillingEntryRecentHourCostTypesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadProjectTimeAndBillingEntryRecentHourCostTypesResults is null)
        {
            return response;
        }

        var allItems = new List<ReadProjectTimeAndBillingEntryRecentHourCostTypes>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadProjectTimeAndBillingEntryRecentHourCostTypesResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadProjectTimeAndBillingEntryRecentHourCostTypesResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new TimeAndBillingEntryRecentHourCostTypesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadProjectTimeAndBillingEntryRecentHourCostTypes_Response
        {
            D = new ReadProjectTimeAndBillingEntryRecentHourCostTypes_Response.ReadProjectTimeAndBillingEntryRecentHourCostTypes_Response_d
            {
                ReadProjectTimeAndBillingEntryRecentHourCostTypes = allItems
            }
        };

        return finalResponse;
    }
}
