// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Manufacturing.Workcenters;

public partial class WorkcentersRequestBuilder
{
    public async Task<ManufacturingWorkcenters_Response?> GetAllAsync(Action<RequestConfiguration<WorkcentersRequestBuilder.WorkcentersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ManufacturingWorkcentersResults is null)
        {
            return response;
        }

        var allItems = new List<ManufacturingWorkcenters>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ManufacturingWorkcentersResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ManufacturingWorkcentersResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new WorkcentersRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ManufacturingWorkcenters_Response
        {
            D = new ManufacturingWorkcenters_Response.ManufacturingWorkcenters_Response_d
            {
                ManufacturingWorkcenters = allItems
            }
        };

        return finalResponse;
    }
}
