// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sync.Manufacturing.ShopOrderMaterialPlans;

public partial class ShopOrderMaterialPlansRequestBuilder
{
    public async Task<SyncManufacturingShopOrderMaterialPlan_Response?> GetAllAsync(Action<RequestConfiguration<ShopOrderMaterialPlansRequestBuilder.ShopOrderMaterialPlansRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SyncManufacturingShopOrderMaterialPlanResults is null)
        {
            return response;
        }

        var allItems = new List<SyncManufacturingShopOrderMaterialPlan>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SyncManufacturingShopOrderMaterialPlanResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SyncManufacturingShopOrderMaterialPlanResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ShopOrderMaterialPlansRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SyncManufacturingShopOrderMaterialPlan_Response
        {
            D = new SyncManufacturingShopOrderMaterialPlan_Response.SyncManufacturingShopOrderMaterialPlan_Response_d
            {
                SyncManufacturingShopOrderMaterialPlan = allItems
            }
        };

        return finalResponse;
    }
}
