// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sync.Payroll.EmploymentSalaries;

public partial class EmploymentSalariesRequestBuilder
{
    public async Task<SyncPayrollEmploymentSalary_Response?> GetAllAsync(Action<RequestConfiguration<EmploymentSalariesRequestBuilder.EmploymentSalariesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SyncPayrollEmploymentSalaryResults is null)
        {
            return response;
        }

        var allItems = new List<SyncPayrollEmploymentSalary>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SyncPayrollEmploymentSalaryResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SyncPayrollEmploymentSalaryResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new EmploymentSalariesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SyncPayrollEmploymentSalary_Response
        {
            D = new SyncPayrollEmploymentSalary_Response.SyncPayrollEmploymentSalary_Response_d
            {
                SyncPayrollEmploymentSalary = allItems
            }
        };

        return finalResponse;
    }
}
