// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sync.Payroll.EmploymentContracts;

public partial class EmploymentContractsRequestBuilder
{
    public async Task<SyncPayrollEmploymentContract_Response?> GetAllAsync(Action<RequestConfiguration<EmploymentContractsRequestBuilder.EmploymentContractsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SyncPayrollEmploymentContractResults is null)
        {
            return response;
        }

        var allItems = new List<SyncPayrollEmploymentContract>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SyncPayrollEmploymentContractResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SyncPayrollEmploymentContractResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new EmploymentContractsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SyncPayrollEmploymentContract_Response
        {
            D = new SyncPayrollEmploymentContract_Response.SyncPayrollEmploymentContract_Response_d
            {
                SyncPayrollEmploymentContract = allItems
            }
        };

        return finalResponse;
    }
}
