// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sync.Sales.SalesPriceListVolumeDiscounts;

public partial class SalesPriceListVolumeDiscountsRequestBuilder
{
    public async Task<SyncSalesSalesPriceListVolumeDiscounts_Response?> GetAllAsync(Action<RequestConfiguration<SalesPriceListVolumeDiscountsRequestBuilder.SalesPriceListVolumeDiscountsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SyncSalesSalesPriceListVolumeDiscountsResults is null)
        {
            return response;
        }

        var allItems = new List<SyncSalesSalesPriceListVolumeDiscounts>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SyncSalesSalesPriceListVolumeDiscountsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SyncSalesSalesPriceListVolumeDiscountsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new SalesPriceListVolumeDiscountsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SyncSalesSalesPriceListVolumeDiscounts_Response
        {
            D = new SyncSalesSalesPriceListVolumeDiscounts_Response.SyncSalesSalesPriceListVolumeDiscounts_Response_d
            {
                SyncSalesSalesPriceListVolumeDiscounts = allItems
            }
        };

        return finalResponse;
    }
}
