// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Inventory.Warehouses;

public partial class WarehousesRequestBuilder
{
    public async Task<InventoryWarehouse_Response?> GetAllAsync(Action<RequestConfiguration<WarehousesRequestBuilder.WarehousesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.InventoryWarehouseResults is null)
        {
            return response;
        }

        var allItems = new List<InventoryWarehouse>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.InventoryWarehouseResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.InventoryWarehouseResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new WarehousesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new InventoryWarehouse_Response
        {
            D = new InventoryWarehouse_Response.InventoryWarehouse_Response_d
            {
                InventoryWarehouse = allItems
            }
        };

        return finalResponse;
    }
}
