// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Manufacturing.SubOrderReceipts;

public partial class SubOrderReceiptsRequestBuilder
{
    public async Task<ManufacturingSubOrderReceipt_Response?> GetAllAsync(Action<RequestConfiguration<SubOrderReceiptsRequestBuilder.SubOrderReceiptsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ManufacturingSubOrderReceiptResults is null)
        {
            return response;
        }

        var allItems = new List<ManufacturingSubOrderReceipt>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ManufacturingSubOrderReceiptResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ManufacturingSubOrderReceiptResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new SubOrderReceiptsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ManufacturingSubOrderReceipt_Response
        {
            D = new ManufacturingSubOrderReceipt_Response.ManufacturingSubOrderReceipt_Response_d
            {
                ManufacturingSubOrderReceipt = allItems
            }
        };

        return finalResponse;
    }
}
