// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sync.SalesOrder.SalesOrderHeaders;

public partial class SalesOrderHeadersRequestBuilder
{
    public async Task<SyncSalesOrderSalesOrderHeader_Response?> GetAllAsync(Action<RequestConfiguration<SalesOrderHeadersRequestBuilder.SalesOrderHeadersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SyncSalesOrderSalesOrderHeaderResults is null)
        {
            return response;
        }

        var allItems = new List<SyncSalesOrderSalesOrderHeader>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SyncSalesOrderSalesOrderHeaderResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SyncSalesOrderSalesOrderHeaderResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new SalesOrderHeadersRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SyncSalesOrderSalesOrderHeader_Response
        {
            D = new SyncSalesOrderSalesOrderHeader_Response.SyncSalesOrderSalesOrderHeader_Response_d
            {
                SyncSalesOrderSalesOrderHeader = allItems
            }
        };

        return finalResponse;
    }
}
