// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Logistics.CustomerItems;

public partial class CustomerItemsRequestBuilder
{
    public async Task<LogisticsCustomerItem_Response?> GetAllAsync(Action<RequestConfiguration<CustomerItemsRequestBuilder.CustomerItemsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.LogisticsCustomerItemResults is null)
        {
            return response;
        }

        var allItems = new List<LogisticsCustomerItem>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.LogisticsCustomerItemResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.LogisticsCustomerItemResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new CustomerItemsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new LogisticsCustomerItem_Response
        {
            D = new LogisticsCustomerItem_Response.LogisticsCustomerItem_Response_d
            {
                LogisticsCustomerItem = allItems
            }
        };

        return finalResponse;
    }
}
