// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Bulk.SalesInvoice.SalesInvoiceLines;

public partial class SalesInvoiceLinesRequestBuilder
{
    public async Task<BulkSalesInvoiceSalesInvoiceLines_Response?> GetAllAsync(Action<RequestConfiguration<SalesInvoiceLinesRequestBuilder.SalesInvoiceLinesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.BulkSalesInvoiceSalesInvoiceLinesResults is null)
        {
            return response;
        }

        var allItems = new List<BulkSalesInvoiceSalesInvoiceLines>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.BulkSalesInvoiceSalesInvoiceLinesResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.BulkSalesInvoiceSalesInvoiceLinesResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new SalesInvoiceLinesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new BulkSalesInvoiceSalesInvoiceLines_Response
        {
            D = new BulkSalesInvoiceSalesInvoiceLines_Response.BulkSalesInvoiceSalesInvoiceLines_Response_d
            {
                BulkSalesInvoiceSalesInvoiceLines = allItems
            }
        };

        return finalResponse;
    }
}
