// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Subscription.SubscriptionReasonCodes;

public partial class SubscriptionReasonCodesRequestBuilder
{
    public async Task<SubscriptionSubscriptionReasonCode_Response?> GetAllAsync(Action<RequestConfiguration<SubscriptionReasonCodesRequestBuilder.SubscriptionReasonCodesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SubscriptionSubscriptionReasonCodeResults is null)
        {
            return response;
        }

        var allItems = new List<SubscriptionSubscriptionReasonCode>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SubscriptionSubscriptionReasonCodeResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SubscriptionSubscriptionReasonCodeResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new SubscriptionReasonCodesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SubscriptionSubscriptionReasonCode_Response
        {
            D = new SubscriptionSubscriptionReasonCode_Response.SubscriptionSubscriptionReasonCode_Response_d
            {
                SubscriptionSubscriptionReasonCode = allItems
            }
        };

        return finalResponse;
    }
}
