// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Project.ProjectClassifications;

public partial class ProjectClassificationsRequestBuilder
{
    public async Task<ProjectProjectClassification_Response?> GetAllAsync(Action<RequestConfiguration<ProjectClassificationsRequestBuilder.ProjectClassificationsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ProjectProjectClassificationResults is null)
        {
            return response;
        }

        var allItems = new List<ProjectProjectClassification>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ProjectProjectClassificationResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ProjectProjectClassificationResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ProjectClassificationsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ProjectProjectClassification_Response
        {
            D = new ProjectProjectClassification_Response.ProjectProjectClassification_Response_d
            {
                ProjectProjectClassification = allItems
            }
        };

        return finalResponse;
    }
}
