// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Inventory.FinishAssemblyOrder;

public partial class FinishAssemblyOrderRequestBuilder
{
    public async Task<InventoryFinishAssemblyOrder_Response?> GetAllAsync(Action<RequestConfiguration<FinishAssemblyOrderRequestBuilder.FinishAssemblyOrderRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.InventoryFinishAssemblyOrderResults is null)
        {
            return response;
        }

        var allItems = new List<InventoryFinishAssemblyOrder>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.InventoryFinishAssemblyOrderResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.InventoryFinishAssemblyOrderResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new FinishAssemblyOrderRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new InventoryFinishAssemblyOrder_Response
        {
            D = new InventoryFinishAssemblyOrder_Response.InventoryFinishAssemblyOrder_Response_d
            {
                InventoryFinishAssemblyOrder = allItems
            }
        };

        return finalResponse;
    }
}
