// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Bulk.Documents.DocumentAttachments;

public partial class DocumentAttachmentsRequestBuilder
{
    public async Task<BulkDocumentsDocumentAttachments_Response?> GetAllAsync(Action<RequestConfiguration<DocumentAttachmentsRequestBuilder.DocumentAttachmentsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.BulkDocumentsDocumentAttachmentsResults is null)
        {
            return response;
        }

        var allItems = new List<BulkDocumentsDocumentAttachments>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.BulkDocumentsDocumentAttachmentsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.BulkDocumentsDocumentAttachmentsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new DocumentAttachmentsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new BulkDocumentsDocumentAttachments_Response
        {
            D = new BulkDocumentsDocumentAttachments_Response.BulkDocumentsDocumentAttachments_Response_d
            {
                BulkDocumentsDocumentAttachments = allItems
            }
        };

        return finalResponse;
    }
}
