// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sync.Project.ProjectWBS;

public partial class ProjectWBSRequestBuilder
{
    public async Task<SyncProjectProjectWBS_Response?> GetAllAsync(Action<RequestConfiguration<ProjectWBSRequestBuilder.ProjectWBSRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SyncProjectProjectWBSResults is null)
        {
            return response;
        }

        var allItems = new List<SyncProjectProjectWBS>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SyncProjectProjectWBSResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SyncProjectProjectWBSResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ProjectWBSRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SyncProjectProjectWBS_Response
        {
            D = new SyncProjectProjectWBS_Response.SyncProjectProjectWBS_Response_d
            {
                SyncProjectProjectWBS = allItems
            }
        };

        return finalResponse;
    }
}
