// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Bulk.SalesOrder.GoodsDeliveries;

public partial class GoodsDeliveriesRequestBuilder
{
    public async Task<BulkSalesOrderGoodsDeliveries_Response?> GetAllAsync(Action<RequestConfiguration<GoodsDeliveriesRequestBuilder.GoodsDeliveriesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.BulkSalesOrderGoodsDeliveriesResults is null)
        {
            return response;
        }

        var allItems = new List<BulkSalesOrderGoodsDeliveries>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.BulkSalesOrderGoodsDeliveriesResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.BulkSalesOrderGoodsDeliveriesResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new GoodsDeliveriesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new BulkSalesOrderGoodsDeliveries_Response
        {
            D = new BulkSalesOrderGoodsDeliveries_Response.BulkSalesOrderGoodsDeliveries_Response_d
            {
                BulkSalesOrderGoodsDeliveries = allItems
            }
        };

        return finalResponse;
    }
}
