// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Financial.GLAccounts;

public partial class GLAccountsRequestBuilder
{
    public async Task<FinancialGLAccount_Response?> GetAllAsync(Action<RequestConfiguration<GLAccountsRequestBuilder.GLAccountsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.FinancialGLAccountResults is null)
        {
            return response;
        }

        var allItems = new List<FinancialGLAccount>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.FinancialGLAccountResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.FinancialGLAccountResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new GLAccountsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new FinancialGLAccount_Response
        {
            D = new FinancialGLAccount_Response.FinancialGLAccount_Response_d
            {
                FinancialGLAccount = allItems
            }
        };

        return finalResponse;
    }
}
