// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Project.ProjectRestrictionItems;

public partial class ProjectRestrictionItemsRequestBuilder
{
    public async Task<ProjectProjectRestrictionItem_Response?> GetAllAsync(Action<RequestConfiguration<ProjectRestrictionItemsRequestBuilder.ProjectRestrictionItemsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ProjectProjectRestrictionItemResults is null)
        {
            return response;
        }

        var allItems = new List<ProjectProjectRestrictionItem>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ProjectProjectRestrictionItemResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ProjectProjectRestrictionItemResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ProjectRestrictionItemsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ProjectProjectRestrictionItem_Response
        {
            D = new ProjectProjectRestrictionItem_Response.ProjectProjectRestrictionItem_Response_d
            {
                ProjectProjectRestrictionItem = allItems
            }
        };

        return finalResponse;
    }
}
