// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Assets.Assets;

public partial class AssetsRequestBuilder
{
    public async Task<AssetsAssets_Response?> GetAllAsync(Action<RequestConfiguration<AssetsRequestBuilder.AssetsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.AssetsAssetsResults is null)
        {
            return response;
        }

        var allItems = new List<AssetsAssets>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.AssetsAssetsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.AssetsAssetsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new AssetsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new AssetsAssets_Response
        {
            D = new AssetsAssets_Response.AssetsAssets_Response_d
            {
                AssetsAssets = allItems
            }
        };

        return finalResponse;
    }
}
