// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Project.CostTypesByProjectAndDate;

public partial class CostTypesByProjectAndDateRequestBuilder
{
    public async Task<ReadProjectCostTypesByProjectAndDate_Response?> GetAllAsync(Action<RequestConfiguration<CostTypesByProjectAndDateRequestBuilder.CostTypesByProjectAndDateRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadProjectCostTypesByProjectAndDateResults is null)
        {
            return response;
        }

        var allItems = new List<ReadProjectCostTypesByProjectAndDate>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadProjectCostTypesByProjectAndDateResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadProjectCostTypesByProjectAndDateResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new CostTypesByProjectAndDateRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadProjectCostTypesByProjectAndDate_Response
        {
            D = new ReadProjectCostTypesByProjectAndDate_Response.ReadProjectCostTypesByProjectAndDate_Response_d
            {
                ReadProjectCostTypesByProjectAndDate = allItems
            }
        };

        return finalResponse;
    }
}
