// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sync.Financial.TransactionLines;

public partial class TransactionLinesRequestBuilder
{
    public async Task<SyncFinancialTransactionLine_Response?> GetAllAsync(Action<RequestConfiguration<TransactionLinesRequestBuilder.TransactionLinesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SyncFinancialTransactionLineResults is null)
        {
            return response;
        }

        var allItems = new List<SyncFinancialTransactionLine>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SyncFinancialTransactionLineResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SyncFinancialTransactionLineResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new TransactionLinesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SyncFinancialTransactionLine_Response
        {
            D = new SyncFinancialTransactionLine_Response.SyncFinancialTransactionLine_Response_d
            {
                SyncFinancialTransactionLine = allItems
            }
        };

        return finalResponse;
    }
}
