// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class AccountancyInvolvedUsers_ResponseExtensions
{
    public static async Task<List<AccountancyInvolvedUsers>> AsItems(this Task<AccountancyInvolvedUsers_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.AccountancyInvolvedUsers ?? d.AccountancyInvolvedUsersResults?.Results ?? [];
    }

}
