// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class AccountancyAccountInvolvedAccounts_ResponseExtensions
{
    public static List<AccountancyAccountInvolvedAccounts> AsResults(this AccountancyAccountInvolvedAccounts_Response? response) => response?.D?.Results ?? [];
}
