// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class AccountancyInvolvedUsersGet_ResponseExtensions
{
    public static async Task<AccountancyInvolvedUsers?> AsItem(this Task<AccountancyInvolvedUsersGet_Response?> task)
    {
        return (await task)?.D;
    }
}
