// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class AccountancyTaskTypeGet_ResponseExtensions
{
    public static async Task<AccountancyTaskType?> AsItem(this Task<AccountancyTaskTypeGet_Response?> task)
    {
        return (await task)?.D;
    }
}
