// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class AccountancyAccountInvolvedAccount_ResponseExtensions
{
    public static async Task<List<AccountancyAccountInvolvedAccount>> AsItems(this Task<AccountancyAccountInvolvedAccount_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.AccountancyAccountInvolvedAccount ?? d.AccountancyAccountInvolvedAccountResults?.Results ?? [];
    }

}
