// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class AccountancyAccountOwners_ResponseExtensions
{
    public static List<AccountancyAccountOwners> AsResults(this AccountancyAccountOwners_Response? response) => response?.D?.Results ?? [];
}
