// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class AccountancyInvolvedUserRoleGet_ResponseExtensions
{
    public static async Task<AccountancyInvolvedUserRole?> AsItem(this Task<AccountancyInvolvedUserRoleGet_Response?> task)
    {
        return (await task)?.D;
    }
}
