// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class AccountancyAccountInvolvedAccountPost_ResponseExtensions
{
    public static async Task<AccountancyAccountInvolvedAccountPost?> AsItem(this Task<AccountancyAccountInvolvedAccountPost_Response?> task)
    {
        return (await task)?.D;
    }
}
