// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ActivitiesEvents_ResponseExtensions
{
    public static async Task<List<ActivitiesEvents>> AsResults(this Task<ActivitiesEvents_Response?> task) => (await task)?.D?.Results ?? [];
}
