// <auto-generated/>
namespace ExactOnline.Api.Client.Models;

public partial class ActivitiesAnnualStatement
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ActionDate), "ActionDate" },
        { nameof(AnnualStatementStatus), "AnnualStatementStatus" },
        { nameof(AnnualStatementStatusRemark), "AnnualStatementStatusRemark" },
        { nameof(AssignedTo), "AssignedTo" },
        { nameof(AssignedToFullName), "AssignedToFullName" },
        { nameof(Created), "Created" },
        { nameof(Creator), "Creator" },
        { nameof(CreatorFullName), "CreatorFullName" },
        { nameof(Description), "Description" },
        { nameof(Division), "Division" },
        { nameof(HID), "HID" },
        { nameof(ID), "ID" },
        { nameof(Message), "Message" },
        { nameof(Metadata), "__metadata" },
        { nameof(Modified), "Modified" },
        { nameof(Modifier), "Modifier" },
        { nameof(ModifierFullName), "ModifierFullName" },
        { nameof(MyFirmUserEmail), "MyFirmUserEmail" },
        { nameof(Status), "Status" },
        { nameof(StatusDescription), "StatusDescription" },
        { nameof(Type), "Type" },
        { nameof(Url), "Url" }
    };
}
