// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ActivitiesComplaints_Response
{
    public List<ActivitiesComplaints> ToResults() => D?.Results ?? [];
}
