// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ActivitiesCommunicationNote_ResponseExtensions
{
    public static async Task<List<ActivitiesCommunicationNote>> AsItems(this Task<ActivitiesCommunicationNote_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ActivitiesCommunicationNote ?? d.ActivitiesCommunicationNoteResults?.Results ?? [];
    }

}
