// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ActivitiesServiceRequestsGet_ResponseExtensions
{
    public static async Task<ActivitiesServiceRequests?> AsItem(this Task<ActivitiesServiceRequestsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
