// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ActivitiesFiscalPost_ResponseExtensions
{
    public static async Task<ActivitiesFiscalPost?> AsItem(this Task<ActivitiesFiscalPost_Response?> task)
    {
        return (await task)?.D;
    }
}
