// <auto-generated/>
namespace ExactOnline.Api.Client.Models;

public partial class ActivitiesEvent
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Account), "Account" },
        { nameof(AccountName), "AccountName" },
        { nameof(Attachments), "Attachments" },
        { nameof(Campaign), "Campaign" },
        { nameof(CampaignDescription), "CampaignDescription" },
        { nameof(Contact), "Contact" },
        { nameof(ContactFullName), "ContactFullName" },
        { nameof(Created), "Created" },
        { nameof(Creator), "Creator" },
        { nameof(CreatorFullName), "CreatorFullName" },
        { nameof(Description), "Description" },
        { nameof(Division), "Division" },
        { nameof(Document), "Document" },
        { nameof(DocumentSubject), "DocumentSubject" },
        { nameof(EndDate), "EndDate" },
        { nameof(HID), "HID" },
        { nameof(ID), "ID" },
        { nameof(Metadata), "__metadata" },
        { nameof(Modified), "Modified" },
        { nameof(Modifier), "Modifier" },
        { nameof(ModifierFullName), "ModifierFullName" },
        { nameof(Notes), "Notes" },
        { nameof(Opportunity), "Opportunity" },
        { nameof(OpportunityName), "OpportunityName" },
        { nameof(Project), "Project" },
        { nameof(ProjectDescription), "ProjectDescription" },
        { nameof(StartDate), "StartDate" },
        { nameof(Status), "Status" },
        { nameof(StatusDescription), "StatusDescription" },
        { nameof(User), "User" },
        { nameof(UserFullName), "UserFullName" }
    };
}
