// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class AssetsDepreciationMethods_ResponseExtensions
{
    public static List<AssetsDepreciationMethods> AsResults(this AssetsDepreciationMethods_Response? response) => response?.D?.Results ?? [];
}
