// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class AssetsDepreciationMethods_ResponseExtensions
{
    public static async Task<List<AssetsDepreciationMethods>> AsResults(this Task<AssetsDepreciationMethods_Response?> task) => (await task)?.D?.Results ?? [];
}
