// <auto-generated/>
namespace ExactOnline.Api.Client.Models;

public partial class AssetsAssetGroups
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Code), "Code" },
        { nameof(Created), "Created" },
        { nameof(Creator), "Creator" },
        { nameof(CreatorFullName), "CreatorFullName" },
        { nameof(DepreciationMethod), "DepreciationMethod" },
        { nameof(DepreciationMethodCode), "DepreciationMethodCode" },
        { nameof(DepreciationMethodDescription), "DepreciationMethodDescription" },
        { nameof(Description), "Description" },
        { nameof(Division), "Division" },
        { nameof(GLAccountAssets), "GLAccountAssets" },
        { nameof(GLAccountAssetsCode), "GLAccountAssetsCode" },
        { nameof(GLAccountAssetsDescription), "GLAccountAssetsDescription" },
        { nameof(GLAccountDepreciationBS), "GLAccountDepreciationBS" },
        { nameof(GLAccountDepreciationBSCode), "GLAccountDepreciationBSCode" },
        { nameof(GLAccountDepreciationBSDescription), "GLAccountDepreciationBSDescription" },
        { nameof(GLAccountDepreciationPL), "GLAccountDepreciationPL" },
        { nameof(GLAccountDepreciationPLCode), "GLAccountDepreciationPLCode" },
        { nameof(GLAccountDepreciationPLDescription), "GLAccountDepreciationPLDescription" },
        { nameof(GLAccountRevaluationBS), "GLAccountRevaluationBS" },
        { nameof(GLAccountRevaluationBSCode), "GLAccountRevaluationBSCode" },
        { nameof(GLAccountRevaluationBSDescription), "GLAccountRevaluationBSDescription" },
        { nameof(ID), "ID" },
        { nameof(Metadata), "__metadata" },
        { nameof(Modified), "Modified" },
        { nameof(Modifier), "Modifier" },
        { nameof(ModifierFullName), "ModifierFullName" },
        { nameof(Notes), "Notes" }
    };
}
