// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class BudgetBudgetScenarios_Response
{
    public List<BudgetBudgetScenarios> ToResults() => D?.Results ?? [];
}
