// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class BudgetBudgets_ResponseExtensions
{
    public static async Task<List<BudgetBudgets>> AsResults(this Task<BudgetBudgets_Response?> task) => (await task)?.D?.Results ?? [];
}
