// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class BudgetBudget_ResponseExtensions
{
    public static async Task<List<BudgetBudget>> AsItems(this Task<BudgetBudget_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.BudgetBudget ?? d.BudgetBudgetResults?.Results ?? [];
    }

}
