// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class BulkDocumentsDocumentAttachments_ResponseExtensions
{
    public static List<BulkDocumentsDocumentAttachments> AsResults(this BulkDocumentsDocumentAttachments_Response? response) => response?.D?.Results ?? [];
}
