// <auto-generated/>
namespace ExactOnline.Api.Client.Models;

public partial class BulkFinancialGLAccounts
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AllowCostsInSales), "AllowCostsInSales" },
        { nameof(AssimilatedVATBox), "AssimilatedVATBox" },
        { nameof(BalanceSide), "BalanceSide" },
        { nameof(BalanceType), "BalanceType" },
        { nameof(BelcotaxType), "BelcotaxType" },
        { nameof(Code), "Code" },
        { nameof(Compress), "Compress" },
        { nameof(Costcenter), "Costcenter" },
        { nameof(CostcenterDescription), "CostcenterDescription" },
        { nameof(Costunit), "Costunit" },
        { nameof(CostunitDescription), "CostunitDescription" },
        { nameof(Created), "Created" },
        { nameof(Creator), "Creator" },
        { nameof(CreatorFullName), "CreatorFullName" },
        { nameof(CustomField), "CustomField" },
        { nameof(DeductibilityPercentages), "DeductibilityPercentages" },
        { nameof(Description), "Description" },
        { nameof(Division), "Division" },
        { nameof(ExcludeVATListing), "ExcludeVATListing" },
        { nameof(ExpenseNonDeductiblePercentage), "ExpenseNonDeductiblePercentage" },
        { nameof(ID), "ID" },
        { nameof(IsBlocked), "IsBlocked" },
        { nameof(Matching), "Matching" },
        { nameof(Metadata), "__metadata" },
        { nameof(Modified), "Modified" },
        { nameof(Modifier), "Modifier" },
        { nameof(ModifierFullName), "ModifierFullName" },
        { nameof(PrivateGLAccount), "PrivateGLAccount" },
        { nameof(PrivatePercentage), "PrivatePercentage" },
        { nameof(ReportingCode), "ReportingCode" },
        { nameof(RevalueCurrency), "RevalueCurrency" },
        { nameof(SearchCode), "SearchCode" },
        { nameof(Type), "Type" },
        { nameof(TypeDescription), "TypeDescription" },
        { nameof(UseCostcenter), "UseCostcenter" },
        { nameof(UseCostunit), "UseCostunit" },
        { nameof(VATCode), "VATCode" },
        { nameof(VATDescription), "VATDescription" },
        { nameof(VATGLAccountType), "VATGLAccountType" },
        { nameof(VATNonDeductibleGLAccount), "VATNonDeductibleGLAccount" },
        { nameof(VATNonDeductiblePercentage), "VATNonDeductiblePercentage" },
        { nameof(VATSystem), "VATSystem" },
        { nameof(YearEndCostGLAccount), "YearEndCostGLAccount" },
        { nameof(YearEndReflectionGLAccount), "YearEndReflectionGLAccount" }
    };
}
