// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class BulkSalesInvoiceSalesInvoiceLinesGet_ResponseExtensions
{
    public static async Task<BulkSalesInvoiceSalesInvoiceLines?> AsItem(this Task<BulkSalesInvoiceSalesInvoiceLinesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
