// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class BulkFinancialGLAccountsGet_ResponseExtensions
{
    public static async Task<BulkFinancialGLAccounts?> AsItem(this Task<BulkFinancialGLAccountsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
