// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class BulkSalesOrderSalesOrderLines_ResponseExtensions
{
    public static async Task<List<BulkSalesOrderSalesOrderLines>> AsItems(this Task<BulkSalesOrderSalesOrderLines_Response?> task) => (await task)?.D?.Results ?? [];
}
