// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class BulkDocumentsDocumentAttachmentGet_ResponseExtensions
{
    public static async Task<BulkDocumentsDocumentAttachment?> AsItem(this Task<BulkDocumentsDocumentAttachmentGet_Response?> task)
    {
        return (await task)?.D;
    }
}
