// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class BulkCashflowPayments_ResponseExtensions
{
    public static async Task<List<BulkCashflowPayments>> AsItems(this Task<BulkCashflowPayments_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.BulkCashflowPayments ?? d.BulkCashflowPaymentsResults?.Results ?? [];
    }

}
