// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class BulkCRMAddresses_ResponseExtensions
{
    public static List<BulkCRMAddresses> AsResults(this BulkCRMAddresses_Response? response) => response?.D?.Results ?? [];
}
