// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class BulkSalesInvoiceSalesInvoicesGet_ResponseExtensions
{
    public static async Task<BulkSalesInvoiceSalesInvoices?> AsItem(this Task<BulkSalesInvoiceSalesInvoicesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
