// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class BulkSalesOrderGoodsDeliveryLine_ResponseExtensions
{
    public static async Task<List<BulkSalesOrderGoodsDeliveryLine>> AsItems(this Task<BulkSalesOrderGoodsDeliveryLine_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.BulkSalesOrderGoodsDeliveryLine ?? d.BulkSalesOrderGoodsDeliveryLineResults?.Results ?? [];
    }

}
