// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class BulkDocumentsDocuments_ResponseExtensions
{
    public static List<BulkDocumentsDocuments> AsResults(this BulkDocumentsDocuments_Response? response) => response?.D?.Results ?? [];
}
