// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class BulkLogisticsSalesItemPrice_ResponseExtensions
{
    public static async Task<List<BulkLogisticsSalesItemPrice>> AsItems(this Task<BulkLogisticsSalesItemPrice_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.BulkLogisticsSalesItemPrice ?? d.BulkLogisticsSalesItemPriceResults?.Results ?? [];
    }

}
