// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class BulkDocumentsDocumentAttachments_Response
{
    public List<BulkDocumentsDocumentAttachments> ToResults() => D?.Results ?? [];
}
