// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class BulkCRMAccountsGet_ResponseExtensions
{
    public static async Task<BulkCRMAccounts?> AsItem(this Task<BulkCRMAccountsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
