// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class BulkProjectProjectWBS_ResponseExtensions
{
    public static async Task<BulkProjectProjectWBS?> AsItem(this Task<BulkProjectProjectWBS_Response?> task) => (await task)?.D?.Results?.FirstOrDefault();
}
