// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class BulkCRMQuotations_Response
{
    public List<BulkCRMQuotations> ToResults() => D?.Results ?? [];
}
