// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class BulkCashflowReceivables_ResponseExtensions
{
    public static List<BulkCashflowReceivables> AsResults(this BulkCashflowReceivables_Response? response) => response?.D?.Results ?? [];
}
