// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class BulkProjectProjectWBS_Response
{
    public BulkProjectProjectWBS? ToItem() => D?.Results?.FirstOrDefault();
}
