// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class BulkCashflowReceivableGet_ResponseExtensions
{
    public static async Task<BulkCashflowReceivable?> AsItem(this Task<BulkCashflowReceivableGet_Response?> task)
    {
        return (await task)?.D;
    }
}
