// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class BulkCRMAccounts_ResponseExtensions
{
    public static async Task<List<BulkCRMAccounts>> AsResults(this Task<BulkCRMAccounts_Response?> task) => (await task)?.D?.Results ?? [];
}
