// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class BulkCRMQuotationLine_ResponseExtensions
{
    public static async Task<List<BulkCRMQuotationLine>> AsItems(this Task<BulkCRMQuotationLine_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.BulkCRMQuotationLine ?? d.BulkCRMQuotationLineResults?.Results ?? [];
    }

}
