// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class BulkFinancialGLClassificationGet_ResponseExtensions
{
    public static async Task<BulkFinancialGLClassification?> AsItem(this Task<BulkFinancialGLClassificationGet_Response?> task)
    {
        return (await task)?.D;
    }
}
