// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class BulkFinancialGLAccounts_Response
{
    public List<BulkFinancialGLAccounts> ToResults() => D?.Results ?? [];
}
