// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CashflowDirectDebitMandateGet_ResponseExtensions
{
    public static async Task<CashflowDirectDebitMandate?> AsItem(this Task<CashflowDirectDebitMandateGet_Response?> task)
    {
        return (await task)?.D;
    }
}
