// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CashflowPaymentConditionsGet_ResponseExtensions
{
    public static async Task<CashflowPaymentConditions?> AsItem(this Task<CashflowPaymentConditionsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
