// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CashflowAllocationRuleGet_ResponseExtensions
{
    public static async Task<CashflowAllocationRule?> AsItem(this Task<CashflowAllocationRuleGet_Response?> task)
    {
        return (await task)?.D;
    }
}
