// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CashflowReceivables_ResponseExtensions
{
    public static List<CashflowReceivables> AsResults(this CashflowReceivables_Response? response) => response?.D?.Results ?? [];
}
