// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CashflowProcessPaymentsPost_ResponseExtensions
{
    public static async Task<CashflowProcessPaymentsPost?> AsItem(this Task<CashflowProcessPaymentsPost_Response?> task)
    {
        return (await task)?.D;
    }
}
