// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class CashflowReceivables_Response
{
    public List<CashflowReceivables> ToResults() => D?.Results ?? [];
}
