// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CRMAddressStates_ResponseExtensions
{
    public static async Task<List<CRMAddressStates>> AsItems(this Task<CRMAddressStates_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.CRMAddressStates ?? d.CRMAddressStatesResults?.Results ?? [];
    }

}
