// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CRMAcceptQuotation_ResponseExtensions
{
    public static async Task<List<CRMAcceptQuotation>> AsItems(this Task<CRMAcceptQuotation_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.CRMAcceptQuotation ?? d.CRMAcceptQuotationResults?.Results ?? [];
    }

}
