// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CRMAddressState_ResponseExtensions
{
    public static async Task<List<CRMAddressState>> AsItems(this Task<CRMAddressState_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.CRMAddressState ?? d.CRMAddressStateResults?.Results ?? [];
    }

}
