// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CRMAccountClassificationNames_ResponseExtensions
{
    public static async Task<List<CRMAccountClassificationNames>> AsItems(this Task<CRMAccountClassificationNames_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.CRMAccountClassificationNames ?? d.CRMAccountClassificationNamesResults?.Results ?? [];
    }

}
