// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CRMAccountPost_ResponseExtensions
{
    public static async Task<CRMAccountPost?> AsItem(this Task<CRMAccountPost_Response?> task)
    {
        return (await task)?.D;
    }
}
