// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CRMAccountGet_ResponseExtensions
{
    public static async Task<CRMAccount?> AsItem(this Task<CRMAccountGet_Response?> task)
    {
        return (await task)?.D;
    }
}
