// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CRMAccountClassificationNameGet_ResponseExtensions
{
    public static async Task<CRMAccountClassificationName?> AsItem(this Task<CRMAccountClassificationNameGet_Response?> task)
    {
        return (await task)?.D;
    }
}
