// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CRMAccounts_ResponseExtensions
{
    public static async Task<List<CRMAccounts>> AsItems(this Task<CRMAccounts_Response?> task) => (await task)?.D?.Results ?? [];
}
