// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CRMAddresses_ResponseExtensions
{
    public static List<CRMAddresses> AsResults(this CRMAddresses_Response? response) => response?.D?.Results ?? [];
}
