// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CRMBankAccounts_ResponseExtensions
{
    public static List<CRMBankAccounts> AsResults(this CRMBankAccounts_Response? response) => response?.D?.Results ?? [];
}
