// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CRMContactPost_ResponseExtensions
{
    public static async Task<CRMContactPost?> AsItem(this Task<CRMContactPost_Response?> task)
    {
        return (await task)?.D;
    }
}
