// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CRMOpportunitiesGet_ResponseExtensions
{
    public static async Task<CRMOpportunities?> AsItem(this Task<CRMOpportunitiesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
