// <auto-generated/>
namespace ExactOnline.Api.Client.Models;

public partial class CRMOptionalQuotationLineID
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ID), "ID" },
        { nameof(Metadata), "__metadata" }
    };
}
