// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CRMQuotationLineGet_ResponseExtensions
{
    public static async Task<CRMQuotationLine?> AsItem(this Task<CRMQuotationLineGet_Response?> task)
    {
        return (await task)?.D;
    }
}
