// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CRMQuotationOrderChargeLines_ResponseExtensions
{
    public static async Task<List<CRMQuotationOrderChargeLines>> AsResults(this Task<CRMQuotationOrderChargeLines_Response?> task) => (await task)?.D?.Results ?? [];
}
