// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CRMQuotationLinesGet_ResponseExtensions
{
    public static async Task<CRMQuotationLines?> AsItem(this Task<CRMQuotationLinesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
