// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CRMReviewQuotationPost_ResponseExtensions
{
    public static async Task<CRMReviewQuotationPost?> AsItem(this Task<CRMReviewQuotationPost_Response?> task)
    {
        return (await task)?.D;
    }
}
