// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CRMReasonCodes_ResponseExtensions
{
    public static List<CRMReasonCodes> AsResults(this CRMReasonCodes_Response? response) => response?.D?.Results ?? [];
}
