// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CustomFieldCustomFields_ResponseExtensions
{
    public static async Task<List<CustomFieldCustomFields>> AsItems(this Task<CustomFieldCustomFields_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.CustomFieldCustomFields ?? d.CustomFieldCustomFieldsResults?.Results ?? [];
    }

}
