// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class CustomFieldCustomFieldGet_ResponseExtensions
{
    public static async Task<CustomFieldCustomField?> AsItem(this Task<CustomFieldCustomFieldGet_Response?> task)
    {
        return (await task)?.D;
    }
}
