// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class CustomFieldCustomFields_Response
{
    public List<CustomFieldCustomFields> ToResults() => D?.Results ?? [];
}
