// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class CustomFieldUpdateCustomField_Response
{
    public CustomFieldUpdateCustomField? ToItem() => D?.Results?.FirstOrDefault();

    public List<CustomFieldUpdateCustomField> ToResults() => D?.Results ?? [];
}
