// <auto-generated/>
namespace ExactOnline.Api.Client.Models;

public partial class DocumentsDocumentTypeCategory
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Created), "Created" },
        { nameof(Description), "Description" },
        { nameof(ID), "ID" },
        { nameof(Metadata), "__metadata" },
        { nameof(Modified), "Modified" }
    };
}
