// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class DocumentsDocumentType_ResponseExtensions
{
    public static async Task<List<DocumentsDocumentType>> AsItems(this Task<DocumentsDocumentType_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.DocumentsDocumentType ?? d.DocumentsDocumentTypeResults?.Results ?? [];
    }

}
