// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class DocumentsGetSharePointDocumentUrl_ResponseExtensions
{
    public static async Task<List<DocumentsGetSharePointDocumentUrl>> AsItems(this Task<DocumentsGetSharePointDocumentUrl_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.DocumentsGetSharePointDocumentUrl ?? d.DocumentsGetSharePointDocumentUrlResults?.Results ?? [];
    }

}
