// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class DocumentsDocumentFolderGet_ResponseExtensions
{
    public static async Task<DocumentsDocumentFolder?> AsItem(this Task<DocumentsDocumentFolderGet_Response?> task)
    {
        return (await task)?.D;
    }
}
