// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class DocumentsDocument_ResponseExtensions
{
    public static async Task<List<DocumentsDocument>> AsItems(this Task<DocumentsDocument_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.DocumentsDocument ?? d.DocumentsDocumentResults?.Results ?? [];
    }

}
