// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class DocumentsDocumentCategories_Response
{
    public List<DocumentsDocumentCategories> ToResults() => D?.Results ?? [];
}
