// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class DocumentsDocumentTypeFolderPost_ResponseExtensions
{
    public static async Task<DocumentsDocumentTypeFolderPost?> AsItem(this Task<DocumentsDocumentTypeFolderPost_Response?> task)
    {
        return (await task)?.D;
    }
}
