// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class DocumentsDocumentTypeCategories_ResponseExtensions
{
    public static List<DocumentsDocumentTypeCategories> AsResults(this DocumentsDocumentTypeCategories_Response? response) => response?.D?.Results ?? [];
}
