// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class DocumentsDocumentCategories_ResponseExtensions
{
    public static List<DocumentsDocumentCategories> AsResults(this DocumentsDocumentCategories_Response? response) => response?.D?.Results ?? [];
}
