// <auto-generated/>
namespace ExactOnline.Api.Client.Models;

public partial class ExpenseManagementExpense
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(ApproverComment), "ApproverComment" },
        { nameof(Claimant), "Claimant" },
        { nameof(ClaimantFullName), "ClaimantFullName" },
        { nameof(Country), "Country" },
        { nameof(Currency), "Currency" },
        { nameof(Description), "Description" },
        { nameof(Distance), "Distance" },
        { nameof(DistanceUnit), "DistanceUnit" },
        { nameof(DistanceUnitDescription), "DistanceUnitDescription" },
        { nameof(Division), "Division" },
        { nameof(DocumentId), "DocumentId" },
        { nameof(ExpenseDate), "ExpenseDate" },
        { nameof(ExpenseLines), "ExpenseLines" },
        { nameof(ExpenseNumber), "ExpenseNumber" },
        { nameof(ExpenseType), "ExpenseType" },
        { nameof(ExpenseTypeDescription), "ExpenseTypeDescription" },
        { nameof(ID), "ID" },
        { nameof(Metadata), "__metadata" },
        { nameof(MileageRate), "MileageRate" },
        { nameof(MileageRateDescription), "MileageRateDescription" },
        { nameof(PaymentMethod), "PaymentMethod" },
        { nameof(PerDiemRate), "PerDiemRate" },
        { nameof(PerDiemRateDescription), "PerDiemRateDescription" },
        { nameof(Project), "Project" },
        { nameof(ProjectDescription), "ProjectDescription" },
        { nameof(RateFC), "RateFC" },
        { nameof(Report), "Report" },
        { nameof(ReportDescription), "ReportDescription" },
        { nameof(Status), "Status" },
        { nameof(StatusDescription), "StatusDescription" },
        { nameof(SysCreated), "SysCreated" },
        { nameof(SysCreator), "SysCreator" },
        { nameof(SysCreatorFullName), "SysCreatorFullName" },
        { nameof(SysModified), "SysModified" },
        { nameof(SysModifier), "SysModifier" },
        { nameof(SysModifierFullName), "SysModifierFullName" },
        { nameof(TotalAmountDC), "TotalAmountDC" },
        { nameof(TotalAmountFC), "TotalAmountFC" },
        { nameof(Waypoints), "Waypoints" }
    };
}
