// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ExpenseManagementExpenseReportGet_ResponseExtensions
{
    public static async Task<ExpenseManagementExpenseReport?> AsItem(this Task<ExpenseManagementExpenseReportGet_Response?> task)
    {
        return (await task)?.D;
    }
}
