// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialProcessReturn_ResponseExtensions
{
    public static async Task<FinancialProcessReturn?> AsItem(this Task<FinancialProcessReturn_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? null : (d.FinancialProcessReturn ?? d.FinancialProcessReturnResults?.Results ?? []).FirstOrDefault();
    }

}
