// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialJournalsGet_ResponseExtensions
{
    public static async Task<FinancialJournals?> AsItem(this Task<FinancialJournalsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
