// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialGLClassification_ResponseExtensions
{
    public static async Task<List<FinancialGLClassification>> AsItems(this Task<FinancialGLClassification_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.FinancialGLClassification ?? d.FinancialGLClassificationResults?.Results ?? [];
    }

}
