// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialReportingBalance_ResponseExtensions
{
    public static FinancialReportingBalance? AsItem(this FinancialReportingBalance_Response? response) => response?.D?.Results?.FirstOrDefault();
}
