// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialTransactionCashEntryLinesGet_ResponseExtensions
{
    public static async Task<FinancialTransactionCashEntryLines?> AsItem(this Task<FinancialTransactionCashEntryLinesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
