// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialJournalPost_ResponseExtensions
{
    public static async Task<FinancialJournalPost?> AsItem(this Task<FinancialJournalPost_Response?> task)
    {
        return (await task)?.D;
    }
}
