// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialTransactionBankEntriesPost_ResponseExtensions
{
    public static async Task<FinancialTransactionBankEntries?> AsItem(this Task<FinancialTransactionBankEntriesPost_Response?> task)
    {
        return (await task)?.D;
    }
}
