// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialGLAccountClassificationMappingPost_ResponseExtensions
{
    public static async Task<FinancialGLAccountClassificationMappingPost?> AsItem(this Task<FinancialGLAccountClassificationMappingPost_Response?> task)
    {
        return (await task)?.D;
    }
}
