// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialExchangeRate_ResponseExtensions
{
    public static async Task<List<FinancialExchangeRate>> AsItems(this Task<FinancialExchangeRate_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.FinancialExchangeRate ?? d.FinancialExchangeRateResults?.Results ?? [];
    }

}
