// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialTransactionTransactionLinesGet_ResponseExtensions
{
    public static async Task<FinancialTransactionTransactionLines?> AsItem(this Task<FinancialTransactionTransactionLinesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
