// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialTransactionBankEntryLinePost_ResponseExtensions
{
    public static async Task<FinancialTransactionBankEntryLinePost?> AsItem(this Task<FinancialTransactionBankEntryLinePost_Response?> task)
    {
        return (await task)?.D;
    }
}
