// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class FinancialOfficialReturns_Response
{
    public List<FinancialOfficialReturns> ToResults() => D?.Results ?? [];
}
