// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialGLClassifications_ResponseExtensions
{
    public static async Task<List<FinancialGLClassifications>> AsResults(this Task<FinancialGLClassifications_Response?> task) => (await task)?.D?.Results ?? [];
}
