// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialFinancialPeriods_ResponseExtensions
{
    public static async Task<List<FinancialFinancialPeriods>> AsItems(this Task<FinancialFinancialPeriods_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.FinancialFinancialPeriods ?? d.FinancialFinancialPeriodsResults?.Results ?? [];
    }

}
