// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialExchangeRates_ResponseExtensions
{
    public static async Task<List<FinancialExchangeRates>> AsItems(this Task<FinancialExchangeRates_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.FinancialExchangeRates ?? d.FinancialExchangeRatesResults?.Results ?? [];
    }

}
