// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialGLTransactionSources_ResponseExtensions
{
    public static async Task<List<FinancialGLTransactionSources>> AsItems(this Task<FinancialGLTransactionSources_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.FinancialGLTransactionSources ?? d.FinancialGLTransactionSourcesResults?.Results ?? [];
    }

}
