// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialGLClassifications_ResponseExtensions
{
    public static async Task<List<FinancialGLClassifications>> AsItems(this Task<FinancialGLClassifications_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.FinancialGLClassifications ?? d.FinancialGLClassificationsResults?.Results ?? [];
    }

}
