// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialGLClassifications_ResponseExtensions
{
    public static List<FinancialGLClassifications> AsResults(this FinancialGLClassifications_Response? response) => response?.D?.Results ?? [];
}
