// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialReportingBalance_ResponseExtensions
{
    public static async Task<FinancialReportingBalance?> AsItem(this Task<FinancialReportingBalance_Response?> task) => (await task)?.D?.Results?.FirstOrDefault();
}
