// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialGLAccountClassificationMappingsPost_ResponseExtensions
{
    public static async Task<FinancialGLAccountClassificationMappingsPost?> AsItem(this Task<FinancialGLAccountClassificationMappingsPost_Response?> task)
    {
        return (await task)?.D;
    }
}
