// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialGLAccountsPost_ResponseExtensions
{
    public static async Task<FinancialGLAccounts?> AsItem(this Task<FinancialGLAccountsPost_Response?> task)
    {
        return (await task)?.D;
    }
}
