// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class FinancialTransactionCashEntryGet_ResponseExtensions
{
    public static async Task<FinancialTransactionCashEntry?> AsItem(this Task<FinancialTransactionCashEntryGet_Response?> task)
    {
        return (await task)?.D;
    }
}
