// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class GeneralJournalEntryGeneralJournalEntries_Response
{
    public List<GeneralJournalEntryGeneralJournalEntries> ToResults() => D?.Results ?? [];
}
