// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class GeneralJournalEntryGeneralJournalEntryLines_ResponseExtensions
{
    public static async Task<List<GeneralJournalEntryGeneralJournalEntryLines>> AsItems(this Task<GeneralJournalEntryGeneralJournalEntryLines_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.GeneralJournalEntryGeneralJournalEntryLines ?? d.GeneralJournalEntryGeneralJournalEntryLinesResults?.Results ?? [];
    }

}
