// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class GeneralLayout_ResponseExtensions
{
    public static async Task<List<GeneralLayout>> AsItems(this Task<GeneralLayout_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.GeneralLayout ?? d.GeneralLayoutResults?.Results ?? [];
    }

}
