// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class GeneralJournalEntryGeneralJournalEntryLinesGet_ResponseExtensions
{
    public static async Task<GeneralJournalEntryGeneralJournalEntryLines?> AsItem(this Task<GeneralJournalEntryGeneralJournalEntryLinesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
