// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class GeneralJournalEntryGeneralJournalEntryGet_ResponseExtensions
{
    public static async Task<GeneralJournalEntryGeneralJournalEntry?> AsItem(this Task<GeneralJournalEntryGeneralJournalEntryGet_Response?> task)
    {
        return (await task)?.D;
    }
}
