// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class GeneralCurrencies_ResponseExtensions
{
    public static async Task<List<GeneralCurrencies>> AsItems(this Task<GeneralCurrencies_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.GeneralCurrencies ?? d.GeneralCurrenciesResults?.Results ?? [];
    }

}
