// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class HRMAbsenceRegistrationTransactionsGet_ResponseExtensions
{
    public static async Task<HRMAbsenceRegistrationTransactions?> AsItem(this Task<HRMAbsenceRegistrationTransactionsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
