// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class HRMCostunits_ResponseExtensions
{
    public static async Task<List<HRMCostunits>> AsItems(this Task<HRMCostunits_Response?> task) => (await task)?.D?.Results ?? [];
}
