// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class HRMCostcenters_ResponseExtensions
{
    public static async Task<List<HRMCostcenters>> AsResults(this Task<HRMCostcenters_Response?> task) => (await task)?.D?.Results ?? [];
}
