// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class HRMCostunitPost_ResponseExtensions
{
    public static async Task<HRMCostunitPost?> AsItem(this Task<HRMCostunitPost_Response?> task)
    {
        return (await task)?.D;
    }
}
