// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class HRMCostcentersGet_ResponseExtensions
{
    public static async Task<HRMCostcenters?> AsItem(this Task<HRMCostcentersGet_Response?> task)
    {
        return (await task)?.D;
    }
}
