// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class HRMCostunitsGet_ResponseExtensions
{
    public static async Task<HRMCostunits?> AsItem(this Task<HRMCostunitsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
