// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class HRMDivisionClassGet_ResponseExtensions
{
    public static async Task<HRMDivisionClass?> AsItem(this Task<HRMDivisionClassGet_Response?> task)
    {
        return (await task)?.D;
    }
}
