// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class HRMDepartmentsGet_ResponseExtensions
{
    public static async Task<HRMDepartments?> AsItem(this Task<HRMDepartmentsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
