// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class HRMDivisionClassesGet_ResponseExtensions
{
    public static async Task<HRMDivisionClasses?> AsItem(this Task<HRMDivisionClassesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
