// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class HRMDivisionClassNamesGet_ResponseExtensions
{
    public static async Task<HRMDivisionClassNames?> AsItem(this Task<HRMDivisionClassNamesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
