// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class HRMJobTitles_ResponseExtensions
{
    public static List<HRMJobTitles> AsResults(this HRMJobTitles_Response? response) => response?.D?.Results ?? [];
}
