// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class HRMJobGroups_ResponseExtensions
{
    public static async Task<List<HRMJobGroups>> AsItems(this Task<HRMJobGroups_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.HRMJobGroups ?? d.HRMJobGroupsResults?.Results ?? [];
    }

}
