// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class HRMLeaveRegistrations_ResponseExtensions
{
    public static async Task<List<HRMLeaveRegistrations>> AsItems(this Task<HRMLeaveRegistrations_Response?> task) => (await task)?.D?.Results ?? [];
}
