// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class HRMLeaveRegistrationGet_ResponseExtensions
{
    public static async Task<HRMLeaveRegistration?> AsItem(this Task<HRMLeaveRegistrationGet_Response?> task)
    {
        return (await task)?.D;
    }
}
