// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class HRMSchedules_ResponseExtensions
{
    public static async Task<List<HRMSchedules>> AsResults(this Task<HRMSchedules_Response?> task) => (await task)?.D?.Results ?? [];
}
