// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryStockCounts_ResponseExtensions
{
    public static async Task<List<InventoryStockCounts>> AsItems(this Task<InventoryStockCounts_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.InventoryStockCounts ?? d.InventoryStockCountsResults?.Results ?? [];
    }

}
