// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryItemWarehousePlanningDetails_ResponseExtensions
{
    public static async Task<List<InventoryItemWarehousePlanningDetails>> AsResults(this Task<InventoryItemWarehousePlanningDetails_Response?> task) => (await task)?.D?.Results ?? [];
}
