// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryItemWarehouse_ResponseExtensions
{
    public static async Task<List<InventoryItemWarehouse>> AsItems(this Task<InventoryItemWarehouse_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.InventoryItemWarehouse ?? d.InventoryItemWarehouseResults?.Results ?? [];
    }

}
