// <auto-generated/>
namespace ExactOnline.Api.Client.Models;

public partial class InventoryBatchNumbers
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AvailableQuantity), "AvailableQuantity" },
        { nameof(BatchNumber), "BatchNumber" },
        { nameof(Created), "Created" },
        { nameof(Creator), "Creator" },
        { nameof(CreatorFullName), "CreatorFullName" },
        { nameof(CustomField), "CustomField" },
        { nameof(Division), "Division" },
        { nameof(ExpiryDate), "ExpiryDate" },
        { nameof(ID), "ID" },
        { nameof(IsBlocked), "IsBlocked" },
        { nameof(Item), "Item" },
        { nameof(ItemCode), "ItemCode" },
        { nameof(ItemDescription), "ItemDescription" },
        { nameof(Metadata), "__metadata" },
        { nameof(Modified), "Modified" },
        { nameof(Modifier), "Modifier" },
        { nameof(ModifierFullName), "ModifierFullName" },
        { nameof(Remarks), "Remarks" },
        { nameof(StorageLocations), "StorageLocations" },
        { nameof(Warehouses), "Warehouses" }
    };
}
