// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryStockCountLinesPost_ResponseExtensions
{
    public static async Task<InventoryStockCountLinesPost?> AsItem(this Task<InventoryStockCountLinesPost_Response?> task)
    {
        return (await task)?.D;
    }
}
