// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryWarehouseTransfersPost_ResponseExtensions
{
    public static async Task<InventoryWarehouseTransfersPost?> AsItem(this Task<InventoryWarehouseTransfersPost_Response?> task)
    {
        return (await task)?.D;
    }
}
