// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryStockBatchNumbersPost_ResponseExtensions
{
    public static async Task<InventoryStockBatchNumbers?> AsItem(this Task<InventoryStockBatchNumbersPost_Response?> task)
    {
        return (await task)?.D;
    }
}
