// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryStockCount_ResponseExtensions
{
    public static async Task<List<InventoryStockCount>> AsItems(this Task<InventoryStockCount_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.InventoryStockCount ?? d.InventoryStockCountResults?.Results ?? [];
    }

}
