// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryFinishAssemblyOrderGet_ResponseExtensions
{
    public static async Task<InventoryFinishAssemblyOrder?> AsItem(this Task<InventoryFinishAssemblyOrderGet_Response?> task)
    {
        return (await task)?.D;
    }
}
