// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryStockBatchNumberPost_ResponseExtensions
{
    public static async Task<InventoryStockBatchNumberPost?> AsItem(this Task<InventoryStockBatchNumberPost_Response?> task)
    {
        return (await task)?.D;
    }
}
