// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class InventoryBatchNumbers_Warehouses_Response
{
    public InventoryBatchNumbers_Warehouses? ToItem() => D?.Results?.FirstOrDefault();

    public List<InventoryBatchNumbers_Warehouses> ToResults() => D?.Results ?? [];
}
