// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryStockCounts_ResponseExtensions
{
    public static async Task<List<InventoryStockCounts>> AsResults(this Task<InventoryStockCounts_Response?> task) => (await task)?.D?.Results ?? [];
}
