// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryStockCountPost_ResponseExtensions
{
    public static async Task<InventoryStockCountPost?> AsItem(this Task<InventoryStockCountPost_Response?> task)
    {
        return (await task)?.D;
    }
}
