// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryWarehouseTransferLine_ResponseExtensions
{
    public static async Task<List<InventoryWarehouseTransferLine>> AsItems(this Task<InventoryWarehouseTransferLine_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.InventoryWarehouseTransferLine ?? d.InventoryWarehouseTransferLineResults?.Results ?? [];
    }

}
