// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryAssemblyBillOfMaterialHeader_ResponseExtensions
{
    public static InventoryAssemblyBillOfMaterialHeader? AsItem(this InventoryAssemblyBillOfMaterialHeader_Response? response) => response?.D?.Results?.FirstOrDefault();
}
