// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryStorageLocation_ResponseExtensions
{
    public static async Task<List<InventoryStorageLocation>> AsItems(this Task<InventoryStorageLocation_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.InventoryStorageLocation ?? d.InventoryStorageLocationResults?.Results ?? [];
    }

}
