// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryWarehouseTransferLinesPost_ResponseExtensions
{
    public static async Task<InventoryWarehouseTransferLinesPost?> AsItem(this Task<InventoryWarehouseTransferLinesPost_Response?> task)
    {
        return (await task)?.D;
    }
}
