// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class InventoryAssemblyOrders_PartItems_Response
{
    public InventoryAssemblyOrders_PartItems? ToItem() => D?.Results?.FirstOrDefault();

    public List<InventoryAssemblyOrders_PartItems> ToResults() => D?.Results ?? [];
}
