// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryItemWarehouseStorageLocations_ResponseExtensions
{
    public static async Task<List<InventoryItemWarehouseStorageLocations>> AsItems(this Task<InventoryItemWarehouseStorageLocations_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.InventoryItemWarehouseStorageLocations ?? d.InventoryItemWarehouseStorageLocationsResults?.Results ?? [];
    }

}
