// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryProcessStockCountGet_ResponseExtensions
{
    public static async Task<InventoryProcessStockCount?> AsItem(this Task<InventoryProcessStockCountGet_Response?> task)
    {
        return (await task)?.D;
    }
}
