// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryStorageLocations_ResponseExtensions
{
    public static async Task<List<InventoryStorageLocations>> AsItems(this Task<InventoryStorageLocations_Response?> task) => (await task)?.D?.Results ?? [];
}
