// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryAssemblyBillOfMaterialMaterialsPost_ResponseExtensions
{
    public static async Task<InventoryAssemblyBillOfMaterialMaterialsPost?> AsItem(this Task<InventoryAssemblyBillOfMaterialMaterialsPost_Response?> task)
    {
        return (await task)?.D;
    }
}
