// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class InventoryWarehouses_Response
{
    public List<InventoryWarehouses> ToResults() => D?.Results ?? [];
}
