// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class InventoryStockCounts_Response
{
    public List<InventoryStockCounts> ToResults() => D?.Results ?? [];
}
