// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryWarehouseTransfersGet_ResponseExtensions
{
    public static async Task<InventoryWarehouseTransfers?> AsItem(this Task<InventoryWarehouseTransfersGet_Response?> task)
    {
        return (await task)?.D;
    }
}
