// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryStockSerialNumbers_ResponseExtensions
{
    public static List<InventoryStockSerialNumbers> AsResults(this InventoryStockSerialNumbers_Response? response) => response?.D?.Results ?? [];
}
