// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class InventoryAssemblyBillOfMaterialHeader_ResponseExtensions
{
    public static async Task<List<InventoryAssemblyBillOfMaterialHeader>> AsItems(this Task<InventoryAssemblyBillOfMaterialHeader_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.InventoryAssemblyBillOfMaterialHeader ?? d.InventoryAssemblyBillOfMaterialHeaderResults?.Results ?? [];
    }

}
