// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class LogisticsReasonCodesLinkTypes_ResponseExtensions
{
    public static List<LogisticsReasonCodesLinkTypes> AsResults(this LogisticsReasonCodesLinkTypes_Response? response) => response?.D?.Results ?? [];
}
