// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class LogisticsIncotermsGet_ResponseExtensions
{
    public static async Task<LogisticsIncoterms?> AsItem(this Task<LogisticsIncotermsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
