// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class LogisticsCustomerItems_Response
{
    public List<LogisticsCustomerItems> ToResults() => D?.Results ?? [];
}
