// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class LogisticsItemAssortment_ResponseExtensions
{
    public static LogisticsItemAssortment? AsItem(this LogisticsItemAssortment_Response? response) => response?.D?.Results?.FirstOrDefault();
}
