// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class LogisticsItems_ResponseExtensions
{
    public static async Task<List<LogisticsItems>> AsResults(this Task<LogisticsItems_Response?> task) => (await task)?.D?.Results ?? [];
}
