// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class LogisticsItemAssortmentGet_ResponseExtensions
{
    public static async Task<LogisticsItemAssortment?> AsItem(this Task<LogisticsItemAssortmentGet_Response?> task)
    {
        return (await task)?.D;
    }
}
