// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class LogisticsItemGroupGet_ResponseExtensions
{
    public static async Task<LogisticsItemGroup?> AsItem(this Task<LogisticsItemGroupGet_Response?> task)
    {
        return (await task)?.D;
    }
}
