// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class LogisticsReasonCodes_Response
{
    public List<LogisticsReasonCodes> ToResults() => D?.Results ?? [];
}
