// <auto-generated/>
namespace ExactOnline.Api.Client.Models;

public partial class LogisticsItemAssortmentProperty
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Code), "Code" },
        { nameof(Description), "Description" },
        { nameof(Division), "Division" },
        { nameof(ID), "ID" },
        { nameof(ItemAssortmentCode), "ItemAssortmentCode" },
        { nameof(Metadata), "__metadata" }
    };
}
