// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class LogisticsReasonCodesLinkType_ResponseExtensions
{
    public static async Task<List<LogisticsReasonCodesLinkType>> AsItems(this Task<LogisticsReasonCodesLinkType_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.LogisticsReasonCodesLinkType ?? d.LogisticsReasonCodesLinkTypeResults?.Results ?? [];
    }

}
