// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class LogisticsCustomerItemsGet_ResponseExtensions
{
    public static async Task<LogisticsCustomerItems?> AsItem(this Task<LogisticsCustomerItemsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
