// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class MailboxMailMessagesSent_Response
{
    public MailboxMailMessagesSent? ToItem() => D?.Results?.FirstOrDefault();
}
