// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class MailboxMailMessageAttachmentsPost_ResponseExtensions
{
    public static async Task<MailboxMailMessageAttachmentsPost?> AsItem(this Task<MailboxMailMessageAttachmentsPost_Response?> task)
    {
        return (await task)?.D;
    }
}
