// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class MailboxMailMessagesSentGet_ResponseExtensions
{
    public static async Task<MailboxMailMessagesSent?> AsItem(this Task<MailboxMailMessagesSentGet_Response?> task)
    {
        return (await task)?.D;
    }
}
