// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class MailboxMailboxGet_ResponseExtensions
{
    public static async Task<MailboxMailbox?> AsItem(this Task<MailboxMailboxGet_Response?> task)
    {
        return (await task)?.D;
    }
}
