// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingShopOrderReversalGet_ResponseExtensions
{
    public static async Task<ManufacturingShopOrderReversal?> AsItem(this Task<ManufacturingShopOrderReversalGet_Response?> task)
    {
        return (await task)?.D;
    }
}
