// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingWorkcenters_ResponseExtensions
{
    public static List<ManufacturingWorkcenters> AsResults(this ManufacturingWorkcenters_Response? response) => response?.D?.Results ?? [];
}
