// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingBillOfMaterialVersions_ResponseExtensions
{
    public static async Task<List<ManufacturingBillOfMaterialVersions>> AsItems(this Task<ManufacturingBillOfMaterialVersions_Response?> task) => (await task)?.D?.Results ?? [];
}
