// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingMaterialIssueGet_ResponseExtensions
{
    public static async Task<ManufacturingMaterialIssue?> AsItem(this Task<ManufacturingMaterialIssueGet_Response?> task)
    {
        return (await task)?.D;
    }
}
