// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingBillOfMaterialMaterials_ResponseExtensions
{
    public static async Task<List<ManufacturingBillOfMaterialMaterials>> AsResults(this Task<ManufacturingBillOfMaterialMaterials_Response?> task) => (await task)?.D?.Results ?? [];
}
