// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingShopOrders_ResponseExtensions
{
    public static List<ManufacturingShopOrders> AsResults(this ManufacturingShopOrders_Response? response) => response?.D?.Results ?? [];
}
