// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingStageForDeliveryReversal_ResponseExtensions
{
    public static async Task<List<ManufacturingStageForDeliveryReversal>> AsItems(this Task<ManufacturingStageForDeliveryReversal_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ManufacturingStageForDeliveryReversal ?? d.ManufacturingStageForDeliveryReversalResults?.Results ?? [];
    }

}
