// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingBillOfMaterialVersions_ResponseExtensions
{
    public static List<ManufacturingBillOfMaterialVersions> AsResults(this ManufacturingBillOfMaterialVersions_Response? response) => response?.D?.Results ?? [];
}
