// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ManufacturingWorkcenters_Response
{
    public List<ManufacturingWorkcenters> ToResults() => D?.Results ?? [];
}
