// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingMaterialIssues_ResponseExtensions
{
    public static async Task<List<ManufacturingMaterialIssues>> AsItems(this Task<ManufacturingMaterialIssues_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ManufacturingMaterialIssues ?? d.ManufacturingMaterialIssuesResults?.Results ?? [];
    }

}
