// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingProductionAreasGet_ResponseExtensions
{
    public static async Task<ManufacturingProductionAreas?> AsItem(this Task<ManufacturingProductionAreasGet_Response?> task)
    {
        return (await task)?.D;
    }
}
