// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingMaterialIssue_ResponseExtensions
{
    public static async Task<List<ManufacturingMaterialIssue>> AsItems(this Task<ManufacturingMaterialIssue_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ManufacturingMaterialIssue ?? d.ManufacturingMaterialIssueResults?.Results ?? [];
    }

}
