// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingOperationResourceGet_ResponseExtensions
{
    public static async Task<ManufacturingOperationResource?> AsItem(this Task<ManufacturingOperationResourceGet_Response?> task)
    {
        return (await task)?.D;
    }
}
