// <auto-generated/>
namespace ExactOnline.Api.Client.Models;

public partial class ManufacturingShopOrderReceipts
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CreatedBy), "CreatedBy" },
        { nameof(CreatedByFullName), "CreatedByFullName" },
        { nameof(CreatedDate), "CreatedDate" },
        { nameof(DraftStockTransactionID), "DraftStockTransactionID" },
        { nameof(HasReversibleQuantity), "HasReversibleQuantity" },
        { nameof(IsBatch), "IsBatch" },
        { nameof(IsFractionAllowedItem), "IsFractionAllowedItem" },
        { nameof(IsIssueToParent), "IsIssueToParent" },
        { nameof(IsSerial), "IsSerial" },
        { nameof(Item), "Item" },
        { nameof(ItemCode), "ItemCode" },
        { nameof(ItemDescription), "ItemDescription" },
        { nameof(ItemPictureUrl), "ItemPictureUrl" },
        { nameof(Metadata), "__metadata" },
        { nameof(ParentShopOrder), "ParentShopOrder" },
        { nameof(ParentShopOrderNumber), "ParentShopOrderNumber" },
        { nameof(Quantity), "Quantity" },
        { nameof(ReceiptNumber), "ReceiptNumber" },
        { nameof(RelatedStockTransaction), "RelatedStockTransaction" },
        { nameof(ShopOrder), "ShopOrder" },
        { nameof(ShopOrderNumber), "ShopOrderNumber" },
        { nameof(StockTransactionId), "StockTransactionId" },
        { nameof(StorageLocation), "StorageLocation" },
        { nameof(StorageLocationCode), "StorageLocationCode" },
        { nameof(StorageLocationDescription), "StorageLocationDescription" },
        { nameof(TransactionDate), "TransactionDate" },
        { nameof(Unit), "Unit" },
        { nameof(UnitDescription), "UnitDescription" },
        { nameof(Warehouse), "Warehouse" },
        { nameof(WarehouseCode), "WarehouseCode" },
        { nameof(WarehouseDescription), "WarehouseDescription" }
    };
}
