// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingShopOrderRoutingStepPlansPost_ResponseExtensions
{
    public static async Task<ManufacturingShopOrderRoutingStepPlansPost?> AsItem(this Task<ManufacturingShopOrderRoutingStepPlansPost_Response?> task)
    {
        return (await task)?.D;
    }
}
