namespace ExactOnline.Api.Client.Models;
public partial class ManufacturingShopOrderRoutingStepPlans
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Account), "Account" },
        { nameof(AccountName), "AccountName" },
        { nameof(AccountNumber), "AccountNumber" },
        { nameof(AttendedPercentage), "AttendedPercentage" },
        { nameof(Backflush), "Backflush" },
        { nameof(CostPerItem), "CostPerItem" },
        { nameof(Created), "Created" },
        { nameof(Creator), "Creator" },
        { nameof(CreatorFullName), "CreatorFullName" },
        { nameof(Description), "Description" },
        { nameof(Division), "Division" },
        { nameof(EfficiencyPercentage), "EfficiencyPercentage" },
        { nameof(FactorType), "FactorType" },
        { nameof(ID), "ID" },
        { nameof(LineNumber), "LineNumber" },
        { nameof(Metadata), "__metadata" },
        { nameof(Modified), "Modified" },
        { nameof(Modifier), "Modifier" },
        { nameof(ModifierFullName), "ModifierFullName" },
        { nameof(Notes), "Notes" },
        { nameof(Operation), "Operation" },
        { nameof(OperationCode), "OperationCode" },
        { nameof(OperationDescription), "OperationDescription" },
        { nameof(OperationResource), "OperationResource" },
        { nameof(PlannedEndDate), "PlannedEndDate" },
        { nameof(PlannedRunHours), "PlannedRunHours" },
        { nameof(PlannedSetupHours), "PlannedSetupHours" },
        { nameof(PlannedStartDate), "PlannedStartDate" },
        { nameof(PlannedTotalHours), "PlannedTotalHours" },
        { nameof(PurchaseUnit), "PurchaseUnit" },
        { nameof(PurchaseUnitFactor), "PurchaseUnitFactor" },
        { nameof(PurchaseUnitPriceFC), "PurchaseUnitPriceFC" },
        { nameof(PurchaseUnitQuantity), "PurchaseUnitQuantity" },
        { nameof(RoutingStepType), "RoutingStepType" },
        { nameof(Run), "Run" },
        { nameof(RunMethod), "RunMethod" },
        { nameof(RunMethodDescription), "RunMethodDescription" },
        { nameof(Setup), "Setup" },
        { nameof(SetupUnit), "SetupUnit" },
        { nameof(ShopOrder), "ShopOrder" },
        { nameof(Status), "Status" },
        { nameof(StatusDescription), "StatusDescription" },
        { nameof(SubcontractedLeadDays), "SubcontractedLeadDays" },
        { nameof(TimeTransactions), "TimeTransactions" },
        { nameof(TotalCostDC), "TotalCostDC" },
        { nameof(Workcenter), "Workcenter" },
        { nameof(WorkcenterCode), "WorkcenterCode" },
        { nameof(WorkcenterDescription), "WorkcenterDescription" }
    };
}
