// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingOperationResourcesGet_ResponseExtensions
{
    public static async Task<ManufacturingOperationResources?> AsItem(this Task<ManufacturingOperationResourcesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
