// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingOperationResources_ResponseExtensions
{
    public static List<ManufacturingOperationResources> AsResults(this ManufacturingOperationResources_Response? response) => response?.D?.Results ?? [];
}
