// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ManufacturingShopOrderMaterialPlanDetails_Calculator_Response
{
    public ManufacturingShopOrderMaterialPlanDetails_Calculator? ToItem() => D?.Results?.FirstOrDefault();

    public List<ManufacturingShopOrderMaterialPlanDetails_Calculator> ToResults() => D?.Results ?? [];
}
