// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingBillOfMaterialRoutingsGet_ResponseExtensions
{
    public static async Task<ManufacturingBillOfMaterialRoutings?> AsItem(this Task<ManufacturingBillOfMaterialRoutingsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
