// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingByProductReceipt_ResponseExtensions
{
    public static async Task<List<ManufacturingByProductReceipt>> AsItems(this Task<ManufacturingByProductReceipt_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ManufacturingByProductReceipt ?? d.ManufacturingByProductReceiptResults?.Results ?? [];
    }

}
