// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingStageForDeliveryReversalsPost_ResponseExtensions
{
    public static async Task<ManufacturingStageForDeliveryReversals?> AsItem(this Task<ManufacturingStageForDeliveryReversalsPost_Response?> task)
    {
        return (await task)?.D;
    }
}
