// <auto-generated/>
namespace ExactOnline.Api.Client.Models;

public partial class ManufacturingOperationResource
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Account), "Account" },
        { nameof(AttendedPercentage), "AttendedPercentage" },
        { nameof(Created), "Created" },
        { nameof(Creator), "Creator" },
        { nameof(CreatorFullName), "CreatorFullName" },
        { nameof(Currency), "Currency" },
        { nameof(Division), "Division" },
        { nameof(EfficiencyPercentage), "EfficiencyPercentage" },
        { nameof(ID), "ID" },
        { nameof(IsPrimary), "IsPrimary" },
        { nameof(Metadata), "__metadata" },
        { nameof(Modified), "Modified" },
        { nameof(Modifier), "Modifier" },
        { nameof(ModifierFullName), "ModifierFullName" },
        { nameof(Operation), "Operation" },
        { nameof(OperationDescription), "OperationDescription" },
        { nameof(PurchaseLeadDays), "PurchaseLeadDays" },
        { nameof(PurchaseUnit), "PurchaseUnit" },
        { nameof(PurchaseVATCode), "PurchaseVATCode" },
        { nameof(Run), "Run" },
        { nameof(RunMethod), "RunMethod" },
        { nameof(Setup), "Setup" },
        { nameof(SetupUnit), "SetupUnit" },
        { nameof(Type), "Type" },
        { nameof(Workcenter), "Workcenter" },
        { nameof(WorkcenterDescription), "WorkcenterDescription" }
    };
}
