// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ManufacturingMaterialIssues_Response
{
    public List<ManufacturingMaterialIssues> ToResults() => D?.Results ?? [];
}
