// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingByProductReversal_ResponseExtensions
{
    public static async Task<List<ManufacturingByProductReversal>> AsItems(this Task<ManufacturingByProductReversal_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ManufacturingByProductReversal ?? d.ManufacturingByProductReversalResults?.Results ?? [];
    }

}
