// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ManufacturingBillOfMaterialRoutings_Response
{
    public List<ManufacturingBillOfMaterialRoutings> ToResults() => D?.Results ?? [];
}
