// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingOperationResource_ResponseExtensions
{
    public static async Task<List<ManufacturingOperationResource>> AsItems(this Task<ManufacturingOperationResource_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ManufacturingOperationResource ?? d.ManufacturingOperationResourceResults?.Results ?? [];
    }

}
