// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ManufacturingTimeTransactions_Response
{
    public List<ManufacturingTimeTransactions> ToResults() => D?.Results ?? [];
}
