// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingByProductReceiptGet_ResponseExtensions
{
    public static async Task<ManufacturingByProductReceipt?> AsItem(this Task<ManufacturingByProductReceiptGet_Response?> task)
    {
        return (await task)?.D;
    }
}
