// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingStageForDeliveryReversalGet_ResponseExtensions
{
    public static async Task<ManufacturingStageForDeliveryReversal?> AsItem(this Task<ManufacturingStageForDeliveryReversalGet_Response?> task)
    {
        return (await task)?.D;
    }
}
