// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingShopOrdersPost_ResponseExtensions
{
    public static async Task<ManufacturingShopOrdersPost?> AsItem(this Task<ManufacturingShopOrdersPost_Response?> task)
    {
        return (await task)?.D;
    }
}
