// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingOperationPost_ResponseExtensions
{
    public static async Task<ManufacturingOperationPost?> AsItem(this Task<ManufacturingOperationPost_Response?> task)
    {
        return (await task)?.D;
    }
}
