// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingStageForDeliveryReceiptPost_ResponseExtensions
{
    public static async Task<ManufacturingStageForDeliveryReceiptPost?> AsItem(this Task<ManufacturingStageForDeliveryReceiptPost_Response?> task)
    {
        return (await task)?.D;
    }
}
