// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ManufacturingShopOrderMaterialPlans_Response
{
    public List<ManufacturingShopOrderMaterialPlans> ToResults() => D?.Results ?? [];
}
