// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ManufacturingWorkcenters_ResponseExtensions
{
    public static async Task<List<ManufacturingWorkcenters>> AsResults(this Task<ManufacturingWorkcenters_Response?> task) => (await task)?.D?.Results ?? [];
}
