// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class OpeningBalancePreviousYearProcessed_ResponseExtensions
{
    public static OpeningBalancePreviousYearProcessed? AsItem(this OpeningBalancePreviousYearProcessed_Response? response) => response?.D?.Results?.FirstOrDefault();
}
