// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class OpeningBalanceCurrentYearAfterEntryGet_ResponseExtensions
{
    public static async Task<OpeningBalanceCurrentYearAfterEntry?> AsItem(this Task<OpeningBalanceCurrentYearAfterEntryGet_Response?> task)
    {
        return (await task)?.D;
    }
}
