// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class OpeningBalancePreviousYearAfterEntry_Response
{
    public OpeningBalancePreviousYearAfterEntry? ToItem() => D?.Results?.FirstOrDefault();
}
