// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class OpeningBalancePreviousYearAfterEntry_ResponseExtensions
{
    public static async Task<OpeningBalancePreviousYearAfterEntry?> AsItem(this Task<OpeningBalancePreviousYearAfterEntry_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? null : (d.OpeningBalancePreviousYearAfterEntry ?? d.OpeningBalancePreviousYearAfterEntryResults?.Results ?? []).FirstOrDefault();
    }

}
