// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class OpeningBalanceCurrentYearAfterEntry_ResponseExtensions
{
    public static OpeningBalanceCurrentYearAfterEntry? AsItem(this OpeningBalanceCurrentYearAfterEntry_Response? response) => response?.D?.Results?.FirstOrDefault();
}
