// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class OpeningBalanceCurrentYearProcessed_ResponseExtensions
{
    public static async Task<List<OpeningBalanceCurrentYearProcessed>> AsItems(this Task<OpeningBalanceCurrentYearProcessed_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.OpeningBalanceCurrentYearProcessed ?? d.OpeningBalanceCurrentYearProcessedResults?.Results ?? [];
    }

}
