// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class OpeningBalancePreviousYearAfterEntry_ResponseExtensions
{
    public static async Task<List<OpeningBalancePreviousYearAfterEntry>> AsItems(this Task<OpeningBalancePreviousYearAfterEntry_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.OpeningBalancePreviousYearAfterEntry ?? d.OpeningBalancePreviousYearAfterEntryResults?.Results ?? [];
    }

}
