// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class PayrollPayrollComponents_Response
{
    public List<PayrollPayrollComponents> ToResults() => D?.Results ?? [];
}
