// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class PayrollPayrollComponentGet_ResponseExtensions
{
    public static async Task<PayrollPayrollComponent?> AsItem(this Task<PayrollPayrollComponentGet_Response?> task)
    {
        return (await task)?.D;
    }
}
