namespace ExactOnline.Api.Client.Models;
public partial class PayrollPayrollTransactionsByPayrollYear
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CalculatedAmount), "CalculatedAmount" },
        { nameof(CalculatedBaseValue), "CalculatedBaseValue" },
        { nameof(CalculatedFranchise), "CalculatedFranchise" },
        { nameof(CalculatedMaximum), "CalculatedMaximum" },
        { nameof(CalculatedNumber), "CalculatedNumber" },
        { nameof(CostCenter), "CostCenter" },
        { nameof(CostCenterCode), "CostCenterCode" },
        { nameof(CostCenterDescription), "CostCenterDescription" },
        { nameof(CostUnit), "CostUnit" },
        { nameof(CostUnitCode), "CostUnitCode" },
        { nameof(CostUnitDescription), "CostUnitDescription" },
        { nameof(Created), "Created" },
        { nameof(Creator), "Creator" },
        { nameof(CreatorFullName), "CreatorFullName" },
        { nameof(Date), "Date" },
        { nameof(Department), "Department" },
        { nameof(DepartmentCode), "DepartmentCode" },
        { nameof(DepartmentDescription), "DepartmentDescription" },
        { nameof(Division), "Division" },
        { nameof(Employee), "Employee" },
        { nameof(EmployeeHID), "EmployeeHID" },
        { nameof(Employment), "Employment" },
        { nameof(EmploymentConditionGroup), "EmploymentConditionGroup" },
        { nameof(EmploymentConditionGroupCode), "EmploymentConditionGroupCode" },
        { nameof(EmploymentConditionGroupDescription), "EmploymentConditionGroupDescription" },
        { nameof(EntryAmount), "EntryAmount" },
        { nameof(EntryBase), "EntryBase" },
        { nameof(EntryNumber), "EntryNumber" },
        { nameof(EntryPercentage), "EntryPercentage" },
        { nameof(EntryPercentage2), "EntryPercentage2" },
        { nameof(EntryType), "EntryType" },
        { nameof(EntryTypeDescription), "EntryTypeDescription" },
        { nameof(Frequency), "Frequency" },
        { nameof(FullName), "FullName" },
        { nameof(ID), "ID" },
        { nameof(Metadata), "__metadata" },
        { nameof(ModifiedDate), "ModifiedDate" },
        { nameof(Modifier), "Modifier" },
        { nameof(ModifierFullName), "ModifierFullName" },
        { nameof(PayrollComponent), "PayrollComponent" },
        { nameof(PayrollComponentCode), "PayrollComponentCode" },
        { nameof(PayrollComponentDescription), "PayrollComponentDescription" },
        { nameof(PayrollComponentType), "PayrollComponentType" },
        { nameof(PayrollComponentTypeDescription), "PayrollComponentTypeDescription" },
        { nameof(PayrollRun), "PayrollRun" },
        { nameof(PayrollRunCode), "PayrollRunCode" },
        { nameof(PayrollYear), "PayrollYear" },
        { nameof(Period), "Period" },
        { nameof(Status), "Status" },
        { nameof(Type), "Type" },
        { nameof(TypeDescription), "TypeDescription" }
    };
}
