// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class PayrollActiveEmploymentGet_ResponseExtensions
{
    public static async Task<PayrollActiveEmployment?> AsItem(this Task<PayrollActiveEmploymentGet_Response?> task)
    {
        return (await task)?.D;
    }
}
