// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class PayrollEmployees_ResponseExtensions
{
    public static async Task<List<PayrollEmployees>> AsItems(this Task<PayrollEmployees_Response?> task) => (await task)?.D?.Results ?? [];
}
