// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class PayrollActiveEmploymentsGet_ResponseExtensions
{
    public static async Task<PayrollActiveEmployments?> AsItem(this Task<PayrollActiveEmploymentsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
