// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class PayrollEmploymentContractFlexPhases_Response
{
    public List<PayrollEmploymentContractFlexPhases> ToResults() => D?.Results ?? [];
}
