// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class PayrollEmploymentContractFlexPhases_ResponseExtensions
{
    public static async Task<List<PayrollEmploymentContractFlexPhases>> AsItems(this Task<PayrollEmploymentContractFlexPhases_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.PayrollEmploymentContractFlexPhases ?? d.PayrollEmploymentContractFlexPhasesResults?.Results ?? [];
    }

}
