// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class PayrollEmploymentTaxAuthoritiesGeneral_Response
{
    public PayrollEmploymentTaxAuthoritiesGeneral? ToItem() => D?.Results?.FirstOrDefault();
}
