// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class PayrollEmploymentContractsGet_ResponseExtensions
{
    public static async Task<PayrollEmploymentContracts?> AsItem(this Task<PayrollEmploymentContractsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
