// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class PayrollEmploymentOrganizations_ResponseExtensions
{
    public static async Task<List<PayrollEmploymentOrganizations>> AsResults(this Task<PayrollEmploymentOrganizations_Response?> task) => (await task)?.D?.Results ?? [];
}
