// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class PayrollEmployment_ResponseExtensions
{
    public static async Task<List<PayrollEmployment>> AsItems(this Task<PayrollEmployment_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.PayrollEmployment ?? d.PayrollEmploymentResults?.Results ?? [];
    }

}
