// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class PayrollEmploymentContractGet_ResponseExtensions
{
    public static async Task<PayrollEmploymentContract?> AsItem(this Task<PayrollEmploymentContractGet_Response?> task)
    {
        return (await task)?.D;
    }
}
