// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class PayrollEmploymentContracts_Response
{
    public List<PayrollEmploymentContracts> ToResults() => D?.Results ?? [];
}
