// <auto-generated/>
namespace ExactOnline.Api.Client.Models;

public partial class PayrollEmploymentConditionGroups
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(CLACodeTaxOffice), "CLACodeTaxOffice" },
        { nameof(CLACodeTaxOfficeDescription), "CLACodeTaxOfficeDescription" },
        { nameof(Code), "Code" },
        { nameof(Created), "Created" },
        { nameof(Creator), "Creator" },
        { nameof(CreatorFullName), "CreatorFullName" },
        { nameof(Description), "Description" },
        { nameof(Division), "Division" },
        { nameof(EndDate), "EndDate" },
        { nameof(HoursPerWeek), "HoursPerWeek" },
        { nameof(ID), "ID" },
        { nameof(Metadata), "__metadata" },
        { nameof(Modified), "Modified" },
        { nameof(Modifier), "Modifier" },
        { nameof(ModifierFullName), "ModifierFullName" },
        { nameof(SBICode), "SBICode" },
        { nameof(SBICodeDescription), "SBICodeDescription" },
        { nameof(StartDate), "StartDate" }
    };
}
