namespace ExactOnline.Api.Client.Models;
public partial class PayrollActiveEmployments
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AverageDaysPerWeek), "AverageDaysPerWeek" },
        { nameof(AverageHoursPerWeek), "AverageHoursPerWeek" },
        { nameof(Contract), "Contract" },
        { nameof(ContractDocument), "ContractDocument" },
        { nameof(ContractEndDate), "ContractEndDate" },
        { nameof(ContractProbationEndDate), "ContractProbationEndDate" },
        { nameof(ContractProbationPeriod), "ContractProbationPeriod" },
        { nameof(ContractStartDate), "ContractStartDate" },
        { nameof(ContractType), "ContractType" },
        { nameof(ContractTypeDescription), "ContractTypeDescription" },
        { nameof(Created), "Created" },
        { nameof(Creator), "Creator" },
        { nameof(CreatorFullName), "CreatorFullName" },
        { nameof(Department), "Department" },
        { nameof(DepartmentCode), "DepartmentCode" },
        { nameof(DepartmentDescription), "DepartmentDescription" },
        { nameof(Division), "Division" },
        { nameof(Employee), "Employee" },
        { nameof(EmployeeFullName), "EmployeeFullName" },
        { nameof(EmployeeHID), "EmployeeHID" },
        { nameof(EmploymentOrganization), "EmploymentOrganization" },
        { nameof(EndDate), "EndDate" },
        { nameof(HID), "HID" },
        { nameof(HourlyWage), "HourlyWage" },
        { nameof(ID), "ID" },
        { nameof(InternalRate), "InternalRate" },
        { nameof(Jobtitle), "Jobtitle" },
        { nameof(JobtitleDescription), "JobtitleDescription" },
        { nameof(Metadata), "__metadata" },
        { nameof(Modified), "Modified" },
        { nameof(Modifier), "Modifier" },
        { nameof(ModifierFullName), "ModifierFullName" },
        { nameof(ReasonEnd), "ReasonEnd" },
        { nameof(ReasonEndDescription), "ReasonEndDescription" },
        { nameof(ReasonEndFlex), "ReasonEndFlex" },
        { nameof(ReasonEndFlexDescription), "ReasonEndFlexDescription" },
        { nameof(Salary), "Salary" },
        { nameof(Schedule), "Schedule" },
        { nameof(ScheduleAverageHours), "ScheduleAverageHours" },
        { nameof(ScheduleCode), "ScheduleCode" },
        { nameof(ScheduleDays), "ScheduleDays" },
        { nameof(ScheduleDescription), "ScheduleDescription" },
        { nameof(ScheduleHours), "ScheduleHours" },
        { nameof(StartDate), "StartDate" },
        { nameof(StartDateOrganization), "StartDateOrganization" }
    };
}
