// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ProjectEmploymentInternalRatesGet_ResponseExtensions
{
    public static async Task<ProjectEmploymentInternalRates?> AsItem(this Task<ProjectEmploymentInternalRatesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
