// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ProjectProjectHourBudgetsGet_ResponseExtensions
{
    public static async Task<ProjectProjectHourBudgets?> AsItem(this Task<ProjectProjectHourBudgetsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
