// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ProjectProjectPlanning_Response
{
    public ProjectProjectPlanning? ToItem() => D?.Results?.FirstOrDefault();
}
