// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ProjectTimeTransactionsGet_ResponseExtensions
{
    public static async Task<ProjectTimeTransactions?> AsItem(this Task<ProjectTimeTransactionsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
