// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ProjectWBSActivityGet_ResponseExtensions
{
    public static async Task<ProjectWBSActivity?> AsItem(this Task<ProjectWBSActivityGet_Response?> task)
    {
        return (await task)?.D;
    }
}
