// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ProjectProjectRestrictionEmployeeItems_ResponseExtensions
{
    public static List<ProjectProjectRestrictionEmployeeItems> AsResults(this ProjectProjectRestrictionEmployeeItems_Response? response) => response?.D?.Results ?? [];
}
