// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ProjectCostTransactions_Response
{
    public List<ProjectCostTransactions> ToResults() => D?.Results ?? [];
}
