// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ProjectProjectRestrictionEmployeeItem_ResponseExtensions
{
    public static async Task<List<ProjectProjectRestrictionEmployeeItem>> AsItems(this Task<ProjectProjectRestrictionEmployeeItem_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ProjectProjectRestrictionEmployeeItem ?? d.ProjectProjectRestrictionEmployeeItemResults?.Results ?? [];
    }

}
