// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ProjectTimeCorrectionsPost_ResponseExtensions
{
    public static async Task<ProjectTimeCorrectionsPost?> AsItem(this Task<ProjectTimeCorrectionsPost_Response?> task)
    {
        return (await task)?.D;
    }
}
