// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ProjectWBSDeliverableGet_ResponseExtensions
{
    public static async Task<ProjectWBSDeliverable?> AsItem(this Task<ProjectWBSDeliverableGet_Response?> task)
    {
        return (await task)?.D;
    }
}
