// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ProjectProjectAccountMutations_ResponseExtensions
{
    public static async Task<List<ProjectProjectAccountMutations>> AsResults(this Task<ProjectProjectAccountMutations_Response?> task) => (await task)?.D?.Results ?? [];
}
