// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ProjectProjectPost_ResponseExtensions
{
    public static async Task<ProjectProjectPost?> AsItem(this Task<ProjectProjectPost_Response?> task)
    {
        return (await task)?.D;
    }
}
