// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ProjectTimeCorrectionPost_ResponseExtensions
{
    public static async Task<ProjectTimeCorrectionPost?> AsItem(this Task<ProjectTimeCorrectionPost_Response?> task)
    {
        return (await task)?.D;
    }
}
