// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ProjectProjects_ResponseExtensions
{
    public static async Task<List<ProjectProjects>> AsResults(this Task<ProjectProjects_Response?> task) => (await task)?.D?.Results ?? [];
}
