// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ProjectWBSExpenses_Response
{
    public List<ProjectWBSExpenses> ToResults() => D?.Results ?? [];
}
