// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ProjectProjectBudgetTypes_Response
{
    public List<ProjectProjectBudgetTypes> ToResults() => D?.Results ?? [];
}
