// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ProjectTimeCorrection_ResponseExtensions
{
    public static async Task<List<ProjectTimeCorrection>> AsItems(this Task<ProjectTimeCorrection_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ProjectTimeCorrection ?? d.ProjectTimeCorrectionResults?.Results ?? [];
    }

}
