// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ProjectInvoiceTermsPost_ResponseExtensions
{
    public static async Task<ProjectInvoiceTermsPost?> AsItem(this Task<ProjectInvoiceTermsPost_Response?> task)
    {
        return (await task)?.D;
    }
}
