// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ProjectEmployeeRestrictionItemGet_ResponseExtensions
{
    public static async Task<ProjectEmployeeRestrictionItem?> AsItem(this Task<ProjectEmployeeRestrictionItemGet_Response?> task)
    {
        return (await task)?.D;
    }
}
