// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ProjectWBSDeliverablePost_ResponseExtensions
{
    public static async Task<ProjectWBSDeliverablePost?> AsItem(this Task<ProjectWBSDeliverablePost_Response?> task)
    {
        return (await task)?.D;
    }
}
