namespace ExactOnline.Api.Client.Models;
public partial class ProjectProjectPlanningRecurring
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Account), "Account" },
        { nameof(AccountCode), "AccountCode" },
        { nameof(AccountName), "AccountName" },
        { nameof(BGTStatus), "BGTStatus" },
        { nameof(Created), "Created" },
        { nameof(Creator), "Creator" },
        { nameof(CreatorFullName), "CreatorFullName" },
        { nameof(CustomField), "CustomField" },
        { nameof(DayOrThe), "DayOrThe" },
        { nameof(Description), "Description" },
        { nameof(Division), "Division" },
        { nameof(Employee), "Employee" },
        { nameof(EmployeeCode), "EmployeeCode" },
        { nameof(EmployeeHID), "EmployeeHID" },
        { nameof(EndDate), "EndDate" },
        { nameof(EndDateOrAfter), "EndDateOrAfter" },
        { nameof(EndTime), "EndTime" },
        { nameof(HourType), "HourType" },
        { nameof(HourTypeCode), "HourTypeCode" },
        { nameof(HourTypeDescription), "HourTypeDescription" },
        { nameof(Hours), "Hours" },
        { nameof(ID), "ID" },
        { nameof(Metadata), "__metadata" },
        { nameof(Modified), "Modified" },
        { nameof(Modifier), "Modifier" },
        { nameof(ModifierFullName), "ModifierFullName" },
        { nameof(MonthPatternDay), "MonthPatternDay" },
        { nameof(MonthPatternOrdinalDay), "MonthPatternOrdinalDay" },
        { nameof(MonthPatternOrdinalWeek), "MonthPatternOrdinalWeek" },
        { nameof(Notes), "Notes" },
        { nameof(NumberOfRecurrences), "NumberOfRecurrences" },
        { nameof(OverAllocate), "OverAllocate" },
        { nameof(PatternFrequency), "PatternFrequency" },
        { nameof(Project), "Project" },
        { nameof(ProjectCode), "ProjectCode" },
        { nameof(ProjectDescription), "ProjectDescription" },
        { nameof(ProjectPlanningRecurringType), "ProjectPlanningRecurringType" },
        { nameof(ProjectWBS), "ProjectWBS" },
        { nameof(ProjectWBSDescription), "ProjectWBSDescription" },
        { nameof(StartDate), "StartDate" },
        { nameof(StartTime), "StartTime" },
        { nameof(Status), "Status" },
        { nameof(WeekPatternDay), "WeekPatternDay" },
        { nameof(WeekPatternFriday), "WeekPatternFriday" },
        { nameof(WeekPatternMonday), "WeekPatternMonday" },
        { nameof(WeekPatternSaturday), "WeekPatternSaturday" },
        { nameof(WeekPatternSunday), "WeekPatternSunday" },
        { nameof(WeekPatternThursday), "WeekPatternThursday" },
        { nameof(WeekPatternTuesday), "WeekPatternTuesday" },
        { nameof(WeekPatternWednesday), "WeekPatternWednesday" }
    };
}
