// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ProjectTimeTransactions_ResponseExtensions
{
    public static async Task<List<ProjectTimeTransactions>> AsItems(this Task<ProjectTimeTransactions_Response?> task) => (await task)?.D?.Results ?? [];
}
