// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ProjectEmployeeRestrictionItemsGet_ResponseExtensions
{
    public static async Task<ProjectEmployeeRestrictionItems?> AsItem(this Task<ProjectEmployeeRestrictionItemsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
