// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ProjectWBSDeliverables_ResponseExtensions
{
    public static async Task<List<ProjectWBSDeliverables>> AsItems(this Task<ProjectWBSDeliverables_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ProjectWBSDeliverables ?? d.ProjectWBSDeliverablesResults?.Results ?? [];
    }

}
