// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ProjectProjectRestrictionItems_Response
{
    public List<ProjectProjectRestrictionItems> ToResults() => D?.Results ?? [];
}
