// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ProjectProjectAccountMutationPost_ResponseExtensions
{
    public static async Task<ProjectProjectAccountMutationPost?> AsItem(this Task<ProjectProjectAccountMutationPost_Response?> task)
    {
        return (await task)?.D;
    }
}
