// <auto-generated/>
namespace ExactOnline.Api.Client.Models;

public partial class PurchaseOrderPurchaseOrderLine_ShopOrderRoutingStepPlans
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {

    };
}
