// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class PurchaseOrderPurchaseOrders_ResponseExtensions
{
    public static async Task<List<PurchaseOrderPurchaseOrders>> AsResults(this Task<PurchaseOrderPurchaseOrders_Response?> task) => (await task)?.D?.Results ?? [];
}
