// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class PurchasePurchaseInvoices_ResponseExtensions
{
    public static async Task<List<PurchasePurchaseInvoices>> AsItems(this Task<PurchasePurchaseInvoices_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.PurchasePurchaseInvoices ?? d.PurchasePurchaseInvoicesResults?.Results ?? [];
    }

}
