// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class PurchaseOrderPurchaseReturns_ResponseExtensions
{
    public static List<PurchaseOrderPurchaseReturns> AsResults(this PurchaseOrderPurchaseReturns_Response? response) => response?.D?.Results ?? [];
}
