// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class PurchaseOrderPurchaseReturnGet_ResponseExtensions
{
    public static async Task<PurchaseOrderPurchaseReturn?> AsItem(this Task<PurchaseOrderPurchaseReturnGet_Response?> task)
    {
        return (await task)?.D;
    }
}
