// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class PurchaseOrderPurchaseReturnLinesPost_ResponseExtensions
{
    public static async Task<PurchaseOrderPurchaseReturnLinesPost?> AsItem(this Task<PurchaseOrderPurchaseReturnLinesPost_Response?> task)
    {
        return (await task)?.D;
    }
}
