// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class PurchaseOrderPurchaseReturnLinesGet_ResponseExtensions
{
    public static async Task<PurchaseOrderPurchaseReturnLines?> AsItem(this Task<PurchaseOrderPurchaseReturnLinesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
