// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class PurchaseOrderGoodsReceiptLine_ResponseExtensions
{
    public static async Task<List<PurchaseOrderGoodsReceiptLine>> AsItems(this Task<PurchaseOrderGoodsReceiptLine_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.PurchaseOrderGoodsReceiptLine ?? d.PurchaseOrderGoodsReceiptLineResults?.Results ?? [];
    }

}
