// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class PurchaseOrderPurchaseReturnLines_ResponseExtensions
{
    public static List<PurchaseOrderPurchaseReturnLines> AsResults(this PurchaseOrderPurchaseReturnLines_Response? response) => response?.D?.Results ?? [];
}
