// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class PurchaseEntryPurchaseEntries_ResponseExtensions
{
    public static List<PurchaseEntryPurchaseEntries> AsResults(this PurchaseEntryPurchaseEntries_Response? response) => response?.D?.Results ?? [];
}
