// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class PurchaseOrderGoodsReceiptLinePost_ResponseExtensions
{
    public static async Task<PurchaseOrderGoodsReceiptLinePost?> AsItem(this Task<PurchaseOrderGoodsReceiptLinePost_Response?> task)
    {
        return (await task)?.D;
    }
}
