// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class PurchaseEntryPurchaseEntryLinesGet_ResponseExtensions
{
    public static async Task<PurchaseEntryPurchaseEntryLines?> AsItem(this Task<PurchaseEntryPurchaseEntryLinesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
