// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectTimeAndBillingAccountDetailsByID_ResponseExtensions
{
    public static ReadProjectTimeAndBillingAccountDetailsByID? AsItem(this ReadProjectTimeAndBillingAccountDetailsByID_Response? response) => response?.D?.Results?.FirstOrDefault();
}
