// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectTimeAndBillingProjectDetailsByID_ResponseExtensions
{
    public static ReadProjectTimeAndBillingProjectDetailsByID? AsItem(this ReadProjectTimeAndBillingProjectDetailsByID_Response? response) => response?.D?.Results?.FirstOrDefault();
}
