// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadLogisticsItemExtraField_ResponseExtensions
{
    public static ReadLogisticsItemExtraField? AsItem(this ReadLogisticsItemExtraField_Response? response) => response?.D?.Results?.FirstOrDefault();
}
