// <auto-generated/>
namespace ExactOnline.Api.Client.Models;

public partial class ReadProjectTimeAndBillingRecentProject
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(DateLastUsed), "DateLastUsed" },
        { nameof(Metadata), "__metadata" },
        { nameof(ProjectCode), "ProjectCode" },
        { nameof(ProjectDescription), "ProjectDescription" },
        { nameof(ProjectId), "ProjectId" }
    };
}
