// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadCRMDefaultAddressForAccountGet_ResponseExtensions
{
    public static async Task<ReadCRMDefaultAddressForAccount?> AsItem(this Task<ReadCRMDefaultAddressForAccountGet_Response?> task)
    {
        return (await task)?.D;
    }
}
