// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectRecentCosts_ResponseExtensions
{
    public static async Task<List<ReadProjectRecentCosts>> AsItems(this Task<ReadProjectRecentCosts_Response?> task) => (await task)?.D?.Results ?? [];
}
