// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectTimeAndBillingProjectDetails_ResponseExtensions
{
    public static async Task<List<ReadProjectTimeAndBillingProjectDetails>> AsResults(this Task<ReadProjectTimeAndBillingProjectDetails_Response?> task) => (await task)?.D?.Results ?? [];
}
