// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadFinancialAgingPayablesList_ResponseExtensions
{
    public static async Task<List<ReadFinancialAgingPayablesList>> AsItems(this Task<ReadFinancialAgingPayablesList_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ReadFinancialAgingPayablesList ?? d.ReadFinancialAgingPayablesListResults?.Results ?? [];
    }

}
