// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadFinancialReceivablesListByAccountAndAgeGroup_ResponseExtensions
{
    public static async Task<List<ReadFinancialReceivablesListByAccountAndAgeGroup>> AsItems(this Task<ReadFinancialReceivablesListByAccountAndAgeGroup_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ReadFinancialReceivablesListByAccountAndAgeGroup ?? d.ReadFinancialReceivablesListByAccountAndAgeGroupResults?.Results ?? [];
    }

}
