// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectRecentCostsByNumberOfWeeks_ResponseExtensions
{
    public static List<ReadProjectRecentCostsByNumberOfWeeks> AsResults(this ReadProjectRecentCostsByNumberOfWeeks_Response? response) => response?.D?.Results ?? [];
}
