// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectCostEntryRecentAccounts_ResponseExtensions
{
    public static async Task<List<ReadProjectCostEntryRecentAccounts>> AsResults(this Task<ReadProjectCostEntryRecentAccounts_Response?> task) => (await task)?.D?.Results ?? [];
}
