// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectRecentCost_ResponseExtensions
{
    public static async Task<List<ReadProjectRecentCost>> AsItems(this Task<ReadProjectRecentCost_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ReadProjectRecentCost ?? d.ReadProjectRecentCostResults?.Results ?? [];
    }

}
