// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadSalesInvoiceInvoiceSalesOrderResult_ResponseExtensions
{
    public static async Task<List<ReadSalesInvoiceInvoiceSalesOrderResult>> AsItems(this Task<ReadSalesInvoiceInvoiceSalesOrderResult_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ReadSalesInvoiceInvoiceSalesOrderResult ?? d.ReadSalesInvoiceInvoiceSalesOrderResultResults?.Results ?? [];
    }

}
