// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectHourEntryRecentAccounts_ResponseExtensions
{
    public static async Task<List<ReadProjectHourEntryRecentAccounts>> AsItems(this Task<ReadProjectHourEntryRecentAccounts_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ReadProjectHourEntryRecentAccounts ?? d.ReadProjectHourEntryRecentAccountsResults?.Results ?? [];
    }

}
