// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ReadFinancialRevenueList_Response
{
    public List<ReadFinancialRevenueList> ToResults() => D?.Results ?? [];
}
