// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ReadFinancialReportingBalanceByClassification_Response
{
    public ReadFinancialReportingBalanceByClassification? ToItem() => D?.Results?.FirstOrDefault();
}
