// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectHourTypesGet_ResponseExtensions
{
    public static async Task<ReadProjectHourTypes?> AsItem(this Task<ReadProjectHourTypesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
