// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectCostEntryRecentExpensesByProject_ResponseExtensions
{
    public static ReadProjectCostEntryRecentExpensesByProject? AsItem(this ReadProjectCostEntryRecentExpensesByProject_Response? response) => response?.D?.Results?.FirstOrDefault();
}
