// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectRecentHoursByNumberOfWeeksByDate_ResponseExtensions
{
    public static async Task<ReadProjectRecentHoursByNumberOfWeeksByDate?> AsItem(this Task<ReadProjectRecentHoursByNumberOfWeeksByDate_Response?> task) => (await task)?.D?.Results?.FirstOrDefault();
}
