// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadFinancialJournalStatusByFinancialPeriodGet_ResponseExtensions
{
    public static async Task<ReadFinancialJournalStatusByFinancialPeriod?> AsItem(this Task<ReadFinancialJournalStatusByFinancialPeriodGet_Response?> task)
    {
        return (await task)?.D;
    }
}
