// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadSalesInvoiceInvoiceSalesOrderResultGet_ResponseExtensions
{
    public static async Task<ReadSalesInvoiceInvoiceSalesOrderResult?> AsItem(this Task<ReadSalesInvoiceInvoiceSalesOrderResultGet_Response?> task)
    {
        return (await task)?.D;
    }
}
