// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadFinancialReturnGet_ResponseExtensions
{
    public static async Task<ReadFinancialReturn?> AsItem(this Task<ReadFinancialReturnGet_Response?> task)
    {
        return (await task)?.D;
    }
}
