// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadFinancialPayablesListByAgeGroupGet_ResponseExtensions
{
    public static async Task<ReadFinancialPayablesListByAgeGroup?> AsItem(this Task<ReadFinancialPayablesListByAgeGroupGet_Response?> task)
    {
        return (await task)?.D;
    }
}
