// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectHourCostTypeGet_ResponseExtensions
{
    public static async Task<ReadProjectHourCostType?> AsItem(this Task<ReadProjectHourCostTypeGet_Response?> task)
    {
        return (await task)?.D;
    }
}
