// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadCRMDocuments_ResponseExtensions
{
    public static async Task<List<ReadCRMDocuments>> AsItems(this Task<ReadCRMDocuments_Response?> task) => (await task)?.D?.Results ?? [];
}
