// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ReadProjectCostEntryRecentAccountsByProject_Response
{
    public ReadProjectCostEntryRecentAccountsByProject? ToItem() => D?.Results?.FirstOrDefault();
}
