// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadCRMDocument_ResponseExtensions
{
    public static async Task<List<ReadCRMDocument>> AsItems(this Task<ReadCRMDocument_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ReadCRMDocument ?? d.ReadCRMDocumentResults?.Results ?? [];
    }

}
