// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectCostTypesGet_ResponseExtensions
{
    public static async Task<ReadProjectCostTypes?> AsItem(this Task<ReadProjectCostTypesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
