// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectHourEntryRecentActivitiesByProject_ResponseExtensions
{
    public static ReadProjectHourEntryRecentActivitiesByProject? AsItem(this ReadProjectHourEntryRecentActivitiesByProject_Response? response) => response?.D?.Results?.FirstOrDefault();
}
