// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectCostEntryRecentCostTypesByProject_ResponseExtensions
{
    public static async Task<List<ReadProjectCostEntryRecentCostTypesByProject>> AsItems(this Task<ReadProjectCostEntryRecentCostTypesByProject_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ReadProjectCostEntryRecentCostTypesByProject ?? d.ReadProjectCostEntryRecentCostTypesByProjectResults?.Results ?? [];
    }

}
