// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectTimeAndBillingEntryAccount_ResponseExtensions
{
    public static async Task<List<ReadProjectTimeAndBillingEntryAccount>> AsItems(this Task<ReadProjectTimeAndBillingEntryAccount_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ReadProjectTimeAndBillingEntryAccount ?? d.ReadProjectTimeAndBillingEntryAccountResults?.Results ?? [];
    }

}
