// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectTimeAndBillingActivitiesAndExpenses_ResponseExtensions
{
    public static List<ReadProjectTimeAndBillingActivitiesAndExpenses> AsResults(this ReadProjectTimeAndBillingActivitiesAndExpenses_Response? response) => response?.D?.Results ?? [];
}
