// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ReadProjectCostEntryRecentProjects_Response
{
    public List<ReadProjectCostEntryRecentProjects> ToResults() => D?.Results ?? [];
}
