// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadFinancialReceivablesListByAccount_ResponseExtensions
{
    public static async Task<ReadFinancialReceivablesListByAccount?> AsItem(this Task<ReadFinancialReceivablesListByAccount_Response?> task) => (await task)?.D?.Results?.FirstOrDefault();
}
