// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectRecentHoursByNumberOfWeeksByDateGet_ResponseExtensions
{
    public static async Task<ReadProjectRecentHoursByNumberOfWeeksByDate?> AsItem(this Task<ReadProjectRecentHoursByNumberOfWeeksByDateGet_Response?> task)
    {
        return (await task)?.D;
    }
}
