// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadSyncSyncSyncTimestampGet_ResponseExtensions
{
    public static async Task<ReadSyncSyncSyncTimestamp?> AsItem(this Task<ReadSyncSyncSyncTimestampGet_Response?> task)
    {
        return (await task)?.D;
    }
}
