// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectHourTypesByProjectAndDateGet_ResponseExtensions
{
    public static async Task<ReadProjectHourTypesByProjectAndDate?> AsItem(this Task<ReadProjectHourTypesByProjectAndDateGet_Response?> task)
    {
        return (await task)?.D;
    }
}
