// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ReadProjectHourEntryActivitiesByProject_Response
{
    public ReadProjectHourEntryActivitiesByProject? ToItem() => D?.Results?.FirstOrDefault();
}
