// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadCRMOpportunityContact_ResponseExtensions
{
    public static async Task<List<ReadCRMOpportunityContact>> AsItems(this Task<ReadCRMOpportunityContact_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ReadCRMOpportunityContact ?? d.ReadCRMOpportunityContactResults?.Results ?? [];
    }

}
