// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadMailboxPreferredMailboxGet_ResponseExtensions
{
    public static async Task<ReadMailboxPreferredMailbox?> AsItem(this Task<ReadMailboxPreferredMailboxGet_Response?> task)
    {
        return (await task)?.D;
    }
}
