// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectHoursByDateGet_ResponseExtensions
{
    public static async Task<ReadProjectHoursByDate?> AsItem(this Task<ReadProjectHoursByDateGet_Response?> task)
    {
        return (await task)?.D;
    }
}
