// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectHoursByDate_ResponseExtensions
{
    public static ReadProjectHoursByDate? AsItem(this ReadProjectHoursByDate_Response? response) => response?.D?.Results?.FirstOrDefault();
}
