// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadFinancialJournalStatusList_ResponseExtensions
{
    public static List<ReadFinancialJournalStatusList> AsResults(this ReadFinancialJournalStatusList_Response? response) => response?.D?.Results ?? [];
}
