// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectCostsById_ResponseExtensions
{
    public static async Task<ReadProjectCostsById?> AsItem(this Task<ReadProjectCostsById_Response?> task) => (await task)?.D?.Results?.FirstOrDefault();
}
