// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectHourEntryRecentProjects_ResponseExtensions
{
    public static List<ReadProjectHourEntryRecentProjects> AsResults(this ReadProjectHourEntryRecentProjects_Response? response) => response?.D?.Results ?? [];
}
