// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadFinancialReturn_ResponseExtensions
{
    public static async Task<List<ReadFinancialReturn>> AsItems(this Task<ReadFinancialReturn_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ReadFinancialReturn ?? d.ReadFinancialReturnResults?.Results ?? [];
    }

}
