// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectHourTypes_ResponseExtensions
{
    public static async Task<List<ReadProjectHourTypes>> AsItems(this Task<ReadProjectHourTypes_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ReadProjectHourTypes ?? d.ReadProjectHourTypesResults?.Results ?? [];
    }

}
