// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadFinancialOutstandingInvoicesOverview_ResponseExtensions
{
    public static ReadFinancialOutstandingInvoicesOverview? AsItem(this ReadFinancialOutstandingInvoicesOverview_Response? response) => response?.D?.Results?.FirstOrDefault();
}
