// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ReadFinancialJournalStatusList_Response
{
    public List<ReadFinancialJournalStatusList> ToResults() => D?.Results ?? [];
}
