// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectHourCostType_ResponseExtensions
{
    public static async Task<List<ReadProjectHourCostType>> AsItems(this Task<ReadProjectHourCostType_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ReadProjectHourCostType ?? d.ReadProjectHourCostTypeResults?.Results ?? [];
    }

}
