// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectProjectWBSByProjectGet_ResponseExtensions
{
    public static async Task<ReadProjectProjectWBSByProject?> AsItem(this Task<ReadProjectProjectWBSByProjectGet_Response?> task)
    {
        return (await task)?.D;
    }
}
