// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadLogisticsSalesItemPrice_ResponseExtensions
{
    public static ReadLogisticsSalesItemPrice? AsItem(this ReadLogisticsSalesItemPrice_Response? response) => response?.D?.Results?.FirstOrDefault();
}
