// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ReadProjectRecentCosts_Response
{
    public List<ReadProjectRecentCosts> ToResults() => D?.Results ?? [];
}
