// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectRecentHoursByNumberOfWeekGet_ResponseExtensions
{
    public static async Task<ReadProjectRecentHoursByNumberOfWeek?> AsItem(this Task<ReadProjectRecentHoursByNumberOfWeekGet_Response?> task)
    {
        return (await task)?.D;
    }
}
