// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectTimeAndBillingItemDetails_ResponseExtensions
{
    public static async Task<List<ReadProjectTimeAndBillingItemDetails>> AsItems(this Task<ReadProjectTimeAndBillingItemDetails_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ReadProjectTimeAndBillingItemDetails ?? d.ReadProjectTimeAndBillingItemDetailsResults?.Results ?? [];
    }

}
