// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadCRMOpportunityContactsGet_ResponseExtensions
{
    public static async Task<ReadCRMOpportunityContacts?> AsItem(this Task<ReadCRMOpportunityContactsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
