// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadCRMAccountDocumentFolderGet_ResponseExtensions
{
    public static async Task<ReadCRMAccountDocumentFolder?> AsItem(this Task<ReadCRMAccountDocumentFolderGet_Response?> task)
    {
        return (await task)?.D;
    }
}
