// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectTimeAndBillingActivitiesAndExpense_ResponseExtensions
{
    public static async Task<List<ReadProjectTimeAndBillingActivitiesAndExpense>> AsItems(this Task<ReadProjectTimeAndBillingActivitiesAndExpense_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ReadProjectTimeAndBillingActivitiesAndExpense ?? d.ReadProjectTimeAndBillingActivitiesAndExpenseResults?.Results ?? [];
    }

}
