// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectCostsByDate_ResponseExtensions
{
    public static async Task<List<ReadProjectCostsByDate>> AsItems(this Task<ReadProjectCostsByDate_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ReadProjectCostsByDate ?? d.ReadProjectCostsByDateResults?.Results ?? [];
    }

}
