// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadCRMOpportunityDocumentsCount_ResponseExtensions
{
    public static async Task<ReadCRMOpportunityDocumentsCount?> AsItem(this Task<ReadCRMOpportunityDocumentsCount_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? null : (d.ReadCRMOpportunityDocumentsCount ?? d.ReadCRMOpportunityDocumentsCountResults?.Results ?? []).FirstOrDefault();
    }

}
