namespace ExactOnline.Api.Client.Models;
public partial class ReadManufacturingStartedTimedTimeTransactions
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Created), "Created" },
        { nameof(Creator), "Creator" },
        { nameof(CreatorFullName), "CreatorFullName" },
        { nameof(CustomerCode), "CustomerCode" },
        { nameof(CustomerCount), "CustomerCount" },
        { nameof(CustomerName), "CustomerName" },
        { nameof(DataType), "DataType" },
        { nameof(Division), "Division" },
        { nameof(Employee), "Employee" },
        { nameof(EndTime), "EndTime" },
        { nameof(ID), "ID" },
        { nameof(IsFractionAllowedItem), "IsFractionAllowedItem" },
        { nameof(IsOperationFinished), "IsOperationFinished" },
        { nameof(Item), "Item" },
        { nameof(ItemCode), "ItemCode" },
        { nameof(ItemPictureUrl), "ItemPictureUrl" },
        { nameof(ItemUnit), "ItemUnit" },
        { nameof(LaborHours), "LaborHours" },
        { nameof(MachineHours), "MachineHours" },
        { nameof(Metadata), "__metadata" },
        { nameof(Modified), "Modified" },
        { nameof(Modifier), "Modifier" },
        { nameof(ModifierFullName), "ModifierFullName" },
        { nameof(Notes), "Notes" },
        { nameof(Operation), "Operation" },
        { nameof(OperationCode), "OperationCode" },
        { nameof(PercentComplete), "PercentComplete" },
        { nameof(ProducedQuantity), "ProducedQuantity" },
        { nameof(Project), "Project" },
        { nameof(ProjectCode), "ProjectCode" },
        { nameof(ProjectDescription), "ProjectDescription" },
        { nameof(SalesOrderCount), "SalesOrderCount" },
        { nameof(SalesOrderLineNumber), "SalesOrderLineNumber" },
        { nameof(SalesOrderNumber), "SalesOrderNumber" },
        { nameof(ShopOrder), "ShopOrder" },
        { nameof(ShopOrderDescription), "ShopOrderDescription" },
        { nameof(ShopOrderNumber), "ShopOrderNumber" },
        { nameof(ShopOrderPlannedQuantity), "ShopOrderPlannedQuantity" },
        { nameof(ShopOrderRoutingStepPlan), "ShopOrderRoutingStepPlan" },
        { nameof(ShopOrderRoutingStepPlanAttendedPercentage), "ShopOrderRoutingStepPlanAttendedPercentage" },
        { nameof(ShopOrderRoutingStepPlanDescription), "ShopOrderRoutingStepPlanDescription" },
        { nameof(Source), "Source" },
        { nameof(StartTime), "StartTime" },
        { nameof(Status), "Status" },
        { nameof(Type), "Type" },
        { nameof(Warehouse), "Warehouse" },
        { nameof(Workcenter), "Workcenter" },
        { nameof(WorkcenterCode), "WorkcenterCode" },
        { nameof(WorkcenterDescription), "WorkcenterDescription" }
    };
}
