// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectHourEntryRecentAccounts_ResponseExtensions
{
    public static List<ReadProjectHourEntryRecentAccounts> AsResults(this ReadProjectHourEntryRecentAccounts_Response? response) => response?.D?.Results ?? [];
}
