namespace ExactOnline.Api.Client.Models;
public partial class ReadLogisticsAccountItems
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(Account), "Account" },
        { nameof(Barcode), "Barcode" },
        { nameof(Code), "Code" },
        { nameof(CostPriceCurrency), "CostPriceCurrency" },
        { nameof(CostPriceNew), "CostPriceNew" },
        { nameof(CostPriceStandard), "CostPriceStandard" },
        { nameof(Created), "Created" },
        { nameof(Creator), "Creator" },
        { nameof(CreatorFullName), "CreatorFullName" },
        { nameof(DefaultSalesPrice), "DefaultSalesPrice" },
        { nameof(Description), "Description" },
        { nameof(Division), "Division" },
        { nameof(EndDate), "EndDate" },
        { nameof(ID), "ID" },
        { nameof(IsFractionAllowedItem), "IsFractionAllowedItem" },
        { nameof(IsSalesItem), "IsSalesItem" },
        { nameof(IsStockItem), "IsStockItem" },
        { nameof(IsTaxableItem), "IsTaxableItem" },
        { nameof(IsWebshopItem), "IsWebshopItem" },
        { nameof(ItemGroup), "ItemGroup" },
        { nameof(ItemGroupCode), "ItemGroupCode" },
        { nameof(ItemGroupDescription), "ItemGroupDescription" },
        { nameof(Margin), "Margin" },
        { nameof(Markup), "Markup" },
        { nameof(Metadata), "__metadata" },
        { nameof(Modified), "Modified" },
        { nameof(Modifier), "Modifier" },
        { nameof(ModifierFullName), "ModifierFullName" },
        { nameof(Notes), "Notes" },
        { nameof(PictureName), "PictureName" },
        { nameof(PictureThumbnailUrl), "PictureThumbnailUrl" },
        { nameof(PictureUrl), "PictureUrl" },
        { nameof(ProjectedStock), "ProjectedStock" },
        { nameof(PurchaseLeadDays), "PurchaseLeadDays" },
        { nameof(QuantityToBeConsumed), "QuantityToBeConsumed" },
        { nameof(QuantityToBeDelivered), "QuantityToBeDelivered" },
        { nameof(QuantityToBeProduced), "QuantityToBeProduced" },
        { nameof(QuantityToBeReceived), "QuantityToBeReceived" },
        { nameof(ReservedStock), "ReservedStock" },
        { nameof(SalesCurrency), "SalesCurrency" },
        { nameof(SalesPrice), "SalesPrice" },
        { nameof(SalesVatCode), "SalesVatCode" },
        { nameof(SalesVatCodeDescription), "SalesVatCodeDescription" },
        { nameof(StartDate), "StartDate" },
        { nameof(Stock), "Stock" },
        { nameof(Unit), "Unit" },
        { nameof(UnitCode), "UnitCode" },
        { nameof(UnitDescription), "UnitDescription" },
        { nameof(UnitType), "UnitType" }
    };
}
