// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ReadProjectCostTypesByDate_Response
{
    public ReadProjectCostTypesByDate? ToItem() => D?.Results?.FirstOrDefault();
}
