// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectCostEntryRecentAccountsByProjectGet_ResponseExtensions
{
    public static async Task<ReadProjectCostEntryRecentAccountsByProject?> AsItem(this Task<ReadProjectCostEntryRecentAccountsByProjectGet_Response?> task)
    {
        return (await task)?.D;
    }
}
