// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadFinancialAgingOverview_ResponseExtensions
{
    public static async Task<ReadFinancialAgingOverview?> AsItem(this Task<ReadFinancialAgingOverview_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? null : (d.ReadFinancialAgingOverview ?? d.ReadFinancialAgingOverviewResults?.Results ?? []).FirstOrDefault();
    }

}
