// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectTimeAndBillingEntryProjectsByAccountAndDate_ResponseExtensions
{
    public static ReadProjectTimeAndBillingEntryProjectsByAccountAndDate? AsItem(this ReadProjectTimeAndBillingEntryProjectsByAccountAndDate_Response? response) => response?.D?.Results?.FirstOrDefault();
}
