// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadCRMDefaultAddressForAccount_ResponseExtensions
{
    public static ReadCRMDefaultAddressForAccount? AsItem(this ReadCRMDefaultAddressForAccount_Response? response) => response?.D?.Results?.FirstOrDefault();
}
