// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectTimeAndBillingProjectDetailsGet_ResponseExtensions
{
    public static async Task<ReadProjectTimeAndBillingProjectDetails?> AsItem(this Task<ReadProjectTimeAndBillingProjectDetailsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
