// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectCostEntryRecentExpensesByProject_ResponseExtensions
{
    public static async Task<List<ReadProjectCostEntryRecentExpensesByProject>> AsItems(this Task<ReadProjectCostEntryRecentExpensesByProject_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ReadProjectCostEntryRecentExpensesByProject ?? d.ReadProjectCostEntryRecentExpensesByProjectResults?.Results ?? [];
    }

}
