// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectCostTypes_ResponseExtensions
{
    public static async Task<List<ReadProjectCostTypes>> AsItems(this Task<ReadProjectCostTypes_Response?> task) => (await task)?.D?.Results ?? [];
}
