// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectRecentCostsByNumberOfWeeksByDate_ResponseExtensions
{
    public static async Task<List<ReadProjectRecentCostsByNumberOfWeeksByDate>> AsItems(this Task<ReadProjectRecentCostsByNumberOfWeeksByDate_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ReadProjectRecentCostsByNumberOfWeeksByDate ?? d.ReadProjectRecentCostsByNumberOfWeeksByDateResults?.Results ?? [];
    }

}
