// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ReadMailboxPreferredMailbox_Response
{
    public ReadMailboxPreferredMailbox? ToItem() => D?.Results?.FirstOrDefault();
}
