// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ReadMailboxDefaultMailbox_Response
{
    public ReadMailboxDefaultMailbox? ToItem() => D?.Results?.FirstOrDefault();
}
