// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ReadProjectProjectWBSByProject_Response
{
    public ReadProjectProjectWBSByProject? ToItem() => D?.Results?.FirstOrDefault();
}
