// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadFinancialAgingOverviewByAccount_ResponseExtensions
{
    public static async Task<List<ReadFinancialAgingOverviewByAccount>> AsItems(this Task<ReadFinancialAgingOverviewByAccount_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ReadFinancialAgingOverviewByAccount ?? d.ReadFinancialAgingOverviewByAccountResults?.Results ?? [];
    }

}
