// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectTimeAndBillingEntryProjects_ResponseExtensions
{
    public static async Task<List<ReadProjectTimeAndBillingEntryProjects>> AsItems(this Task<ReadProjectTimeAndBillingEntryProjects_Response?> task) => (await task)?.D?.Results ?? [];
}
