// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadFinancialRevenueListByYearAndStatus_ResponseExtensions
{
    public static async Task<List<ReadFinancialRevenueListByYearAndStatus>> AsItems(this Task<ReadFinancialRevenueListByYearAndStatus_Response?> task) => (await task)?.D?.Results ?? [];
}
