// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectCostEntryRecentProjects_ResponseExtensions
{
    public static async Task<List<ReadProjectCostEntryRecentProjects>> AsItems(this Task<ReadProjectCostEntryRecentProjects_Response?> task) => (await task)?.D?.Results ?? [];
}
