// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadFinancialProfitLossOverview_ResponseExtensions
{
    public static async Task<List<ReadFinancialProfitLossOverview>> AsItems(this Task<ReadFinancialProfitLossOverview_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ReadFinancialProfitLossOverview ?? d.ReadFinancialProfitLossOverviewResults?.Results ?? [];
    }

}
