// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectCostEntryRecentAccountsByProject_ResponseExtensions
{
    public static async Task<ReadProjectCostEntryRecentAccountsByProject?> AsItem(this Task<ReadProjectCostEntryRecentAccountsByProject_Response?> task) => (await task)?.D?.Results?.FirstOrDefault();
}
