// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadCRMAccountDocumentFolders_ResponseExtensions
{
    public static List<ReadCRMAccountDocumentFolders> AsResults(this ReadCRMAccountDocumentFolders_Response? response) => response?.D?.Results ?? [];
}
