// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ReadFinancialAgingOverviewByAccount_Response
{
    public ReadFinancialAgingOverviewByAccount? ToItem() => D?.Results?.FirstOrDefault();
}
