// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectCostEntryRecentAccountsByProject_ResponseExtensions
{
    public static ReadProjectCostEntryRecentAccountsByProject? AsItem(this ReadProjectCostEntryRecentAccountsByProject_Response? response) => response?.D?.Results?.FirstOrDefault();
}
