// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectRecentCostsByNumberOfWeeksGet_ResponseExtensions
{
    public static async Task<ReadProjectRecentCostsByNumberOfWeeks?> AsItem(this Task<ReadProjectRecentCostsByNumberOfWeeksGet_Response?> task)
    {
        return (await task)?.D;
    }
}
