// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadManufacturingStartedTimedTimeTransactions_ResponseExtensions
{
    public static async Task<List<ReadManufacturingStartedTimedTimeTransactions>> AsItems(this Task<ReadManufacturingStartedTimedTimeTransactions_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.ReadManufacturingStartedTimedTimeTransactions ?? d.ReadManufacturingStartedTimedTimeTransactionsResults?.Results ?? [];
    }

}
