// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectProjectWBSByProject_ResponseExtensions
{
    public static ReadProjectProjectWBSByProject? AsItem(this ReadProjectProjectWBSByProject_Response? response) => response?.D?.Results?.FirstOrDefault();
}
