// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadManufacturingRecentTimeTransactions_ResponseExtensions
{
    public static List<ReadManufacturingRecentTimeTransactions> AsResults(this ReadManufacturingRecentTimeTransactions_Response? response) => response?.D?.Results ?? [];
}
