// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class ReadProjectRecentCostsByNumberOfWeeks_Response
{
    public List<ReadProjectRecentCostsByNumberOfWeeks> ToResults() => D?.Results ?? [];
}
