// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadMailboxPreferredMailbox_ResponseExtensions
{
    public static ReadMailboxPreferredMailbox? AsItem(this ReadMailboxPreferredMailbox_Response? response) => response?.D?.Results?.FirstOrDefault();
}
