// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class ReadProjectTimeAndBillingEntryAccountsByProjectAndDate_ResponseExtensions
{
    public static async Task<ReadProjectTimeAndBillingEntryAccountsByProjectAndDate?> AsItem(this Task<ReadProjectTimeAndBillingEntryAccountsByProjectAndDate_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? null : (d.ReadProjectTimeAndBillingEntryAccountsByProjectAndDate ?? d.ReadProjectTimeAndBillingEntryAccountsByProjectAndDateResults?.Results ?? []).FirstOrDefault();
    }

}
