// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesSalesPriceListVolumeDiscount_ResponseExtensions
{
    public static async Task<List<SalesSalesPriceListVolumeDiscount>> AsItems(this Task<SalesSalesPriceListVolumeDiscount_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.SalesSalesPriceListVolumeDiscount ?? d.SalesSalesPriceListVolumeDiscountResults?.Results ?? [];
    }

}
