// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesSalesPriceListVolumeDiscountGet_ResponseExtensions
{
    public static async Task<SalesSalesPriceListVolumeDiscount?> AsItem(this Task<SalesSalesPriceListVolumeDiscountGet_Response?> task)
    {
        return (await task)?.D;
    }
}
