// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesOrderPlannedSalesReturnLineGet_ResponseExtensions
{
    public static async Task<SalesOrderPlannedSalesReturnLine?> AsItem(this Task<SalesOrderPlannedSalesReturnLineGet_Response?> task)
    {
        return (await task)?.D;
    }
}
