// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class SalesEntrySalesEntries_Response
{
    public List<SalesEntrySalesEntries> ToResults() => D?.Results ?? [];
}
