// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesOrderDropShipmentsGet_ResponseExtensions
{
    public static async Task<SalesOrderDropShipments?> AsItem(this Task<SalesOrderDropShipmentsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
