namespace ExactOnline.Api.Client.Models;
public partial class SalesEntrySalesEntries
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AmountDC), "AmountDC" },
        { nameof(AmountFC), "AmountFC" },
        { nameof(BatchNumber), "BatchNumber" },
        { nameof(Created), "Created" },
        { nameof(Creator), "Creator" },
        { nameof(CreatorFullName), "CreatorFullName" },
        { nameof(Currency), "Currency" },
        { nameof(CustomField), "CustomField" },
        { nameof(Customer), "Customer" },
        { nameof(CustomerName), "CustomerName" },
        { nameof(Description), "Description" },
        { nameof(Division), "Division" },
        { nameof(Document), "Document" },
        { nameof(DocumentNumber), "DocumentNumber" },
        { nameof(DocumentSubject), "DocumentSubject" },
        { nameof(DueDate), "DueDate" },
        { nameof(EntryDate), "EntryDate" },
        { nameof(EntryID), "EntryID" },
        { nameof(EntryNumber), "EntryNumber" },
        { nameof(ExternalLinkDescription), "ExternalLinkDescription" },
        { nameof(ExternalLinkReference), "ExternalLinkReference" },
        { nameof(GAccountAmountFC), "GAccountAmountFC" },
        { nameof(InvoiceNumber), "InvoiceNumber" },
        { nameof(IsExtraDuty), "IsExtraDuty" },
        { nameof(Journal), "Journal" },
        { nameof(JournalDescription), "JournalDescription" },
        { nameof(Metadata), "__metadata" },
        { nameof(Modified), "Modified" },
        { nameof(Modifier), "Modifier" },
        { nameof(ModifierFullName), "ModifierFullName" },
        { nameof(OrderNumber), "OrderNumber" },
        { nameof(PaymentCondition), "PaymentCondition" },
        { nameof(PaymentConditionDescription), "PaymentConditionDescription" },
        { nameof(PaymentConditionPaymentMethod), "PaymentConditionPaymentMethod" },
        { nameof(PaymentReference), "PaymentReference" },
        { nameof(ProcessNumber), "ProcessNumber" },
        { nameof(Rate), "Rate" },
        { nameof(ReportingPeriod), "ReportingPeriod" },
        { nameof(ReportingYear), "ReportingYear" },
        { nameof(Reversal), "Reversal" },
        { nameof(SalesEntryLines), "SalesEntryLines" },
        { nameof(Status), "Status" },
        { nameof(StatusDescription), "StatusDescription" },
        { nameof(Type), "Type" },
        { nameof(TypeDescription), "TypeDescription" },
        { nameof(VATAmountDC), "VATAmountDC" },
        { nameof(VATAmountFC), "VATAmountFC" },
        { nameof(WithholdingTaxAmountDC), "WithholdingTaxAmountDC" },
        { nameof(WithholdingTaxBaseAmount), "WithholdingTaxBaseAmount" },
        { nameof(WithholdingTaxPercentage), "WithholdingTaxPercentage" },
        { nameof(YourRef), "YourRef" }
    };
}
