// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesInvoiceSalesOrderID_ResponseExtensions
{
    public static async Task<List<SalesInvoiceSalesOrderID>> AsItems(this Task<SalesInvoiceSalesOrderID_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.SalesInvoiceSalesOrderID ?? d.SalesInvoiceSalesOrderIDResults?.Results ?? [];
    }

}
