namespace ExactOnline.Api.Client.Models;
public partial class SalesEntrySalesEntryLines
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AmountDC), "AmountDC" },
        { nameof(AmountFC), "AmountFC" },
        { nameof(Asset), "Asset" },
        { nameof(AssetDescription), "AssetDescription" },
        { nameof(CostCenter), "CostCenter" },
        { nameof(CostCenterDescription), "CostCenterDescription" },
        { nameof(CostUnit), "CostUnit" },
        { nameof(CostUnitDescription), "CostUnitDescription" },
        { nameof(CustomField), "CustomField" },
        { nameof(Description), "Description" },
        { nameof(Division), "Division" },
        { nameof(EntryID), "EntryID" },
        { nameof(ExtraDutyAmountFC), "ExtraDutyAmountFC" },
        { nameof(ExtraDutyPercentage), "ExtraDutyPercentage" },
        { nameof(From), "From" },
        { nameof(GLAccount), "GLAccount" },
        { nameof(GLAccountCode), "GLAccountCode" },
        { nameof(GLAccountDescription), "GLAccountDescription" },
        { nameof(ID), "ID" },
        { nameof(IntraStatArea), "IntraStatArea" },
        { nameof(IntraStatCountry), "IntraStatCountry" },
        { nameof(IntraStatDeliveryTerm), "IntraStatDeliveryTerm" },
        { nameof(IntraStatTransactionA), "IntraStatTransactionA" },
        { nameof(IntraStatTransactionB), "IntraStatTransactionB" },
        { nameof(IntraStatTransportMethod), "IntraStatTransportMethod" },
        { nameof(LineNumber), "LineNumber" },
        { nameof(Metadata), "__metadata" },
        { nameof(Notes), "Notes" },
        { nameof(Project), "Project" },
        { nameof(ProjectDescription), "ProjectDescription" },
        { nameof(Quantity), "Quantity" },
        { nameof(SerialNumber), "SerialNumber" },
        { nameof(StatisticalNetWeight), "StatisticalNetWeight" },
        { nameof(StatisticalNumber), "StatisticalNumber" },
        { nameof(StatisticalQuantity), "StatisticalQuantity" },
        { nameof(StatisticalValue), "StatisticalValue" },
        { nameof(Subscription), "Subscription" },
        { nameof(SubscriptionDescription), "SubscriptionDescription" },
        { nameof(TaxSchedule), "TaxSchedule" },
        { nameof(To), "To" },
        { nameof(TrackingNumber), "TrackingNumber" },
        { nameof(TrackingNumberDescription), "TrackingNumberDescription" },
        { nameof(Type), "Type" },
        { nameof(VATAmountDC), "VATAmountDC" },
        { nameof(VATAmountFC), "VATAmountFC" },
        { nameof(VATBaseAmountDC), "VATBaseAmountDC" },
        { nameof(VATBaseAmountFC), "VATBaseAmountFC" },
        { nameof(VATCode), "VATCode" },
        { nameof(VATCodeDescription), "VATCodeDescription" },
        { nameof(VATPercentage), "VATPercentage" }
    };
}
