// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class SalesInvoiceSalesInvoiceOrderChargeLines_Response
{
    public List<SalesInvoiceSalesInvoiceOrderChargeLines> ToResults() => D?.Results ?? [];
}
