// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesInvoiceInvoiceSalesOrdersPost_ResponseExtensions
{
    public static async Task<SalesInvoiceInvoiceSalesOrdersPost?> AsItem(this Task<SalesInvoiceInvoiceSalesOrdersPost_Response?> task)
    {
        return (await task)?.D;
    }
}
