// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesOrderPrintedSalesOrdersPost_ResponseExtensions
{
    public static async Task<SalesOrderPrintedSalesOrders?> AsItem(this Task<SalesOrderPrintedSalesOrdersPost_Response?> task)
    {
        return (await task)?.D;
    }
}
