// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class SalesInvoiceInvoiceSalesOrders_Response
{
    public SalesInvoiceInvoiceSalesOrders? ToItem() => D?.Results?.FirstOrDefault();

    public List<SalesInvoiceInvoiceSalesOrders> ToResults() => D?.Results ?? [];
}
