// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesInvoiceSalesInvoiceOrderChargeLines_ResponseExtensions
{
    public static List<SalesInvoiceSalesInvoiceOrderChargeLines> AsResults(this SalesInvoiceSalesInvoiceOrderChargeLines_Response? response) => response?.D?.Results ?? [];
}
