// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesInvoiceSalesInvoiceLines_ResponseExtensions
{
    public static List<SalesInvoiceSalesInvoiceLines> AsResults(this SalesInvoiceSalesInvoiceLines_Response? response) => response?.D?.Results ?? [];
}
