// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesSalesPriceListLinkedAccountGet_ResponseExtensions
{
    public static async Task<SalesSalesPriceListLinkedAccount?> AsItem(this Task<SalesSalesPriceListLinkedAccountGet_Response?> task)
    {
        return (await task)?.D;
    }
}
