// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesEntrySalesEntryLine_ResponseExtensions
{
    public static async Task<List<SalesEntrySalesEntryLine>> AsItems(this Task<SalesEntrySalesEntryLine_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.SalesEntrySalesEntryLine ?? d.SalesEntrySalesEntryLineResults?.Results ?? [];
    }

}
