// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesOrderPlannedSalesReturnGet_ResponseExtensions
{
    public static async Task<SalesOrderPlannedSalesReturn?> AsItem(this Task<SalesOrderPlannedSalesReturnGet_Response?> task)
    {
        return (await task)?.D;
    }
}
