// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class SalesInvoiceSalesInvoices_Response
{
    public List<SalesInvoiceSalesInvoices> ToResults() => D?.Results ?? [];
}
