// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesSalesPriceListVolumeDiscounts_ResponseExtensions
{
    public static async Task<List<SalesSalesPriceListVolumeDiscounts>> AsResults(this Task<SalesSalesPriceListVolumeDiscounts_Response?> task) => (await task)?.D?.Results ?? [];
}
