// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesEntrySalesEntries_ResponseExtensions
{
    public static async Task<List<SalesEntrySalesEntries>> AsResults(this Task<SalesEntrySalesEntries_Response?> task) => (await task)?.D?.Results ?? [];
}
