// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesOrderPlannedSalesReturnLines_ResponseExtensions
{
    public static async Task<List<SalesOrderPlannedSalesReturnLines>> AsItems(this Task<SalesOrderPlannedSalesReturnLines_Response?> task) => (await task)?.D?.Results ?? [];
}
