// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class SalesShippingMethods_Response
{
    public List<SalesShippingMethods> ToResults() => D?.Results ?? [];
}
