// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesInvoiceSalesInvoicesGet_ResponseExtensions
{
    public static async Task<SalesInvoiceSalesInvoices?> AsItem(this Task<SalesInvoiceSalesInvoicesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
