// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesShippingMethod_ResponseExtensions
{
    public static async Task<List<SalesShippingMethod>> AsItems(this Task<SalesShippingMethod_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.SalesShippingMethod ?? d.SalesShippingMethodResults?.Results ?? [];
    }

}
