// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesInvoiceLayouts_ResponseExtensions
{
    public static List<SalesInvoiceLayouts> AsResults(this SalesInvoiceLayouts_Response? response) => response?.D?.Results ?? [];
}
