// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesSalesPriceListPeriod_ResponseExtensions
{
    public static async Task<List<SalesSalesPriceListPeriod>> AsItems(this Task<SalesSalesPriceListPeriod_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.SalesSalesPriceListPeriod ?? d.SalesSalesPriceListPeriodResults?.Results ?? [];
    }

}
