// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesOrderSalesOrderOrderChargeLines_ResponseExtensions
{
    public static List<SalesOrderSalesOrderOrderChargeLines> AsResults(this SalesOrderSalesOrderOrderChargeLines_Response? response) => response?.D?.Results ?? [];
}
