// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesSalesPriceListGet_ResponseExtensions
{
    public static async Task<SalesSalesPriceList?> AsItem(this Task<SalesSalesPriceListGet_Response?> task)
    {
        return (await task)?.D;
    }
}
