// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesOrderDropShipmentGet_ResponseExtensions
{
    public static async Task<SalesOrderDropShipment?> AsItem(this Task<SalesOrderDropShipmentGet_Response?> task)
    {
        return (await task)?.D;
    }
}
