// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesInvoiceSalesInvoiceLines_ResponseExtensions
{
    public static async Task<List<SalesInvoiceSalesInvoiceLines>> AsResults(this Task<SalesInvoiceSalesInvoiceLines_Response?> task) => (await task)?.D?.Results ?? [];
}
