// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesOrderDropShipment_ResponseExtensions
{
    public static async Task<List<SalesOrderDropShipment>> AsItems(this Task<SalesOrderDropShipment_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.SalesOrderDropShipment ?? d.SalesOrderDropShipmentResults?.Results ?? [];
    }

}
