// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SalesOrderPlannedSalesReturnPost_ResponseExtensions
{
    public static async Task<SalesOrderPlannedSalesReturnPost?> AsItem(this Task<SalesOrderPlannedSalesReturnPost_Response?> task)
    {
        return (await task)?.D;
    }
}
