// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SubscriptionSubscriptionsPost_ResponseExtensions
{
    public static async Task<SubscriptionSubscriptionsPost?> AsItem(this Task<SubscriptionSubscriptionsPost_Response?> task)
    {
        return (await task)?.D;
    }
}
