// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SubscriptionSubscriptionLineTypes_ResponseExtensions
{
    public static async Task<List<SubscriptionSubscriptionLineTypes>> AsItems(this Task<SubscriptionSubscriptionLineTypes_Response?> task) => (await task)?.D?.Results ?? [];
}
