// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SubscriptionSubscriptionLines_ResponseExtensions
{
    public static async Task<List<SubscriptionSubscriptionLines>> AsItems(this Task<SubscriptionSubscriptionLines_Response?> task) => (await task)?.D?.Results ?? [];
}
