// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SubscriptionSubscriptionTypesGet_ResponseExtensions
{
    public static async Task<SubscriptionSubscriptionTypes?> AsItem(this Task<SubscriptionSubscriptionTypesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
