// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SubscriptionSubscriptions_ResponseExtensions
{
    public static List<SubscriptionSubscriptions> AsResults(this SubscriptionSubscriptions_Response? response) => response?.D?.Results ?? [];
}
