// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SubscriptionSubscriptionTypes_ResponseExtensions
{
    public static async Task<List<SubscriptionSubscriptionTypes>> AsResults(this Task<SubscriptionSubscriptionTypes_Response?> task) => (await task)?.D?.Results ?? [];
}
