// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SubscriptionSubscriptionRestrictionItemPost_ResponseExtensions
{
    public static async Task<SubscriptionSubscriptionRestrictionItemPost?> AsItem(this Task<SubscriptionSubscriptionRestrictionItemPost_Response?> task)
    {
        return (await task)?.D;
    }
}
