// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SubscriptionSubscriptionLine_ResponseExtensions
{
    public static async Task<List<SubscriptionSubscriptionLine>> AsItems(this Task<SubscriptionSubscriptionLine_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.SubscriptionSubscriptionLine ?? d.SubscriptionSubscriptionLineResults?.Results ?? [];
    }

}
