// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SubscriptionSubscriptionRestrictionEmployeesGet_ResponseExtensions
{
    public static async Task<SubscriptionSubscriptionRestrictionEmployees?> AsItem(this Task<SubscriptionSubscriptionRestrictionEmployeesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
