// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SubscriptionSubscriptionRestrictionItems_ResponseExtensions
{
    public static async Task<List<SubscriptionSubscriptionRestrictionItems>> AsItems(this Task<SubscriptionSubscriptionRestrictionItems_Response?> task) => (await task)?.D?.Results ?? [];
}
