// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SubscriptionSubscriptionPost_ResponseExtensions
{
    public static async Task<SubscriptionSubscriptionPost?> AsItem(this Task<SubscriptionSubscriptionPost_Response?> task)
    {
        return (await task)?.D;
    }
}
