// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SubscriptionSubscriptionRestrictionEmployee_ResponseExtensions
{
    public static async Task<List<SubscriptionSubscriptionRestrictionEmployee>> AsItems(this Task<SubscriptionSubscriptionRestrictionEmployee_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.SubscriptionSubscriptionRestrictionEmployee ?? d.SubscriptionSubscriptionRestrictionEmployeeResults?.Results ?? [];
    }

}
