// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SubscriptionSubscriptionReasonCodesGet_ResponseExtensions
{
    public static async Task<SubscriptionSubscriptionReasonCodes?> AsItem(this Task<SubscriptionSubscriptionReasonCodesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
