// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SubscriptionSubscriptionRestrictionEmployeePost_ResponseExtensions
{
    public static async Task<SubscriptionSubscriptionRestrictionEmployeePost?> AsItem(this Task<SubscriptionSubscriptionRestrictionEmployeePost_Response?> task)
    {
        return (await task)?.D;
    }
}
