// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncPayrollEmploymentCLAs_ResponseExtensions
{
    public static async Task<List<SyncPayrollEmploymentCLAs>> AsResults(this Task<SyncPayrollEmploymentCLAs_Response?> task) => (await task)?.D?.Results ?? [];
}
