// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncDocumentsDocuments_ResponseExtensions
{
    public static List<SyncDocumentsDocuments> AsResults(this SyncDocumentsDocuments_Response? response) => response?.D?.Results ?? [];
}
