// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncHRMScheduleEntries_ResponseExtensions
{
    public static async Task<List<SyncHRMScheduleEntries>> AsResults(this Task<SyncHRMScheduleEntries_Response?> task) => (await task)?.D?.Results ?? [];
}
