// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncManufacturingShopOrderMaterialPlanGet_ResponseExtensions
{
    public static async Task<SyncManufacturingShopOrderMaterialPlan?> AsItem(this Task<SyncManufacturingShopOrderMaterialPlanGet_Response?> task)
    {
        return (await task)?.D;
    }
}
