// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class SyncInventoryItemStorageLocations_Response
{
    public List<SyncInventoryItemStorageLocations> ToResults() => D?.Results ?? [];
}
