// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncPayrollEmploymentSalariesGet_ResponseExtensions
{
    public static async Task<SyncPayrollEmploymentSalaries?> AsItem(this Task<SyncPayrollEmploymentSalariesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
