namespace ExactOnline.Api.Client.Models;
public partial class SyncProjectProjectWBS
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(BlockEntry), "BlockEntry" },
        { nameof(BlockRebilling), "BlockRebilling" },
        { nameof(BudgetOverrunHours), "BudgetOverrunHours" },
        { nameof(BudgetedCost), "BudgetedCost" },
        { nameof(BudgetedHours), "BudgetedHours" },
        { nameof(BudgetedQuantity), "BudgetedQuantity" },
        { nameof(BudgetedRevenue), "BudgetedRevenue" },
        { nameof(Completed), "Completed" },
        { nameof(Created), "Created" },
        { nameof(Creator), "Creator" },
        { nameof(CreatorFullName), "CreatorFullName" },
        { nameof(CustomField), "CustomField" },
        { nameof(DefaultItem), "DefaultItem" },
        { nameof(DefaultItemIsMandatory), "DefaultItemIsMandatory" },
        { nameof(Description), "Description" },
        { nameof(Division), "Division" },
        { nameof(EndDate), "EndDate" },
        { nameof(ID), "ID" },
        { nameof(InvoiceDate), "InvoiceDate" },
        { nameof(InvoiceMethod), "InvoiceMethod" },
        { nameof(InvoiceSeparately), "InvoiceSeparately" },
        { nameof(MarkupPercentage), "MarkupPercentage" },
        { nameof(Metadata), "__metadata" },
        { nameof(Milestone), "Milestone" },
        { nameof(Modified), "Modified" },
        { nameof(Modifier), "Modifier" },
        { nameof(ModifierFullName), "ModifierFullName" },
        { nameof(Notes), "Notes" },
        { nameof(PartOf), "PartOf" },
        { nameof(PartOfDescription), "PartOfDescription" },
        { nameof(Project), "Project" },
        { nameof(ProjectDescription), "ProjectDescription" },
        { nameof(ProjectTerm), "ProjectTerm" },
        { nameof(ProjectTermDescription), "ProjectTermDescription" },
        { nameof(PurchasePrice), "PurchasePrice" },
        { nameof(SequenceNumber), "SequenceNumber" },
        { nameof(StartDate), "StartDate" },
        { nameof(Supplier), "Supplier" },
        { nameof(TimeQuantityToAlert), "TimeQuantityToAlert" },
        { nameof(Timestamp), "Timestamp" },
        { nameof(Type), "Type" }
    };
}
