// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncCRMAccountGet_ResponseExtensions
{
    public static async Task<SyncCRMAccount?> AsItem(this Task<SyncCRMAccountGet_Response?> task)
    {
        return (await task)?.D;
    }
}
