// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class SyncHRMLeaveAbsenceHoursByDay_Response
{
    public SyncHRMLeaveAbsenceHoursByDay? ToItem() => D?.Results?.FirstOrDefault();
}
