namespace ExactOnline.Api.Client.Models;
public partial class SyncCRMQuotationLines
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AmountDC), "AmountDC" },
        { nameof(AmountDiscount), "AmountDiscount" },
        { nameof(AmountDiscountExclVat), "AmountDiscountExclVat" },
        { nameof(AmountFC), "AmountFC" },
        { nameof(CostCenter), "CostCenter" },
        { nameof(CostCenterDescription), "CostCenterDescription" },
        { nameof(CostUnit), "CostUnit" },
        { nameof(CostUnitDescription), "CostUnitDescription" },
        { nameof(Created), "Created" },
        { nameof(Creator), "Creator" },
        { nameof(CreatorFullName), "CreatorFullName" },
        { nameof(CustomField), "CustomField" },
        { nameof(CustomerItemCode), "CustomerItemCode" },
        { nameof(Description), "Description" },
        { nameof(Discount), "Discount" },
        { nameof(Division), "Division" },
        { nameof(ID), "ID" },
        { nameof(Item), "Item" },
        { nameof(ItemDescription), "ItemDescription" },
        { nameof(LineNumber), "LineNumber" },
        { nameof(Metadata), "__metadata" },
        { nameof(Modified), "Modified" },
        { nameof(Modifier), "Modifier" },
        { nameof(ModifierFullName), "ModifierFullName" },
        { nameof(NetPrice), "NetPrice" },
        { nameof(Notes), "Notes" },
        { nameof(Optional), "Optional" },
        { nameof(Quantity), "Quantity" },
        { nameof(QuotationID), "QuotationID" },
        { nameof(QuotationNumber), "QuotationNumber" },
        { nameof(Timestamp), "Timestamp" },
        { nameof(UnitCode), "UnitCode" },
        { nameof(UnitDescription), "UnitDescription" },
        { nameof(UnitPrice), "UnitPrice" },
        { nameof(VATAmountFC), "VATAmountFC" },
        { nameof(VATCode), "VATCode" },
        { nameof(VATDescription), "VATDescription" },
        { nameof(VATPercentage), "VATPercentage" }
    };
}
