// <auto-generated/>
namespace ExactOnline.Api.Client.Models;

public partial class SyncPayrollEmploymentSalaries
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AmountType), "AmountType" },
        { nameof(AmountTypeDescription), "AmountTypeDescription" },
        { nameof(AverageDaysPerWeek), "AverageDaysPerWeek" },
        { nameof(AverageHoursPerWeek), "AverageHoursPerWeek" },
        { nameof(BillabilityTarget), "BillabilityTarget" },
        { nameof(Created), "Created" },
        { nameof(Creator), "Creator" },
        { nameof(CreatorFullName), "CreatorFullName" },
        { nameof(Description), "Description" },
        { nameof(Division), "Division" },
        { nameof(Employee), "Employee" },
        { nameof(EmployeeFullName), "EmployeeFullName" },
        { nameof(EmployeeHID), "EmployeeHID" },
        { nameof(Employment), "Employment" },
        { nameof(EmploymentNumber), "EmploymentNumber" },
        { nameof(EmploymentSalaryType), "EmploymentSalaryType" },
        { nameof(EmploymentSalaryTypeDescription), "EmploymentSalaryTypeDescription" },
        { nameof(EndDate), "EndDate" },
        { nameof(ExternalRate), "ExternalRate" },
        { nameof(Frequency), "Frequency" },
        { nameof(FrequencyDescription), "FrequencyDescription" },
        { nameof(FulltimeAmount), "FulltimeAmount" },
        { nameof(HourlyWage), "HourlyWage" },
        { nameof(ID), "ID" },
        { nameof(IntercompanyRate), "IntercompanyRate" },
        { nameof(InternalRate), "InternalRate" },
        { nameof(JobLevel), "JobLevel" },
        { nameof(Metadata), "__metadata" },
        { nameof(Modified), "Modified" },
        { nameof(Modifier), "Modifier" },
        { nameof(ModifierFullName), "ModifierFullName" },
        { nameof(ParttimeAmount), "ParttimeAmount" },
        { nameof(ParttimeFactor), "ParttimeFactor" },
        { nameof(SalaryBasedType), "SalaryBasedType" },
        { nameof(SalaryBasedTypeDescription), "SalaryBasedTypeDescription" },
        { nameof(Scale), "Scale" },
        { nameof(Schedule), "Schedule" },
        { nameof(ScheduleCode), "ScheduleCode" },
        { nameof(ScheduleDescription), "ScheduleDescription" },
        { nameof(StartDate), "StartDate" },
        { nameof(Timestamp), "Timestamp" },
        { nameof(WageScale), "WageScale" },
        { nameof(WageScalePeriod), "WageScalePeriod" },
        { nameof(WageScaleStep), "WageScaleStep" }
    };
}
