// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class SyncSalesOrderGoodsDeliveryLines_Response
{
    public List<SyncSalesOrderGoodsDeliveryLines> ToResults() => D?.Results ?? [];
}
