// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncDeletedGet_ResponseExtensions
{
    public static async Task<SyncDeleted?> AsItem(this Task<SyncDeletedGet_Response?> task)
    {
        return (await task)?.D;
    }
}
