// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncLogisticsSupplierItemGet_ResponseExtensions
{
    public static async Task<SyncLogisticsSupplierItem?> AsItem(this Task<SyncLogisticsSupplierItemGet_Response?> task)
    {
        return (await task)?.D;
    }
}
