// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncPayrollEmploymentSalaries_ResponseExtensions
{
    public static async Task<List<SyncPayrollEmploymentSalaries>> AsItems(this Task<SyncPayrollEmploymentSalaries_Response?> task) => (await task)?.D?.Results ?? [];
}
