// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncPayrollEmploymentTaxAuthoritiesGeneralGet_ResponseExtensions
{
    public static async Task<SyncPayrollEmploymentTaxAuthoritiesGeneral?> AsItem(this Task<SyncPayrollEmploymentTaxAuthoritiesGeneralGet_Response?> task)
    {
        return (await task)?.D;
    }
}
