// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncSalesOrderSalesOrderHeaders_ResponseExtensions
{
    public static List<SyncSalesOrderSalesOrderHeaders> AsResults(this SyncSalesOrderSalesOrderHeaders_Response? response) => response?.D?.Results ?? [];
}
