// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncManufacturingBillOfMaterialVersions_ResponseExtensions
{
    public static List<SyncManufacturingBillOfMaterialVersions> AsResults(this SyncManufacturingBillOfMaterialVersions_Response? response) => response?.D?.Results ?? [];
}
