// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncHRMLeaveBuildUpRegistrations_ResponseExtensions
{
    public static async Task<List<SyncHRMLeaveBuildUpRegistrations>> AsItems(this Task<SyncHRMLeaveBuildUpRegistrations_Response?> task) => (await task)?.D?.Results ?? [];
}
