// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncSalesOrderSalesOrderLines_ResponseExtensions
{
    public static List<SyncSalesOrderSalesOrderLines> AsResults(this SyncSalesOrderSalesOrderLines_Response? response) => response?.D?.Results ?? [];
}
