// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class SyncPayrollEmploymentOrganizations_Response
{
    public List<SyncPayrollEmploymentOrganizations> ToResults() => D?.Results ?? [];
}
