// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncPayrollEmploymentOrganizationsGet_ResponseExtensions
{
    public static async Task<SyncPayrollEmploymentOrganizations?> AsItem(this Task<SyncPayrollEmploymentOrganizationsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
