// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncFinancialGLClassification_ResponseExtensions
{
    public static async Task<List<SyncFinancialGLClassification>> AsItems(this Task<SyncFinancialGLClassification_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.SyncFinancialGLClassification ?? d.SyncFinancialGLClassificationResults?.Results ?? [];
    }

}
