// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncInventoryItemWarehouses_ResponseExtensions
{
    public static async Task<List<SyncInventoryItemWarehouses>> AsResults(this Task<SyncInventoryItemWarehouses_Response?> task) => (await task)?.D?.Results ?? [];
}
