// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncSalesInvoiceSalesInvoices_ResponseExtensions
{
    public static async Task<List<SyncSalesInvoiceSalesInvoices>> AsItems(this Task<SyncSalesInvoiceSalesInvoices_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.SyncSalesInvoiceSalesInvoices ?? d.SyncSalesInvoiceSalesInvoicesResults?.Results ?? [];
    }

}
