// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncManufacturingBillOfMaterialVersions_ResponseExtensions
{
    public static async Task<List<SyncManufacturingBillOfMaterialVersions>> AsItems(this Task<SyncManufacturingBillOfMaterialVersions_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.SyncManufacturingBillOfMaterialVersions ?? d.SyncManufacturingBillOfMaterialVersionsResults?.Results ?? [];
    }

}
