// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncPayrollEmployees_ResponseExtensions
{
    public static List<SyncPayrollEmployees> AsResults(this SyncPayrollEmployees_Response? response) => response?.D?.Results ?? [];
}
