// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class SyncManufacturingMaterialIssues_Response
{
    public List<SyncManufacturingMaterialIssues> ToResults() => D?.Results ?? [];
}
