// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncPayrollEmploymentSalaries_ResponseExtensions
{
    public static List<SyncPayrollEmploymentSalaries> AsResults(this SyncPayrollEmploymentSalaries_Response? response) => response?.D?.Results ?? [];
}
