// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncFinancialGLAccounts_ResponseExtensions
{
    public static List<SyncFinancialGLAccounts> AsResults(this SyncFinancialGLAccounts_Response? response) => response?.D?.Results ?? [];
}
