// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncCRMQuotationLines_ResponseExtensions
{
    public static List<SyncCRMQuotationLines> AsResults(this SyncCRMQuotationLines_Response? response) => response?.D?.Results ?? [];
}
