// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncCashflowPaymentTerm_ResponseExtensions
{
    public static async Task<List<SyncCashflowPaymentTerm>> AsItems(this Task<SyncCashflowPaymentTerm_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.SyncCashflowPaymentTerm ?? d.SyncCashflowPaymentTermResults?.Results ?? [];
    }

}
