// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncPayrollEmploymentOrganizations_ResponseExtensions
{
    public static async Task<List<SyncPayrollEmploymentOrganizations>> AsItems(this Task<SyncPayrollEmploymentOrganizations_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.SyncPayrollEmploymentOrganizations ?? d.SyncPayrollEmploymentOrganizationsResults?.Results ?? [];
    }

}
