// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncInventoryItemStorageLocationGet_ResponseExtensions
{
    public static async Task<SyncInventoryItemStorageLocation?> AsItem(this Task<SyncInventoryItemStorageLocationGet_Response?> task)
    {
        return (await task)?.D;
    }
}
