// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncInventoryStorageLocationStockPositions_ResponseExtensions
{
    public static async Task<List<SyncInventoryStorageLocationStockPositions>> AsItems(this Task<SyncInventoryStorageLocationStockPositions_Response?> task) => (await task)?.D?.Results ?? [];
}
