// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncInventoryItemStorageLocations_ResponseExtensions
{
    public static async Task<List<SyncInventoryItemStorageLocations>> AsItems(this Task<SyncInventoryItemStorageLocations_Response?> task) => (await task)?.D?.Results ?? [];
}
