// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncPayrollEmployments_ResponseExtensions
{
    public static List<SyncPayrollEmployments> AsResults(this SyncPayrollEmployments_Response? response) => response?.D?.Results ?? [];
}
