// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncManufacturingShopOrderMaterialPlansGet_ResponseExtensions
{
    public static async Task<SyncManufacturingShopOrderMaterialPlans?> AsItem(this Task<SyncManufacturingShopOrderMaterialPlansGet_Response?> task)
    {
        return (await task)?.D;
    }
}
