// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncManufacturingShopOrderRoutingStepPlans_ResponseExtensions
{
    public static async Task<List<SyncManufacturingShopOrderRoutingStepPlans>> AsResults(this Task<SyncManufacturingShopOrderRoutingStepPlans_Response?> task) => (await task)?.D?.Results ?? [];
}
