// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class SyncFinancialGLAccounts_Response
{
    public List<SyncFinancialGLAccounts> ToResults() => D?.Results ?? [];
}
