// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncInventoryItemWarehouseGet_ResponseExtensions
{
    public static async Task<SyncInventoryItemWarehouse?> AsItem(this Task<SyncInventoryItemWarehouseGet_Response?> task)
    {
        return (await task)?.D;
    }
}
