// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class SyncManufacturingShopOrderMaterialPlans_Response
{
    public List<SyncManufacturingShopOrderMaterialPlans> ToResults() => D?.Results ?? [];
}
