// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncLogisticsPurchaseItemPricesGet_ResponseExtensions
{
    public static async Task<SyncLogisticsPurchaseItemPrices?> AsItem(this Task<SyncLogisticsPurchaseItemPricesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
