// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncSubscriptionSubscriptionLine_ResponseExtensions
{
    public static async Task<List<SyncSubscriptionSubscriptionLine>> AsItems(this Task<SyncSubscriptionSubscriptionLine_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.SyncSubscriptionSubscriptionLine ?? d.SyncSubscriptionSubscriptionLineResults?.Results ?? [];
    }

}
