// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncSalesOrderGoodsDeliveryLines_ResponseExtensions
{
    public static List<SyncSalesOrderGoodsDeliveryLines> AsResults(this SyncSalesOrderGoodsDeliveryLines_Response? response) => response?.D?.Results ?? [];
}
