// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncInventoryStorageLocationStockPositions_ResponseExtensions
{
    public static async Task<List<SyncInventoryStorageLocationStockPositions>> AsItems(this Task<SyncInventoryStorageLocationStockPositions_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.SyncInventoryStorageLocationStockPositions ?? d.SyncInventoryStorageLocationStockPositionsResults?.Results ?? [];
    }

}
