// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncLogisticsSalesItemPrices_ResponseExtensions
{
    public static async Task<List<SyncLogisticsSalesItemPrices>> AsResults(this Task<SyncLogisticsSalesItemPrices_Response?> task) => (await task)?.D?.Results ?? [];
}
