// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class SyncProjectProjectPlanning_Response
{
    public SyncProjectProjectPlanning? ToItem() => D?.Results?.FirstOrDefault();
}
