// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncCRMAccounts_ResponseExtensions
{
    public static async Task<List<SyncCRMAccounts>> AsResults(this Task<SyncCRMAccounts_Response?> task) => (await task)?.D?.Results ?? [];
}
