// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncManufacturingShopOrders_ResponseExtensions
{
    public static List<SyncManufacturingShopOrders> AsResults(this SyncManufacturingShopOrders_Response? response) => response?.D?.Results ?? [];
}
