// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncInventorySerialBatchNumbers_ResponseExtensions
{
    public static async Task<List<SyncInventorySerialBatchNumbers>> AsItems(this Task<SyncInventorySerialBatchNumbers_Response?> task) => (await task)?.D?.Results ?? [];
}
