// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class SyncSalesSalesPriceListVolumeDiscounts_Response
{
    public List<SyncSalesSalesPriceListVolumeDiscounts> ToResults() => D?.Results ?? [];
}
