// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncDeleted_ResponseExtensions
{
    public static SyncDeleted? AsItem(this SyncDeleted_Response? response) => response?.D?.Results?.FirstOrDefault();
}
