// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class SyncPayrollEmploymentSalaries_Response
{
    public List<SyncPayrollEmploymentSalaries> ToResults() => D?.Results ?? [];
}
