// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class SyncProjectTimeCostTransactions_Response
{
    public List<SyncProjectTimeCostTransactions> ToResults() => D?.Results ?? [];
}
