// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SyncInventoryStorageLocationStockPositionsGet_ResponseExtensions
{
    public static async Task<SyncInventoryStorageLocationStockPositions?> AsItem(this Task<SyncInventoryStorageLocationStockPositionsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
