// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SystemSystemMe_ResponseExtensions
{
    public static SystemSystemMe? AsItem(this SystemSystemMe_Response? response) => response?.D?.Results?.FirstOrDefault();
}
