// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SystemSystemGetMostRecentlyUsedDivisionsGet_ResponseExtensions
{
    public static async Task<SystemSystemGetMostRecentlyUsedDivisions?> AsItem(this Task<SystemSystemGetMostRecentlyUsedDivisionsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
