// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SystemSystemAccountantInfo_ResponseExtensions
{
    public static async Task<List<SystemSystemAccountantInfo>> AsItems(this Task<SystemSystemAccountantInfo_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.SystemSystemAccountantInfo ?? d.SystemSystemAccountantInfoResults?.Results ?? [];
    }

}
