// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class SystemSystemAvailableFeatures_Response
{
    public List<SystemSystemAvailableFeatures> ToResults() => D?.Results ?? [];
}
