// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class SystemSystemAllDivisions_Response
{
    public List<SystemSystemAllDivisions> ToResults() => D?.Results ?? [];
}
