// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SystemSystemAvailableFeatures_ResponseExtensions
{
    public static async Task<List<SystemSystemAvailableFeatures>> AsItems(this Task<SystemSystemAvailableFeatures_Response?> task) => (await task)?.D?.Results ?? [];
}
