namespace ExactOnline.Api.Client.Models;
public partial class SystemSystemMe
{
    internal static readonly Dictionary<string, string> PropertyMapping = new()
    {
        { nameof(AccountingDivision), "AccountingDivision" },
        { nameof(CurrentDivision), "CurrentDivision" },
        { nameof(CustomerCode), "CustomerCode" },
        { nameof(DivisionCustomer), "DivisionCustomer" },
        { nameof(DivisionCustomerCode), "DivisionCustomerCode" },
        { nameof(DivisionCustomerName), "DivisionCustomerName" },
        { nameof(DivisionCustomerSiretNumber), "DivisionCustomerSiretNumber" },
        { nameof(DivisionCustomerVatNumber), "DivisionCustomerVatNumber" },
        { nameof(DossierDivision), "DossierDivision" },
        { nameof(Email), "Email" },
        { nameof(EmployeeID), "EmployeeID" },
        { nameof(FirstName), "FirstName" },
        { nameof(FullName), "FullName" },
        { nameof(Gender), "Gender" },
        { nameof(Initials), "Initials" },
        { nameof(IsClientUser), "IsClientUser" },
        { nameof(IsEmployeeSelfServiceUser), "IsEmployeeSelfServiceUser" },
        { nameof(IsMyFirmLiteUser), "IsMyFirmLiteUser" },
        { nameof(IsMyFirmPortalUser), "IsMyFirmPortalUser" },
        { nameof(IsOEIMigrationMandatory), "IsOEIMigrationMandatory" },
        { nameof(IsStarterUser), "IsStarterUser" },
        { nameof(Language), "Language" },
        { nameof(LanguageCode), "LanguageCode" },
        { nameof(LastName), "LastName" },
        { nameof(Legislation), "Legislation" },
        { nameof(Metadata), "__metadata" },
        { nameof(MiddleName), "MiddleName" },
        { nameof(Mobile), "Mobile" },
        { nameof(Nationality), "Nationality" },
        { nameof(PackageCode), "PackageCode" },
        { nameof(Phone), "Phone" },
        { nameof(PhoneExtension), "PhoneExtension" },
        { nameof(PictureUrl), "PictureUrl" },
        { nameof(ServerTime), "ServerTime" },
        { nameof(ServerUtcOffset), "ServerUtcOffset" },
        { nameof(ThumbnailPicture), "ThumbnailPicture" },
        { nameof(ThumbnailPictureFormat), "ThumbnailPictureFormat" },
        { nameof(Title), "Title" },
        { nameof(UserID), "UserID" },
        { nameof(UserName), "UserName" }
    };
}
