// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class SystemSystemAccountantInfoGet_ResponseExtensions
{
    public static async Task<SystemSystemAccountantInfo?> AsItem(this Task<SystemSystemAccountantInfoGet_Response?> task)
    {
        return (await task)?.D;
    }
}
