// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class UsersUserRolesPerDivision_ResponseExtensions
{
    public static async Task<List<UsersUserRolesPerDivision>> AsItems(this Task<UsersUserRolesPerDivision_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.UsersUserRolesPerDivision ?? d.UsersUserRolesPerDivisionResults?.Results ?? [];
    }

}
