// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class UsersUserHasRightsGet_ResponseExtensions
{
    public static async Task<UsersUserHasRights?> AsItem(this Task<UsersUserHasRightsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
