// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class VATVatPercentage_ResponseExtensions
{
    public static async Task<List<VATVatPercentage>> AsItems(this Task<VATVatPercentage_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.VATVatPercentage ?? d.VATVatPercentageResults?.Results ?? [];
    }

}
