// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class VATVatPercentages_Response
{
    public List<VATVatPercentages> ToResults() => D?.Results ?? [];
}
