// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class VATVATCodesGet_ResponseExtensions
{
    public static async Task<VATVATCodes?> AsItem(this Task<VATVATCodesGet_Response?> task)
    {
        return (await task)?.D;
    }
}
