// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class VATVATCodes_ResponseExtensions
{
    public static async Task<List<VATVATCodes>> AsItems(this Task<VATVATCodes_Response?> task)
    {
        var d = (await task)?.D;
        return d == null ? [] : d.VATVATCodes ?? d.VATVATCodesResults?.Results ?? [];
    }

}
