// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class WebhooksWebhookSubscriptionsPost_ResponseExtensions
{
    public static async Task<WebhooksWebhookSubscriptionsPost?> AsItem(this Task<WebhooksWebhookSubscriptionsPost_Response?> task)
    {
        return (await task)?.D;
    }
}
