// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class WorkflowRequestAttachments_ResponseExtensions
{
    public static List<WorkflowRequestAttachments> AsResults(this WorkflowRequestAttachments_Response? response) => response?.D?.Results ?? [];
}
