// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public partial class WorkflowRequestAttachments_Response
{
    public List<WorkflowRequestAttachments> ToResults() => D?.Results ?? [];
}
