// <auto-generated/>
#nullable enable
namespace ExactOnline.Api.Client.Models;

public static class WorkflowRequestAttachmentsGet_ResponseExtensions
{
    public static async Task<WorkflowRequestAttachments?> AsItem(this Task<WorkflowRequestAttachmentsGet_Response?> task)
    {
        return (await task)?.D;
    }
}
