// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Hrm.Divisions;

public partial class DivisionsRequestBuilder
{
    public async Task<HRMDivision_Response?> GetAllAsync(Action<RequestConfiguration<DivisionsRequestBuilder.DivisionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.HRMDivisionResults is null)
        {
            return response;
        }

        var allItems = new List<HRMDivision>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.HRMDivisionResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.HRMDivisionResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new DivisionsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new HRMDivision_Response
        {
            D = new HRMDivision_Response.HRMDivision_Response_d
            {
                HRMDivision = allItems
            }
        };

        return finalResponse;
    }
}
