// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Hrm.Costcenters;

public partial class CostcentersRequestBuilder
{
    public async Task<HRMCostcenter_Response?> GetAllAsync(Action<RequestConfiguration<CostcentersRequestBuilder.CostcentersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.HRMCostcenterResults is null)
        {
            return response;
        }

        var allItems = new List<HRMCostcenter>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.HRMCostcenterResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.HRMCostcenterResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new CostcentersRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new HRMCostcenter_Response
        {
            D = new HRMCostcenter_Response.HRMCostcenter_Response_d
            {
                HRMCostcenter = allItems
            }
        };

        return finalResponse;
    }
}
