// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Financial.AgingOverviewByAccount;

public partial class AgingOverviewByAccountRequestBuilder
{
    public async Task<ReadFinancialAgingOverviewByAccount_Response?> GetAllAsync(Action<RequestConfiguration<AgingOverviewByAccountRequestBuilder.AgingOverviewByAccountRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadFinancialAgingOverviewByAccountResults is null)
        {
            return response;
        }

        var allItems = new List<ReadFinancialAgingOverviewByAccount>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadFinancialAgingOverviewByAccountResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadFinancialAgingOverviewByAccountResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new AgingOverviewByAccountRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadFinancialAgingOverviewByAccount_Response
        {
            D = new ReadFinancialAgingOverviewByAccount_Response.ReadFinancialAgingOverviewByAccount_Response_d
            {
                ReadFinancialAgingOverviewByAccount = allItems
            }
        };

        return finalResponse;
    }
}
