// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sync.Logistics.SalesItemPrices;

public partial class SalesItemPricesRequestBuilder
{
    public async Task<SyncLogisticsSalesItemPrice_Response?> GetAllAsync(Action<RequestConfiguration<SalesItemPricesRequestBuilder.SalesItemPricesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SyncLogisticsSalesItemPriceResults is null)
        {
            return response;
        }

        var allItems = new List<SyncLogisticsSalesItemPrice>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SyncLogisticsSalesItemPriceResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SyncLogisticsSalesItemPriceResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new SalesItemPricesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SyncLogisticsSalesItemPrice_Response
        {
            D = new SyncLogisticsSalesItemPrice_Response.SyncLogisticsSalesItemPrice_Response_d
            {
                SyncLogisticsSalesItemPrice = allItems
            }
        };

        return finalResponse;
    }
}
