// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Project.ProjectPlanningRecurring;

public partial class ProjectPlanningRecurringRequestBuilder
{
    public async Task<ProjectProjectPlanningRecurring_Response?> GetAllAsync(Action<RequestConfiguration<ProjectPlanningRecurringRequestBuilder.ProjectPlanningRecurringRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ProjectProjectPlanningRecurringResults is null)
        {
            return response;
        }

        var allItems = new List<ProjectProjectPlanningRecurring>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ProjectProjectPlanningRecurringResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ProjectProjectPlanningRecurringResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ProjectPlanningRecurringRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ProjectProjectPlanningRecurring_Response
        {
            D = new ProjectProjectPlanningRecurring_Response.ProjectProjectPlanningRecurring_Response_d
            {
                ProjectProjectPlanningRecurring = allItems
            }
        };

        return finalResponse;
    }
}
