// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Project.CostTypes;

public partial class CostTypesRequestBuilder
{
    public async Task<ReadProjectCostType_Response?> GetAllAsync(Action<RequestConfiguration<CostTypesRequestBuilder.CostTypesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadProjectCostTypeResults is null)
        {
            return response;
        }

        var allItems = new List<ReadProjectCostType>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadProjectCostTypeResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadProjectCostTypeResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new CostTypesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadProjectCostType_Response
        {
            D = new ReadProjectCostType_Response.ReadProjectCostType_Response_d
            {
                ReadProjectCostType = allItems
            }
        };

        return finalResponse;
    }
}
