// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Crm.Documents;

public partial class DocumentsRequestBuilder
{
    public async Task<ReadCRMDocument_Response?> GetAllAsync(Action<RequestConfiguration<DocumentsRequestBuilder.DocumentsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadCRMDocumentResults is null)
        {
            return response;
        }

        var allItems = new List<ReadCRMDocument>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadCRMDocumentResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadCRMDocumentResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new DocumentsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadCRMDocument_Response
        {
            D = new ReadCRMDocument_Response.ReadCRMDocument_Response_d
            {
                ReadCRMDocument = allItems
            }
        };

        return finalResponse;
    }
}
