// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Crm.Documents;

public partial class DocumentsRequestBuilder
{
    public async Task<ReadCRMDocuments_Response?> GetAllAsync(Action<RequestConfiguration<DocumentsRequestBuilder.DocumentsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadCRMDocumentsResults is null)
        {
            return response;
        }

        var allItems = new List<ReadCRMDocuments>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadCRMDocumentsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadCRMDocumentsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new DocumentsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadCRMDocuments_Response
        {
            D = new ReadCRMDocuments_Response.ReadCRMDocuments_Response_d
            {
                ReadCRMDocuments = allItems
            }
        };

        return finalResponse;
    }
}
