using ExactOnline.Api.Client.Authentication.Interfaces;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Authentication;

namespace ExactOnline.Api.Client.Authentication.Kiota;

internal class ExactOnlineAuthenticationProvider(IExactTokenService tokenService) : IAuthenticationProvider
{
    private const string AuthorizationHeaderKey = "Authorization";

    public async Task AuthenticateRequestAsync(RequestInformation request, Dictionary<string, object>? additionalAuthenticationContext = null, CancellationToken cancellationToken = default)
    {
        var accessToken = await tokenService.GetAccessTokenAsync(cancellationToken);
        // var accessToken = "stampNL001.gAAAAH3cpQAgu05iVcGVrAq9HhrrmQiyOveAAOnUfPtMe-rzLCm3wjNdF93Jj7uvwZC9HIpGRJmfum7LWg4l12iOXD8tWqiQOImVQ098Y6Gc08XqQYwhV17KRK44R5q032s0veKbb3oVoCSVVWCvexlUFmT7eB3sQgdpaJw7AeKbBAQ8NAIAAIAAAACo4C2pZKpDxnszhPTn4qKR8RvZSFymLM70NzQ2P8_yl7G1MQcTtNhNTXY3an5-nmBmdjW9aRcLh_9VpmGM8DREUICNDR1X_VlHXMb_G9u_o9tPuUyyI0vHcRCA8wsMO7dnNLqg-NUfSDy2T1_bnJBayv0MJUIof51LQAcGLj04mu2XehoBk4vFr5cOEanK_Vq0ag6_Nu-IF604Vn516AUClkqYG9W2nXPANK1XApJEvhDEDqRDYSuxFdEPlhI9okw7EL4fp203lpxzTqRj5bwhYoOFoiUaLejxevpQ5xXc7Ni7Nfw6o3Px6kvVTO0stk6AW0F8YyOKq7zQIzJFZs3E0JoBIghaO2sgrgK7k3aB1hv5LfNZzYQf14FkjQ7RTHThPkxk_VMySygdkvsyKZ_rWfO-2CylGZSldofP5d3tPZ1Kx_Mq-g58-4bH9mb6Z5jxD7a_clkUfj7x7YEMGUgztF7Uow8W3ki_XcOuVPBgITLRkk9TPgW8ZqTh5mu_CwZRBBJ5HxSJgdCdlXV0BZAGkAOyYFf00R4q_g0L2K2jZBi-8enib4SksjjbdgnfI6wftFJStrdOj0DLt_H9ztc0J1sEd7sqw8RihQ7P6h5qBmjUgu_Y1N4Tv2LlqT2_nBcjxdS6SczyPHH1Pn9BDieDfTLUoY5X2exvgTnYvboEx6vFN0_7r-oucxbMc1N1YxBhdJaVOEaUoI_Gl5P4fPOYd2KEwWnNDNljm7bbeND4kA";

        request.Headers.Add(AuthorizationHeaderKey, $"Bearer {accessToken}");
    }
}