// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Payroll.ActiveEmployments;

public partial class ActiveEmploymentsRequestBuilder
{
    public async Task<PayrollActiveEmployment_Response?> GetAllAsync(Action<RequestConfiguration<ActiveEmploymentsRequestBuilder.ActiveEmploymentsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.PayrollActiveEmploymentResults is null)
        {
            return response;
        }

        var allItems = new List<PayrollActiveEmployment>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.PayrollActiveEmploymentResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.PayrollActiveEmploymentResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ActiveEmploymentsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new PayrollActiveEmployment_Response
        {
            D = new PayrollActiveEmployment_Response.PayrollActiveEmployment_Response_d
            {
                PayrollActiveEmployment = allItems
            }
        };

        return finalResponse;
    }
}
