// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Users.UserHasRights;

public partial class UserHasRightsRequestBuilder
{
    public async Task<UsersUserHasRight_Response?> GetAllAsync(Action<RequestConfiguration<UserHasRightsRequestBuilder.UserHasRightsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.UsersUserHasRightResults is null)
        {
            return response;
        }

        var allItems = new List<UsersUserHasRight>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.UsersUserHasRightResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.UsersUserHasRightResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new UserHasRightsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new UsersUserHasRight_Response
        {
            D = new UsersUserHasRight_Response.UsersUserHasRight_Response_d
            {
                UsersUserHasRight = allItems
            }
        };

        return finalResponse;
    }
}
