// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Financial.RevenueList;

public partial class RevenueListRequestBuilder
{
    public async Task<ReadFinancialRevenueList_Response?> GetAllAsync(Action<RequestConfiguration<RevenueListRequestBuilder.RevenueListRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadFinancialRevenueListResults is null)
        {
            return response;
        }

        var allItems = new List<ReadFinancialRevenueList>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadFinancialRevenueListResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadFinancialRevenueListResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new RevenueListRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadFinancialRevenueList_Response
        {
            D = new ReadFinancialRevenueList_Response.ReadFinancialRevenueList_Response_d
            {
                ReadFinancialRevenueList = allItems
            }
        };

        return finalResponse;
    }
}
