// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Expensemanagement.ExpenseReports;

public partial class ExpenseReportsRequestBuilder
{
    public async Task<ExpenseManagementExpenseReport_Response?> GetAllAsync(Action<RequestConfiguration<ExpenseReportsRequestBuilder.ExpenseReportsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ExpenseManagementExpenseReportResults is null)
        {
            return response;
        }

        var allItems = new List<ExpenseManagementExpenseReport>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ExpenseManagementExpenseReportResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ExpenseManagementExpenseReportResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ExpenseReportsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ExpenseManagementExpenseReport_Response
        {
            D = new ExpenseManagementExpenseReport_Response.ExpenseManagementExpenseReport_Response_d
            {
                ExpenseManagementExpenseReport = allItems
            }
        };

        return finalResponse;
    }
}
