// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Crm.QuotationLines;

public partial class QuotationLinesRequestBuilder
{
    public async Task<CRMQuotationLine_Response?> GetAllAsync(Action<RequestConfiguration<QuotationLinesRequestBuilder.QuotationLinesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.CRMQuotationLineResults is null)
        {
            return response;
        }

        var allItems = new List<CRMQuotationLine>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.CRMQuotationLineResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.CRMQuotationLineResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new QuotationLinesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new CRMQuotationLine_Response
        {
            D = new CRMQuotationLine_Response.CRMQuotationLine_Response_d
            {
                CRMQuotationLine = allItems
            }
        };

        return finalResponse;
    }
}
