// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Project.HourEntryRecentHourTypesByProject;

public partial class HourEntryRecentHourTypesByProjectRequestBuilder
{
    public async Task<ReadProjectHourEntryRecentHourTypesByProject_Response?> GetAllAsync(Action<RequestConfiguration<HourEntryRecentHourTypesByProjectRequestBuilder.HourEntryRecentHourTypesByProjectRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadProjectHourEntryRecentHourTypesByProjectResults is null)
        {
            return response;
        }

        var allItems = new List<ReadProjectHourEntryRecentHourTypesByProject>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadProjectHourEntryRecentHourTypesByProjectResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadProjectHourEntryRecentHourTypesByProjectResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new HourEntryRecentHourTypesByProjectRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadProjectHourEntryRecentHourTypesByProject_Response
        {
            D = new ReadProjectHourEntryRecentHourTypesByProject_Response.ReadProjectHourEntryRecentHourTypesByProject_Response_d
            {
                ReadProjectHourEntryRecentHourTypesByProject = allItems
            }
        };

        return finalResponse;
    }
}
