// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Project.ProjectRestrictionRebillings;

public partial class ProjectRestrictionRebillingsRequestBuilder
{
    public async Task<ProjectProjectRestrictionRebillings_Response?> GetAllAsync(Action<RequestConfiguration<ProjectRestrictionRebillingsRequestBuilder.ProjectRestrictionRebillingsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ProjectProjectRestrictionRebillingsResults is null)
        {
            return response;
        }

        var allItems = new List<ProjectProjectRestrictionRebillings>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ProjectProjectRestrictionRebillingsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ProjectProjectRestrictionRebillingsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ProjectRestrictionRebillingsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ProjectProjectRestrictionRebillings_Response
        {
            D = new ProjectProjectRestrictionRebillings_Response.ProjectProjectRestrictionRebillings_Response_d
            {
                ProjectProjectRestrictionRebillings = allItems
            }
        };

        return finalResponse;
    }
}
