// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Logistics.StockPosition;

public partial class StockPositionRequestBuilder
{
    public async Task<ReadLogisticsStockPosition_Response?> GetAllAsync(Action<RequestConfiguration<StockPositionRequestBuilder.StockPositionRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadLogisticsStockPositionResults is null)
        {
            return response;
        }

        var allItems = new List<ReadLogisticsStockPosition>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadLogisticsStockPositionResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadLogisticsStockPositionResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new StockPositionRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadLogisticsStockPosition_Response
        {
            D = new ReadLogisticsStockPosition_Response.ReadLogisticsStockPosition_Response_d
            {
                ReadLogisticsStockPosition = allItems
            }
        };

        return finalResponse;
    }
}
