// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Inventory.ItemWarehouseStorageLocations;

public partial class ItemWarehouseStorageLocationsRequestBuilder
{
    public async Task<InventoryItemWarehouseStorageLocation_Response?> GetAllAsync(Action<RequestConfiguration<ItemWarehouseStorageLocationsRequestBuilder.ItemWarehouseStorageLocationsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.InventoryItemWarehouseStorageLocationResults is null)
        {
            return response;
        }

        var allItems = new List<InventoryItemWarehouseStorageLocation>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.InventoryItemWarehouseStorageLocationResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.InventoryItemWarehouseStorageLocationResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ItemWarehouseStorageLocationsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new InventoryItemWarehouseStorageLocation_Response
        {
            D = new InventoryItemWarehouseStorageLocation_Response.InventoryItemWarehouseStorageLocation_Response_d
            {
                InventoryItemWarehouseStorageLocation = allItems
            }
        };

        return finalResponse;
    }
}
