// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Financial.PayablesListByAccount;

public partial class PayablesListByAccountRequestBuilder
{
    public async Task<ReadFinancialPayablesListByAccount_Response?> GetAllAsync(Action<RequestConfiguration<PayablesListByAccountRequestBuilder.PayablesListByAccountRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadFinancialPayablesListByAccountResults is null)
        {
            return response;
        }

        var allItems = new List<ReadFinancialPayablesListByAccount>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadFinancialPayablesListByAccountResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadFinancialPayablesListByAccountResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new PayablesListByAccountRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadFinancialPayablesListByAccount_Response
        {
            D = new ReadFinancialPayablesListByAccount_Response.ReadFinancialPayablesListByAccount_Response_d
            {
                ReadFinancialPayablesListByAccount = allItems
            }
        };

        return finalResponse;
    }
}
