<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>ExactOnline REST API Client with interfaces and proxy (useful for mocking in unit-tests)</Description>
    <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
    <PackageTags>C#;APIs;Clients;Generated;Interface;Proxy</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ProxyInterfaceGenerator" Version="0.9.1-preview-01">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExactOnline.Api.Client\ExactOnline.Api.Client.csproj" />
  </ItemGroup>

</Project>