// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Logistics.Items;

public partial class ItemsRequestBuilder
{
    public async Task<LogisticsItems_Response?> GetAllAsync(Action<RequestConfiguration<ItemsRequestBuilder.ItemsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.LogisticsItemsResults is null)
        {
            return response;
        }

        var allItems = new List<LogisticsItems>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.LogisticsItemsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.LogisticsItemsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new ItemsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new LogisticsItems_Response
        {
            D = new LogisticsItems_Response.LogisticsItems_Response_d
            {
                LogisticsItems = allItems
            }
        };

        return finalResponse;
    }
}
