// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Read.Project.TimeAndBillingProjectDetails;

public partial class TimeAndBillingProjectDetailsRequestBuilder
{
    public async Task<ReadProjectTimeAndBillingProjectDetails_Response?> GetAllAsync(Action<RequestConfiguration<TimeAndBillingProjectDetailsRequestBuilder.TimeAndBillingProjectDetailsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.ReadProjectTimeAndBillingProjectDetailsResults is null)
        {
            return response;
        }

        var allItems = new List<ReadProjectTimeAndBillingProjectDetails>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.ReadProjectTimeAndBillingProjectDetailsResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.ReadProjectTimeAndBillingProjectDetailsResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new TimeAndBillingProjectDetailsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new ReadProjectTimeAndBillingProjectDetails_Response
        {
            D = new ReadProjectTimeAndBillingProjectDetails_Response.ReadProjectTimeAndBillingProjectDetails_Response_d
            {
                ReadProjectTimeAndBillingProjectDetails = allItems
            }
        };

        return finalResponse;
    }
}
