// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Sync.Inventory.SerialBatchNumbers;

public partial class SerialBatchNumbersRequestBuilder
{
    public async Task<SyncInventorySerialBatchNumber_Response?> GetAllAsync(Action<RequestConfiguration<SerialBatchNumbersRequestBuilder.SerialBatchNumbersRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SyncInventorySerialBatchNumberResults is null)
        {
            return response;
        }

        var allItems = new List<SyncInventorySerialBatchNumber>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SyncInventorySerialBatchNumberResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SyncInventorySerialBatchNumberResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new SerialBatchNumbersRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SyncInventorySerialBatchNumber_Response
        {
            D = new SyncInventorySerialBatchNumber_Response.SyncInventorySerialBatchNumber_Response_d
            {
                SyncInventorySerialBatchNumber = allItems
            }
        };

        return finalResponse;
    }
}
