// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Users.UserRolesPerDivision;

public partial class UserRolesPerDivisionRequestBuilder
{
    public async Task<UsersUserRolesPerDivision_Response?> GetAllAsync(Action<RequestConfiguration<UserRolesPerDivisionRequestBuilder.UserRolesPerDivisionRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.UsersUserRolesPerDivisionResults is null)
        {
            return response;
        }

        var allItems = new List<UsersUserRolesPerDivision>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.UsersUserRolesPerDivisionResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.UsersUserRolesPerDivisionResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new UserRolesPerDivisionRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new UsersUserRolesPerDivision_Response
        {
            D = new UsersUserRolesPerDivision_Response.UsersUserRolesPerDivision_Response_d
            {
                UsersUserRolesPerDivision = allItems
            }
        };

        return finalResponse;
    }
}
