// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Payroll.EmploymentOrganizations;

public partial class EmploymentOrganizationsRequestBuilder
{
    public async Task<PayrollEmploymentOrganization_Response?> GetAllAsync(Action<RequestConfiguration<EmploymentOrganizationsRequestBuilder.EmploymentOrganizationsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.PayrollEmploymentOrganizationResults is null)
        {
            return response;
        }

        var allItems = new List<PayrollEmploymentOrganization>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.PayrollEmploymentOrganizationResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.PayrollEmploymentOrganizationResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new EmploymentOrganizationsRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new PayrollEmploymentOrganization_Response
        {
            D = new PayrollEmploymentOrganization_Response.PayrollEmploymentOrganization_Response_d
            {
                PayrollEmploymentOrganization = allItems
            }
        };

        return finalResponse;
    }
}
