name: Publish to NuGet

on:
  workflow_dispatch:

jobs:
  publish:
    name: Build, Pack, and Publish
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build solution
      run: dotnet build ./ExactOnline.sln -c Release

    - name: Pack projects
      run: dotnet pack ./ExactOnline.sln -c Release --no-build -o ./packages

    - name: Push to NuGet
      run: dotnet nuget push "**/packages/ExactOnline.*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate