// <auto-generated/>
#nullable enable
using System.Linq.Expressions;
using ExactOnline.Api.Client.Models;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Abstractions.Serialization;

namespace ExactOnline.Api.Client.Api.V1.Item.Subscription.SubscriptionTypes;

public partial class SubscriptionTypesRequestBuilder
{
    public async Task<SubscriptionSubscriptionType_Response?> GetAllAsync(Action<RequestConfiguration<SubscriptionTypesRequestBuilder.SubscriptionTypesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
        var response = await GetAsync(requestConfiguration, cancellationToken);
        if (response?.D?.SubscriptionSubscriptionTypeResults is null)
        {
            return response;
        }

        var allItems = new List<SubscriptionSubscriptionType>();
        var currentResponse = response;

        while (true)
        {
            if (currentResponse?.D?.SubscriptionSubscriptionTypeResults?.Results is { } results)
            {
                allItems.AddRange(results);
            }

            var nextUrl = currentResponse?.D?.SubscriptionSubscriptionTypeResults?.Next;
            if (string.IsNullOrEmpty(nextUrl))
            {
                break;
            }

            var nextRequestBuilder = new SubscriptionTypesRequestBuilder(nextUrl, RequestAdapter);
            currentResponse = await nextRequestBuilder.GetAsync(cancellationToken: cancellationToken);
        }

        var finalResponse = new SubscriptionSubscriptionType_Response
        {
            D = new SubscriptionSubscriptionType_Response.SubscriptionSubscriptionType_Response_d
            {
                SubscriptionSubscriptionType = allItems
            }
        };

        return finalResponse;
    }
}
